### ISSUE TITLE
When downloading a profiles images, instaloader stops at the 12th post

### ISSUE THREAD

**Issue by uzzywastaken** [instaloader/instaloader#1293] opened 2021-09-23 12:22 UTC
![d32554062e20fa5bb095477512ecb609](https://user-images.githubusercontent.com/89166344/134505870-ee3c606f-f421-4898-a795-492e325ef61a.png)

**Comment by 89z** [comment] 2021-09-23 17:19
Same problem

**Comment by Showmaster3000** [comment] 2021-09-23 22:03
The error message is clear: you have to login to proceed. Use additional parameter `--login your-account` to get all elements.
Duplicate of #1263.

**Closed by Showmaster3000** 2021-09-23 22:03 UTC
