### ISSUE TITLE
:feed: JSON Query to graphql/query: HTTP error code 500.

### ISSUE THREAD

**Issue by kygger** [instaloader/instaloader#531] opened 2020-02-27 10:40 UTC
**Describe the bug**
after login, download "feed", and error occured.

**To Reproduce**
instaloader ":feed" -l "ID" --count 5000 --fast-update --no-video-thumbnails --no-captions --no-metadata-json --no-compress-json --filename-pattern "{date_utc} {owner_username} {shortcode}"

**Expected behavior**
maybe Instagram changed policy   :(

**Error messages and tracebacks**
------------------------------------------------------------

JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
:feed: JSON Query to graphql/query: HTTP error code 500.
Saved session to d:\users\ID\appdata\local\temp/.instaloader-ID/session-ID.

Errors occured:
:feed: JSON Query to graphql/query: HTTP error code 500.

------------------------------------------------------------

**Instaloader version**
4.3a1

**Additional context**
same error occured with version 4.2.10

**Comment by aandergr** [comment] 2020-03-03 08:14
Duplicate of #516.

> Error code 500 means [Internal Server Error](https://http.cat/500), a problem on the server side which we cannot fix. If that error appears, Instaloader retries the request a few times, and if it continues to fail, it aborts.

**Closed by aandergr** 2020-03-03 08:14 UTC
Labels: bug
