### ISSUE TITLE
Saving files with caption doesn't work in Windows

### ISSUE THREAD

**Issue by fabmedeiros** [instaloader/instaloader#1482] opened 2022-04-08 16:30 UTC
**Describe the bug**
I'm trying download all posts from instagram.com/biblicalvocabulary. But this error occurs:

```
[1/1] Downloading profile biblicalvocabulary
Retrieving posts from profile biblicalvocabulary.
[   1/2895] biblicalvocabulary\2022-04-08_13-01-25_⭐️ Today's Biblical Vocabulary： πάσχα, τό, 29x . More biblical data on the blog： biblicalvocabulary.com .  . . . #biblicalvocabulary #bible  #biblestudy #scripture #newtestament #biblical #biblicalgreek #vocabulary #vocab #greek #greeknt #greeknewtestament #koine #koinegreek #language #theology #christian #christianity #biblequote #bibleverse.jpg Traceback (most recent call last):
  File "C:\Python3\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9', 'console_scripts', 'instaloader')())
  File "C:\Python3\lib\site-packages\instaloader\__main__.py", line 471, in main
    _main(loader,
  File "C:\Python3\lib\site-packages\instaloader\__main__.py", line 220, in _main
    instaloader.download_profiles(profiles,
  File "C:\Python3\lib\site-packages\instaloader\instaloader.py", line 1461, in download_profiles
    self.posts_download_loop(posts_to_download, profile_name, fast_update, post_filter,
  File "C:\Python3\lib\site-packages\instaloader\instaloader.py", line 1040, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "C:\Python3\lib\site-packages\instaloader\instaloader.py", line 739, in download_post
    self.download_pic(filename=filename, url=post.url, mtime=post.date_local))
  File "C:\Python3\lib\site-packages\instaloader\instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "C:\Python3\lib\site-packages\instaloader\instaloader.py", line 356, in download_pic
    self.context.write_raw(resp, filename)
  File "C:\Python3\lib\site-packages\instaloader\instaloadercontext.py", line 495, in write_raw
    with open(filename + '.temp', 'wb') as file:
OSError: [Errno 22] Invalid argument: "biblicalvocabulary\\2022-04-08_13-01-25_⭐️ Today's Biblical Vocabulary： πάσχα, τό, 29x . More biblical data on the blog： biblicalvocabulary.com .  . . . #biblicalvocabulary #bible  #biblestudy #scripture #newtestament #biblical #biblicalgreek #vocabulary #vocab #greek #greeknt #greeknewtestament #koine #koinegreek #language #theology #christian #christianity #biblequote #bibleverse.jpg.temp"
```

**To Reproduce**
`instaloader --sanitize-paths --no-profile-pic --no-captions --no-metadata-json --filename-pattern={date_utc}_{caption} biblicalvocabulary`

**Expected behavior**
Save files without the ":"

**Instaloader version**
`instaloader --version` 4.9

**Comment by aandergr** [comment] 2022-04-18 09:36
Duplicate of #262

**Closed by aandergr** 2022-04-18 09:36 UTC
Labels: duplicate
