### ISSUE TITLE
400,401 Behavior since one month

### ISSUE THREAD

**Issue by yah00078** [instaloader/instaloader#2445] opened 2024-11-25 10:20 UTC
Describe the bug
When attempting to scrape followees using profile.get_followees(), the script throws a QueryReturnedBadRequestException with a 400 Bad Request response and a message indicating "checkpoint_required".

To Reproduce

Use the following command to attempt scraping followees of a profile:

profile = instaloader.Profile.from_username(L.context, 'username')
followees = list(profile.get_followees())

Run the script.

Observe the error traceback.

Expected behavior
The script should retrieve the followees of the specified profile without encountering a 400 Bad Request error.

Error messages and tracebacks

Traceback (most recent call last):
  File "/scripts/Insta/Instabot_Scrapper.py", line 578, in <module>
    main()
  File "/scripts/Insta/Instabot_Scrapper.py", line 538, in main
    Scrap('Following',followings_file)
  File "/scripts/Insta/Instabot_Scrapper.py", line 426, in Scrap
    get = list(profile.get_followees())
  File "/scripts/venv392/lib/python3.9/site-packages/instaloader/nodeiterator.py", line 160, in __next__
    query_response = self._query(self._data['page_info']['end_cursor'])
  File "/scripts/venv392/lib/python3.9/site-packages/instaloader/nodeiterator.py", line 109, in _query
    return self._query_query_hash(self._query_hash, after)
  File "/scripts/venv392/lib/python3.9/site-packages/instaloader/nodeiterator.py", line 131, in _query_query_hash
    self._context.graphql_query(
  File "/scripts/venv392/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/scripts/venv392/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 450, in get_json
    raise QueryReturnedBadRequestException(self._response_error(resp))
instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request - "fail" status, message "checkpoint_required" when accessing https://www.instagram.com/graphql/query?query_hash=58712303d941c6855d4e888c5*****&variables=%7B%22id%22%3A%22254629798%22%2C%22first%22%3A12%2C%22after%22%3A%22QVFBTzRuSjdIcnpMaDRub01mbVlQS1hNVGVDZllrWno1YS1Pd2l1S3hHc2dJSXRkdHBIaTB4cVJxMklpSEMxcUN***************************************************

Instaloader version
instaloader --version output: (Please replace with your version)

Additional context

The issue seems to be related to recent changes in Instagram's API behavior.

The "checkpoint_required" message suggests that additional authentication or verification may now be required to proceed.

The session used in the script was freshly created and valid.

Adding delays between requests did not resolve the issue, Using cookie do the same result for me, changing Ex IP too. 

My script has been working for many month/years one time a week randomly (Not spamming API, not using 2FA), so I think about external changes (instagram added a check point? But we don't have checkpoint url.)

Thank you for your help

**Comment by Tinchox17** [comment] 2024-11-27 01:46
Same, i get 400 error

**Comment by aandergr** [comment] 2024-11-28 08:45
Thank you for the report. However, the bug report lacks some crucial details, such as the version of Instaloader you're using, which is essential for investigating the issue further.

That said, the `get_followees()` method works fine on my end, and I cannot reproduce the issue with the information provided. Additionally, the error message you're encountering mentions "checkpoint_required" and a 400 Bad Request, but it doesn't indicate a 401 error as the title suggests.

Please provide the Instaloader version and any other relevant details to help us troubleshoot further.

**Comment by Tinchox17** [comment] 2024-11-28 13:26
If it help you, i solve mine. my instagram account for instaloader was log off, i got the suspect activity message. i log in, refrresh and the try again. worked

**Comment by yah00078** [comment] 2024-11-28 14:49
In my Case I can login on every device, but not with instaloader On 28 Nov 2024, at 14:26, Tinchox17 ***@***.***> wrote:﻿
If it help you, i solve mine. my instagram account for instaloader was log off, i got the suspect activity message. i log in, refrresh and the try again. worked

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
​Click on me

**Comment by aandergr** [comment] 2024-12-27 07:25
This issue appears to be a duplicate of #2307, as both describe similar errors related to Instagram's API responses (`401 Unauthorized`, `400 Bad Request`) and behavior changes affecting session handling. Please refer to #2307 for updates and ongoing discussions about this issue. 

We’ll close this issue to keep the discussion consolidated in one place. If you believe your issue differs significantly, feel free to provide additional context.

**Closed by aandergr** 2024-12-27 07:25 UTC
Labels: duplicate
