### ISSUE TITLE
download_hashtag

### ISSUE THREAD

**Issue by deank1** [instaloader/instaloader#1708] opened 2022-08-22 00:38 UTC
Anyone else experiencing issues with the download_hashtag method. Using the following code: 

import instaloader
scraper = instaloader.Instaloader()
scraper.download_hashtag('cat')

Error code occurring: 
JSON Query to explore/tags/cat/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
JSON Query to explore/tags/cat/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
Get hashtag #cat: JSON Query to explore/tags/cat/: Expecting value: line 1 column 1 (char 0)

**Comment by deank1** [comment] 2022-08-22 01:21
Saw the similarity in: https://github.com/instaloader/instaloader/issues/1588. Any updates on this?

**Comment by Showmaster3000** [comment] 2022-08-22 10:48
no update. As you mentioned: duplicate of #1588. So closing.

**Closed by Showmaster3000** 2022-08-22 10:48 UTC
Labels: question
