### ISSUE TITLE
Some reels names/titles are broken

### ISSUE THREAD

**Issue by worthl3ss** [instaloader/instaloader#1459] opened 2022-03-19 13:53 UTC
**Describe the bug**
Having reels with the names "." and ".." (without the "), breakes instaloader and goes in back one and 2 directories

**To Reproduce**
Make a reel on your profile with the name .. and run instaloader, the media from that reel will be downloaded in the folder you ran the command instead of ./profilename/reelname

**Expected behavior**
The reel names should be replace with characters that do not break filesystems

**Instaloader version**
4.8.4

**Additional context**
The same is true for having a reel named aux or con and trying to run instaloader on windows

**Comment by worthl3ss** [comment] 2022-03-19 13:55
A general fix would be checking if the reel names contains invalid characters and remove them. If the name left is empty just make folders like reels, reels1, reels2, for invalid named reels.

**Comment by aandergr** [comment] 2022-03-26 16:33
Duplicate of #1252

**Closed by aandergr** 2022-03-26 16:33 UTC
Labels: duplicate
