### ISSUE TITLE
Program crashes / "expected string or bytes-like object"

### ISSUE THREAD

**Issue by catharsis71** [instaloader/instaloader#1829] opened 2022-12-11 16:13 UTC
**Describe the bug**

Program crashes with error

**To Reproduce**

```instaloader "#crackychan"```

**Expected behavior**

program runs without crashing

**Error messages and tracebacks**

```
#crackychan/2022-01-16_00-16-43_UTC_profile_pic.jpg already exists
Retrieving pictures with hashtag #crackychan...
[  1] #crackychan/2022-12-02_04-03-04_UTC.jpg exists [i want you so bad i can taste…] unchanged json
[  2] #crackychan/2022-11-08_04-44-09_UTC.jpg exists [my everlasting catharsis, how…] unchanged json
[  3] #crackychan/2022-10-28_02-08-20_UTC.jpg exists json
[  4] #crackychan/2022-10-13_05-50-47_UTC.jpg exists [HBD. #crackychan #skyqueen #a…] unchanged json
[  5] JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Download <Post CjmfC-IOSgp> of #crackychan: JSON Query to graphql/query: HTTP error code 401.
[  6] #crackychan/2022-09-17_03-33-14_UTC.jpg exists [i'm your opheliac, my stockin…] unchanged json
[  7] JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Download <Post CiOyyQ1ObWU> of #crackychan: JSON Query to graphql/query: HTTP error code 401.
[  8] JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Download <Post Ch_BKNohME5> of #crackychan: JSON Query to graphql/query: HTTP error code 401.
[  9] JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Download <Post ChtCsCbu0Bk> of #crackychan: JSON Query to graphql/query: HTTP error code 401.
[ 10] #crackychan/2022-07-15_02-28-55_UTC.jpg exists [flowing freely, your ebony ha…] unchanged json
[ 11] #crackychan/2022-06-07_01-52-37_UTC.jpg exists [present day, present time.  t…] unchanged json
[ 12] #crackychan/2022-06-06_19-19-39_UTC.jpg exists [#skyqueen #crackychan #4chanm…] unchanged json
[ 13] #crackychan/2022-05-20_21-34-29_UTC.jpg exists [The Original Queen  #crackych…] unchanged json
[ 14] #crackychan/2022-05-19_15-48-32_UTC.jpg exists [No c dibujar gente de lado Su…] unchanged json
[ 15] #crackychan/2022-04-19_17-41-43_UTC.jpg exists [i didn't know i had a dream. …] unchanged json
[ 16] JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Download <Post Cbtwo1mr6dm> of #crackychan: JSON Query to graphql/query: HTTP error code 401.
[ 17] #crackychan/2022-03-28_19-04-15_UTC.jpg exists [🤣 🤭 How can man say this is C…] unchanged JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Warning: Unable to fetch video from graphql of <Post CbqJTzPFT8q>: JSON Query to graphql/query: HTTP error code 401.
Traceback (most recent call last):
  File "/home/username/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.10/site-packages/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "/home/username/.local/lib/python3.10/site-packages/instaloader/__main__.py", line 164, in _main
    instaloader.download_hashtag(hashtag=target[1:], max_count=max_count, fast_update=fast_update,
  File "/home/username/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 1223, in download_hashtag
    self.posts_download_loop(hashtag.get_posts_resumable(), target, fast_update, post_filter,
  File "/home/username/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 1047, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/home/username/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 756, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
  File "/home/username/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 340, in download_pic
    urlmatch = re.search('\\.[a-z0-9]*\\?', url)
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Instaloader version**

4.9.5

**Comment by ciaomark** [comment] 2022-12-11 23:06
I get this a lot too.

**Comment by aandergr** [comment] 2022-12-29 09:32
Duplicate of #1802

**Closed by aandergr** 2022-12-29 09:32 UTC
Labels: bug
