### ISSUE TITLE
Let users customize/finetune Instaloader's request rate limiting

### ISSUE THREAD

**Issue by EveryDirection** [instaloader/instaloader#1922] opened 2023-03-20 10:05 UTC
As evidenced by the large number of issues posted about Instagram temporarily blocking or more permanently suspending or banning accounts, Instaloader's current request rate limits are insufficient.

Please add command-line options to let the user customize/finetune the request rate-limiting. For example, you would probably want stricter rate-limiting when downloading profiles with hundreds of posts (because downloading all that is more likely to trigger Instagram's anti-bot heuristics) than with a profile that only has a few tens of posts.

Some possible suggestions (and I'm sure other users can suggest other ideas):

- letting the user set longer times between consecutive requests
- letting the user set random times between requests so Instaloader's behavior is less bot-like and less likely to trigger Instagram's anti-bot heuristics
- letting the user set the number of requests before Instaloader takes a longer break (by which I mean those 20-minute+ breaks)
- letting the user set the length of those longer breaks

**Comment by Showmaster3000** [comment] 2023-03-20 17:51
This feature is already available. Search for `RateController` in the source code.
If you want to modify the default settings, you have to use the code version.
The standalone version will not support changes beside the default settings.

Duplicate of #1775, #1668, #1006

> Instaloader has a logic to keep track of its requests to Instagram and defers subsequent ones in order to not reach Instagram's rate limits. This rate controlling logic also gets applied when using Instaloader through CLI.
> _Originally posted by @Thammus in [#1006 (comment)](https://github.com/instaloader/instaloader/issues/1006#issuecomment-774186067)_

**Comment by EveryDirection** [comment] 2023-03-20 18:42
> This feature is already available. Search for `RateController` in the source code. If you want to modify the default settings, you have to use the code version. The standalone version will not support changes beside the default settings.
> 
> Duplicate of #1775, #1668, #1006
> 
> > Instaloader has a logic to keep track of its requests to Instagram and defers subsequent ones in order to not reach Instagram's rate limits. This rate controlling logic also gets applied when using Instaloader through CLI.
> > _Originally posted by @Thammus in [#1006 (comment)](https://github.com/instaloader/instaloader/issues/1006#issuecomment-774186067)_

The problem is that the suggested solution of modifying the source code is useless for users who are not Python programmers.

That this issue has been brought up so many times by different users over a period of years shows that there is clear demand among the userbase for rate-limiting options to be available in the CLI.

I will also quote some comments by other users supporting that this should be an option in the CLI rather than requiring users to modify the source code:

@skeith:
> I am still a beginner and would be clueless on how and where to start

@skeith:
> I was thinking, with this CLI option, one can force a slower delay to further avoid account being locked, such as one download per minute or something else even slower.

@MirayXS:
> If the feature request is accepted, would you be willing to submit a pull request?
> I don't think so, sorry. It's because i'm not the best at coding.

@thariq-nugrohotomo:
> I think it would be wise to expose the rate-limiting control as a command-shell argument, instead of hardcoding it. That way user doesn't need to wait for the next release to mitigate the issue when Instagram doing this again in the future.

@curya:
> I should be able to type something like --sleep=60 to sleep 60 seconds between posts.

@curya:
> No. I'm not a programmer.

@curya:
> Is there any reason why this hasn't been implemented before? It seems like a very useful thing to have...

**Comment by ekalin** [comment] 2023-03-20 19:07
Do you have any evidence that slowing downloads will prevent the temporary (or permanent) locks?

For what's worth (and I know this proves nothing), I modified the code to introduce a delay. The only difference was that downloads took longer, but it made no changes in periodically requiring an SMS/email challenge (and eventually getting it locked).

While it cannot be ruled out that the request rate generated by instaloader contributes to IG's suspicious use detection, it is certainly not the only factor.

That said, adding delays might help with avoiding 429 error. The current limit detection works to an extent, but eventually it triggers a 429 error.

So in my opinion (but I'm not a instaloader developer, I've just contributed some small changes) this might be an useful feature to add. I'm not really interested in writing it, but if someone would write a PR I guess it should be considered for merge.

**Comment by EveryDirection** [comment] 2023-03-20 19:59
> Do you have any evidence that slowing downloads will prevent the temporary (or permanent) locks?

Yes. If I only download from profiles with a few posts, then I don't get locked. For profiles with hundreds of posts, if I manually stagger downloading on profiles with lots of posts to only download a few posts at a time, which is extremely time-consuming and tedious and almost voids the point of Instaloader, then I don't get locked.

**Comment by Thammus** [comment] 2023-04-12 06:02
> Instaloader has a logic to keep track of its requests to Instagram and defers subsequent ones in order to not reach Instagram's rate limits. This rate controlling logic also gets applied when using Instaloader through CLI.

_Originally posted in https://github.com/instaloader/instaloader/issues/1006#issuecomment-774186067_

> When used through CLI, Instaloader applies its default rate control logic. Making adjustments to this logic is a non-standard use-case, for which a CLI is generally badly suited.

_Originally posted in https://github.com/instaloader/instaloader/issues/1006#issuecomment-778652069_

Duplicate of #1006.

**Closed by Thammus** 2023-04-12 06:02 UTC
Labels: duplicate
