### ISSUE TITLE
error while scraping

### ISSUE THREAD

**Issue by ihabpalamino** [instaloader/instaloader#1987] opened 2023-05-22 15:17 UTC
**Describe the bug**

**To Reproduce**
(e.g. Instaloader command line)
from datetime import datetime
from itertools import dropwhile, takewhile
import pandas as pd
import instaloader
from requests import post

from argparse import ArgumentParser
from glob import glob
from os.path import expanduser
from platform import system
from sqlite3 import OperationalError, connect

try:
    from instaloader import ConnectionException, Instaloader
except ModuleNotFoundError:
    raise SystemExit("Instaloader not found.\n  pip install [--user] instaloader")

def get_cookiefile():
    default_cookiefile = {
        "Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/*/cookies.sqlite",
        "Darwin": "~/Library/Application Support/Firefox/Profiles/*/cookies.sqlite",
    }.get(system(), "~/.mozilla/firefox/*/cookies.sqlite")
    cookiefiles = glob(expanduser(default_cookiefile))
    if not cookiefiles:
        raise SystemExit("No Firefox cookies.sqlite file found. Use -c COOKIEFILE.")
    return cookiefiles[0]

def import_session(cookiefile, sessionfile):
    print("Using cookies from {}.".format(cookiefile))
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
    try:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE baseDomain='instagram.com'"
        )
    except OperationalError:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE host LIKE '%instagram.com'"
        )
    instaloader = Instaloader(max_connection_attempts=1)
    instaloader.context._session.cookies.update(cookie_data)
    username = instaloader.test_login()
    if not username:
        raise SystemExit("Not logged in. Are you logged in successfully in Firefox?")
    print("Imported session cookie for {}.".format(username))
    instaloader.context.username = username
    instaloader.save_session_to_file(sessionfile)

if __name__ == "__main__":
    p = ArgumentParser()
    p.add_argument("-c", "--cookiefile")
    p.add_argument("-f", "--sessionfile")
    args = p.parse_args()
    try:
        import_session(args.cookiefile or get_cookiefile(), args.sessionfile)
    except (ConnectionException, OperationalError) as e:
        raise SystemExit("Cookie import failed: {}".format(e))

L = instaloader.Instaloader()

username=input("entrez le user que vous cherchez")

posts = instaloader.Profile.from_username(L.context, f"{username}").get_posts()
Since=input("yy,mm,dd")
until=input("yy,mm,dd")
SINCE = datetime.strptime(Since,"%Y/%m/%d")
UNTIL = datetime.strptime(until,"%Y/%m/%d")
a=[]
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    pu=[]
    post_likes = post.likes
    post_date = post.date
    post_owner = post.owner_username
    post_id=post.mediaid
    post_caption=post.caption
    pu=[post_owner,post_date,post_caption,post_likes]
    a.append(pu)
    # L.download_post(post, "instagram")
df = pd.DataFrame(a)
df.to_csv("instagram.csv", mode="w", sep="\t")
print(df.to_string())

hello guys this is my code when i try to scrape informationsfrom an other public account it gives me this error:
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 352, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 352, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 352, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\Instaloader.py", line 71, in <module>
    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\nodeiterator.py", line 141, in __next__
    query_response = self._query(self._data['page_info']['end_cursor'])
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\nodeiterator.py", line 103, in _query
    self._context.graphql_query(
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 429, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 385, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.

**Comment by Showmaster3000** [comment] 2023-05-22 23:06
duplicate of #1947.
Why did you open another issue with the same problem?

**Closed by Showmaster3000** 2023-05-22 23:06 UTC
Labels: duplicate
