### ISSUE TITLE
Only download "New posts"

### ISSUE THREAD

**Issue by Zachary24** [instaloader/instaloader#198] opened 2018-11-13 21:35 UTC
**Describe the solution you'd like**
Allow for only downloading posts from a profile which haven't been downloaded before. Instead of re-downloading all posts for a user.

**Comment by aandergr** [comment] 2018-11-14 07:05
The flag `--fast-update` should do exactly that. 

There is a section in our documentation where we describe the most interesting features of Instaloader:
https://instaloader.github.io/basic-usage.html

**Comment by Zachary24** [comment] 2018-11-14 07:20
I saw that, but i was dumb and didn't think to try it.. When I first read it I was assuming Instaloader downloaded old-to-new, which wouldn't have solved the problem.. I feel quite ignorant now. When looking for whether the post has already been downloaded, where does it look? Is there a log? Or am I required to keep every post? And thanks for building this, I almost died when I found Instaloader, It's MUCH better than saving each and every post!

**Comment by aandergr** [comment] 2018-11-14 13:44
> Just checked, it seems as if it simply checks if the file is already there..

Exactly.

> I don't plan to keep every post that gets downloaded, is there any plans (or something I'm unaware of) that solves the problem?

There is #72, the idea to store a persistent post database that can be used to keep track of what has already been downloaded to allow a more efficient post-deduplication.

**Comment by Zachary24** [comment] 2018-11-15 01:53
Do you plan to implement this? If not, from your perspective what do you think would be the easiest thing for me to do? My internet speed is pretty slow, so writing my own script that would automatically remove posts that I don't want would render useless, as it would take way too long to archive every account.. And keeping every post is too space consuming, but more of an organization issue..

**Comment by ealgase** [comment] 2018-11-26 13:56
@Zachary24 given that the issue is open, it's probably going to be implemented.  The question is, who will do it.

**Comment by aandergr** [comment] 2019-04-02 20:26
Closing this in favor of #72.

**Closed by aandergr** 2019-04-02 20:26 UTC
Labels: duplicate
