### ISSUE TITLE
Covers of Highligths are wrong

### ISSUE THREAD

**Issue by enes4949** [instaloader/instaloader#915] opened 2020-12-11 13:23 UTC
**Describe the bug**
When I try to download cover images of highlights it doesn't download the actual cover, it downloads the first image and crops it to a square.

**To Reproduce**
Running the command `instaloader -l myusername --highlights zeynepbastik`
(e.g. Instaloader command line)

**Expected behavior**
It supposed to download [this](https://instagram.fist13-1.fna.fbcdn.net/v/t51.2885-15/s150x150/126078592_786100495574254_755906512314403204_n.jpg?_nc_ht=instagram.fist13-1.fna.fbcdn.net&_nc_ohc=z1bGgaYqy5UAX95QZtS&tp=1&oh=50dd982fb8e1fa942cc790c86267f558&oe=5FFC69D9) but with a higher resolution. Instead it downloads the first image of highlights and crops it.

**Instaloader version**
4.5.5

**Comment by aandergr** [comment] 2020-12-14 07:32
Duplicate of #844.

**Closed by aandergr** 2020-12-14 07:32 UTC
Labels: duplicate
