### ISSUE TITLE
Don't finish instaloader after some problems

### ISSUE THREAD

**Issue by somera** [instaloader/instaloader#461] opened 2019-11-16 11:45 UTC
**Describe the bug**
With the last release, I get sometimes (I can't reproduce this) this

`[243] Traceback (most recent call last):
  File "instaloader\structures.py", line 157, in _field
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 446, in <module>
  File "__main__.py", line 442, in __main
  File "__main__.py", line 417, in main
  File "__main__.py", line 159, in _main
  File "instaloader\instaloader.py", line 49, in call
  File "instaloader\instaloader.py", line 742, in download_saved_posts
  File "instaloader\instaloader.py", line 466, in download_post
  File "instaloader\structures.py", line 227, in get_sidecar_nodes
  File "instaloader\structures.py", line 160, in _field
  File "instaloader\structures.py", line 143, in _full_metadata
  File "instaloader\structures.py", line 137, in _obtain_metadata
TypeError: 'NoneType' object is not subscriptable
[2908] Failed to execute script __main__`

error. And instaloader is stopping. When I start instaloader again, I get this error on other place.

**Instaloader version**
4.2.10

Or you can add an start parameter liek --dont_finish_during_error or something like this.

**Comment by aandergr** [comment] 2020-01-19 18:31
Duplicate of #451.

**Closed by aandergr** 2020-01-19 18:31 UTC
Labels: bug
