### ISSUE TITLE
Unable to retrieve posts with long captions as filename.

### ISSUE THREAD

**Issue by fosam** [instaloader/instaloader#1198] opened 2021-06-19 14:50 UTC
**Describe the bug**
Instagram posts with short captions `-CNVCsOyDNcy` work fine with the below command but posts with longer captions ` -CP3iI-SjDJy` return an error.

**To Reproduce**
Try this command **(long caption)** `instaloader --filename-pattern={date}_{caption} -- -CP3iI-SjDJy`

**Expected behavior**
Just like the output of this command **(short caption)** `instaloader --filename-pattern={date}_{caption} -- -CNVCsOyDNcy`

**Error messages and tracebacks**
```
-CP3iI-SjDJy\2021-06-08_17-32-56_Hello neighbor 😎@kevintrapp  We just arrived at our Homeground for the next weeks. It’s amazing to be here. Thanks @adidas 👏🏻👏🏻 #jetztgehtslangsamlos #derpulssteigt #dernachbarschaftgefällts #letsgodeutschland #istübrigenseineboatengbrille🤩.jpg Traceback (most recent call last):
  File "__main__.py", line 500, in <module>
  File "__main__.py", line 497, in __main
  File "__main__.py", line 466, in main
  File "__main__.py", line 167, in _main
  File "instaloader\instaloader.py", line 702, in download_post
  File "instaloader\instaloader.py", line 96, in call
  File "instaloader\instaloader.py", line 323, in download_pic
  File "instaloader\instaloadercontext.py", line 531, in get_and_write_raw
  File "instaloader\instaloadercontext.py", line 496, in write_raw
OSError: [Errno 22] Invalid argument: '-CP3iI-SjDJy\\2021-06-08_17-32-56_Hello neighbor 😎@kevintrapp  We just arrived at our Homeground for the next weeks. It’s amazing to be here. Thanks @adidas 👏🏻👏🏻 #jetztgehtslangsamlos #derpulssteigt #dernachbarschaftgefällts #letsgodeutschland #istübrigenseineboatengbrille🤩.jpg.temp'
[9720] Failed to execute script __main__
```

**Instaloader version**

Tried both **`4.8rc2`** and **`4.7.4`**
Windows 10

**Additional context**

As i don't prefer the captions to be downloaded as separate text files, i went with the option to have the captions in the filename.

Why does the command with a post with a long caption fail?

**Comment by Thammus** [comment] 2021-06-24 09:16
Duplicate of #262.

**Closed by Thammus** 2021-06-24 09:16 UTC
Labels: duplicate
