### ISSUE TITLE
Resume Prefix (Working Mechanism and if it really works?)

### ISSUE THREAD

**Issue by iamdeepak42** [instaloader/instaloader#953] opened 2021-01-02 20:57 UTC
I was downloading images from instagram in large volume and wanted to use resume prefix because of 429 errors occurring constantly.

The problem is even if I use **resume prefi**x, instaloader starts checking for the images from the very beginning. When I use this command, is it supposed to make a json file in order to track the changes?

This is the command I used
 `instaloader '#hashtag' --no-metadata-json  --no-compress-json --no-video-thumbnails  --no-videos --no-captions --resume-prefix resumer
`

**Comment by EpiPhobe** [comment] 2021-01-03 21:48
I was never able to get resume-prefix to work so I instead used `post_iterator.freeze()`:

```
import pickle
```
```
with open('config.dictionary', 'wb') as config_dictionary_file:
       pickle.dump(post_iterator.freeze(), config_dictionary_file)
```

And to resume,  `post_iterator.thaw()`:

```
with open('config.dictionary', 'rb') as config_dictionary_file:
       config_dictionary = pickle.load(config_dictionary_file)
       post_iterator.thaw(config_dictionary)
```

Documentation on Resumable Iterations can be found [here](https://instaloader.github.io/module/nodeiterator.html)

**Comment by Thammus** [comment] 2021-01-09 17:30
Duplicate of #874.

**Closed by Thammus** 2021-01-09 17:30 UTC
Labels: duplicate
