### ISSUE TITLE
update documentation with examples of what the command is

### ISSUE THREAD

**Issue by NIXOYE** [instaloader/instaloader#669] opened 2020-06-06 23:11 UTC
everytime I try to download a single post I go to the documentation and can't understand what the instructions mean. It would make it 10x simpler if you just gave an example for downloading a single post by writing out the command for a sample post. 

it currently says `The single post with the given shortcode. Must be preceeded by -- in the argument list to not be mistaken as an option flag.` which must be deciphered

**Comment by aandergr** [comment] 2020-06-07 10:19
Please stop spamming – duplicate of at least #398 and #565, all created by the same account. As I already said multiple times: Feel free to create a PR to discuss concrete ideas.

**Closed by aandergr** 2020-06-07 10:19 UTC
Labels: duplicate
