### ISSUE TITLE
Update a RSS/Atom feed for each folder (any maybe a simple HTML gallery)

### ISSUE THREAD

**Issue by somini** [instaloader/instaloader#1720] opened 2022-08-31 00:29 UTC
**Provide us a use case of the feature**
There could be an option that would keep a RSS/Atom feed updated on each downloaded folder, so that you could serve the root folder in a static HTML server, and subscribe to users, or hashtags.

A stretch goal would be a simple HTML gallery with all the images and a simple link to the instagram profile.

**Describe the solution you'd like**
Add a `--generate-atom` that creates an Atom file `feed.atom` on the downloaded folder, containing the data for all posts. Point images to their local names, not the remote Facebook servers. This could be relative links.

Note that the feed must contain all downloaded posts (or at least a configurable number, default to 10), even if they are not downloaded at this time (using `-F`).

**Describe alternatives you've considered**
Using the JSON information to hack something like this myself.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Additional context**

Here's more Atom information:
- https://en.wikipedia.org/wiki/Atom_(web_standard)
- https://datatracker.ietf.org/doc/html/rfc4287 (the standard)

The HTML gallery would probably require an extra dependency on `jinja2`, and shipping some extra files (the HTML templates) on the releases. RSS/Atom just needs a XML creator, that's on the standard library.

**Comment by aandergr** [comment] 2022-09-16 20:04
Duplicate of #938

**Closed by aandergr** 2022-09-16 20:04 UTC
Labels: duplicate
