### ISSUE TITLE
"KeyError: 'ProfilePage'" when account changed its name

### ISSUE THREAD

**Issue by ohjelmoija** [instaloader/instaloader#95] opened 2018-04-15 17:39 UTC
```
Traceback (most recent call last):
  File "Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.3.7', 'console_scripts', 'instaloader')()
  File "\lib\site-packages\instaloader.py", line 1800, in main
    filter_str=args.only_if)
  File "\lib\site-packages\instaloader.py", line 1618, in main
    filter_func=filter_func)
  File "\lib\site-packages\instaloader.py", line 1474, in download_profile
    profile_metadata, full_metadata = self.get_profile_metadata(name)
  File "\lib\site-packages\instaloader.py", line 1429, in get_profile_metadata
    return metadata['entry_data']['ProfilePage'][0]['graphql'], metadata
KeyError: 'ProfilePage'
```

**Comment by Purefreeman** [comment] 2018-04-16 08:15
I've been getting this same error for the past few days, thought it would've been fixed with recent update. It only seems to occur with the .bat file i have to download several Instagram live stories.

**Comment by aandergr** [comment] 2018-04-18 14:35
Unfortunately, I cannot reproduce this error, making it impossible to me for fix it. Could you provide more information about when it happens?

**Comment by octonator** [comment] 2018-04-25 13:54
I have similar problem now.

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/instaloader", line 11, in <module>
>     load_entry_point('instaloader==3.3.10', 'console_scripts', 'instaloader')()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader.py", line 1802, in main
>     filter_str=args.only_if)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader.py", line 1620, in main
>     filter_func=filter_func)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader.py", line 1480, in download_profile
>     name_updated, profile_id = self.check_profile_id(name, profile_metadata)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader.py", line 1392, in check_profile_id
>     profile_id = int(id_file.read())
> **ValueError: invalid literal for int() with base 10: b**''

**Comment by jtauert** [comment] 2018-04-25 14:58
Could be the same as #104 (and #108).
Scenario: you pass instaloader an old instagram user name that doesn't exist anymore. the account changed its name. in this case, instaloader fails at the moment.

**Comment by aandergr** [comment] 2018-05-02 08:34
Does this problem still persist? If so, does our [4.0 pre-release](https://github.com/instaloader/instaloader/releases/tag/v4.0rc1) alleviate the problem?
```
pip3 install --upgrade --pre instaloader~=4.0rc1
```

**Comment by jtauert** [comment] 2018-05-02 16:14
Seems to work now with the 4.0 final. Many thanks for the new release. Great work!
btw: is it possible to disable the generation of the meta-data files (eg 2018-04-11_19-51-12_UTC.json.xz)?
A fast sight through the doc didn't offer this info. Thanks! :)

**Comment by aandergr** [comment] 2018-05-02 16:17
Cool, thanks for testing! :)

> btw: is it possible to disable the generation of the meta-data files

Yes, with option [--no-metadata-json](https://instaloader.github.io/cli-options.html#cmdoption-no-metadata-json).

Happy Instaloading!
Alex

**Closed** 2018-05-02 16:17 UTC
Labels: bug
