### ISSUE TITLE
Error while downloading from location ID

### ISSUE THREAD

**Issue by Alcatraz0000** [instaloader/instaloader#1570] opened 2022-06-07 08:20 UTC
I'm trying to download many images from the museum location, so I'm using an instaloader.Instaloader().download_location(locationId, maxCount), but some pic cause me an error and the execution ended.
The function starts downloading from the same image in the same way, so I cant iterate over the other pic 

The specific location is '574437842646075', and the code to replicate this behavior is:
```
 L = instaloader.Instaloader()
 L.login(MYUSERNAME, MYPASSWORD)
 L.download_location(str(574437842646075), max_count=1000)

```
The Error was this: 

  
![image](https://user-images.githubusercontent.com/73600156/172331649-298ea51c-e0d4-42f2-b7ad-50d64d537961.png)

Instaloader version: 4.9

I've temporarily fixed the error by adding a try except in the specific method:

![image](https://user-images.githubusercontent.com/73600156/172331745-761647c5-2bd0-43d3-8def-958487aa800f.png)

**Comment by aandergr** [comment] 2022-06-16 13:16
Duplicate of #1471

**Closed by aandergr** 2022-06-16 13:16 UTC
Labels: duplicate
