### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by pvita** [instaloader/instaloader#925] opened 2020-12-16 12:57 UTC
**Describe the bug**
I'm collecting meta-data-jsons from 1 hashtag and after 500 results I have this error.
I tried to change the account, but after the same amount (more or less) of queries I have the same error.

400 Bad Request

**To Reproduce**
instaloader #hashtag --no-videos --no-pictures --comments  --no-captions --no-profile-pic --no-compress-json --login...

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).

**Error messages and tracebacks**
400 Bad Request

**Comment by aandergr** [comment] 2020-12-19 16:33
Duplicate of #828

**Closed by aandergr** 2020-12-19 16:33 UTC
Labels: duplicate
