### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 401. Also when iam trying to donwload a private account photos this isi hwat ima getting rivate but not followed

### ISSUE THREAD

**Issue by hacker07UK** [instaloader/instaloader#2000] opened 2023-06-06 15:48 UTC
Your question here...
JSON Query to graphql/query: HTTP error code 401. 

Also when I am trying to download private account photos this is what I am  getting "private but not followed"

if a private user is being followed then he can download directly from instagram right whats the point in coming here ?

**Comment by iansquenet** [comment] 2023-06-10 11:13
Same issue. How do I login with Firefox cookies?

**Comment by aandergr** [comment] 2023-06-26 05:50
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.

**Closed by aandergr** 2023-06-26 05:50 UTC
Labels: duplicate
