### ISSUE TITLE
"KeyError: 'edge_sidecar_to_children'" along with " "fail" status, message "feedback_required" when accessing" Errors

### ISSUE THREAD

**Issue by Martin-Codther** [instaloader/instaloader#2387] opened 2024-10-05 15:51 UTC
Hello,

I am on a Steam deck (meaning using SteamOS 3.5.19). I keep getting the two bugs pointed in the title, this is my  code, written and executed in a python file:

```
import shutil
import os
import datetime
import time
from instaloader import Instaloader, Profile 
from getpass import getpass

instapath = str("SPECIFIC EXTERNAL SSD PATH")
path = os.getcwd()
variavel = os.listdir(path)
# Instagram account's username and password
username = input("username:")
password = getpass("password:")

# Access user's profile
L = Instaloader(user_agent='BROWSER'S USER AGENT' , dirname_pattern='SPECIFIC EXTERNAL SSD PATH')
L.login(username, password)
profile = Profile.from_username(L.context, username)

# Get posts from 'saved' and iterate through them to obtain download its pictures
posts = profile.get_saved_posts()
for post in posts:
    L.download_video_thumbnails = False
    L.save_metadata = False
    L.download_post(post, "instagram_" + str(post.mediaid))

```
I was hoping for the python code I wrote to simply download the files to the directory.

This is the error message I get:

```
Traceback (most recent call last):
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/structures.py", line 355, in _field
    d = d[key]
        ~^^^^^
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deck/Documents/download_insta_media.py", line 27, in <module>
    L.download_post(post, "instagram_" + str(post.mediaid))
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/instaloader.py", line 725, in download_post
    if (self.download_pictures or self.download_videos) and post.mediacount > 0:
                                                            ^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/structures.py", line 442, in mediacount
    edges = self._field('edge_sidecar_to_children', 'edges')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/structures.py", line 358, in _field
    d = self._full_metadata
        ^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 450, in get_json
    raise QueryReturnedBadRequestException(self._response_error(resp))
instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request - "fail" status, message "feedback_required" when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAtcwMJJHMf%22%7D
```

The Instaloader version I'm using is 4.13.1.

Also, should I write the user agent as every single thing that appears under `navigator.userAgent` (meaning `Mozilla/number AppleWebKit/number etc.`) or just the intended browser (meaning only `Mozilla/number`)?

**Comment by aandergr** [comment] 2024-10-26 18:55
Duplicate of #2384

**Closed by aandergr** 2024-10-26 18:55 UTC
Labels: duplicate
