### ISSUE TITLE
"Connection broken: IncompleteRead" when downloading profilepic

### ISSUE THREAD

**Issue by ealgase** [instaloader/instaloader#242] opened 2019-01-26 04:00 UTC
**Describe the bug**
I'm getting lots of connection issues, every 20-30 pictures downloaded.

**To Reproduce**
(e.g. Instaloader command line)
Can't really give exact steps, but this is my command: `instaloader @elliot.algase --dirname-pattern Instagram/{profile} --login elliot.algase --fast-update`

**Expected behavior**
Profiles successfully download

**Error messages and tracebacks**
```
Retrieving posts from profile team_mystic_updater.
[  1/ 10] Instagram/team_mystic_updater/2018-09-25_22-43-05_UTC.jpg exists json 
Instagram/robynholland_/2019-01-12_23-59-51_UTC_profile_pic.jpg Traceback (most recent call last):
  File "/usr/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.5/http/client.py", line 508, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/http/client.py", line 573, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.5/http/client.py", line 543, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ealgase/.local/lib/python3.5/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/ealgase/.local/lib/python3.5/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 589, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(7029 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ealgase/.local/bin/instaloader", line 11, in <module>
    sys.exit(main())
  File "/home/ealgase/.local/lib/python3.5/site-packages/instaloader/__main__.py", line 412, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/ealgase/.local/lib/python3.5/site-packages/instaloader/__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/home/ealgase/.local/lib/python3.5/site-packages/instaloader/instaloader.py", line 911, in download_profiles
    self.download_profilepic(profile)
  File "/home/ealgase/.local/lib/python3.5/site-packages/instaloader/instaloader.py", line 317, in download_profilepic
    self.context.write_raw(profile_pic_bytes if profile_pic_bytes else profile_pic_response, filename)
  File "/home/ealgase/.local/lib/python3.5/site-packages/instaloader/instaloadercontext.py", line 455, in write_raw
    shutil.copyfileobj(resp.raw, file)
  File "/usr/lib/python3.5/shutil.py", line 73, in copyfileobj
    buf = fsrc.read(length)
  File "/home/ealgase/.local/lib/python3.5/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ealgase/.local/lib/python3.5/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(7029 bytes read)', IncompleteRead(7029 bytes read))
```

**Instaloader version**
4.2.1

**Additional context**
If you'd like my profile login, I can send it to the developers.

**Comment by Showmaster3000** [comment] 2019-01-30 22:22
I just had a similar error some minutes ago during checking an account for updates. In my case the error occured right at the profile pic (which in about half of the cases gets downloaded as new again even if there is no new one, but thats another thing).


```
Loaded session from c:\users\myname\appdata\local\temp/.instaloader-myname/session-mynick.
Logged in as mynick.
downloadnick/2018-06-10_09-36-15_UTC_profile_pic.jpg [14820] Failed to execute script __main__
Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 583, in _readinto_chunked
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 630, in _safe_readinto
http.client.IncompleteRead: IncompleteRead(7552 bytes read, 16384 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py", line 302, in _error_catcher
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py", line 384, in read
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 449, in read
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 483, in readinto
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 594, in _readinto_chunked
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Instaloader\__main__.py", line 444, in <module>
  File "C:\Instaloader\__main__.py", line 440, in __main
  File "C:\Instaloader\__main__.py", line 415, in main
  File "C:\Instaloader\__main__.py", line 189, in _main
  File "C:\Instaloader\instaloader\instaloader.py", line 911, in download_profiles
  File "C:\Instaloader\instaloader\instaloader.py", line 317, in download_profilepic
  File "C:\Instaloader\instaloader\instaloadercontext.py", line 455, in write_raw
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\shutil.py", line 79, in copyfileobj
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py", line 401, in read
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 99, in __exit__
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py", line 320, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by irvinm** [comment] 2019-01-31 21:50
I'm seeing similar issues and can't seem to download more than 5-20 at a time without getting a ConnectionResetError.  Everything was working really well until very recently.

```
Traceback (most recent call last):
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\urllib3\response.py", line 360, in _error_catcher
    yield
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\irvin\AppData\Local\Programs\Python\Python36\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.2.1', 'console_scripts', 'instaloader')()
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\instaloader\__main__.py", line 412, in main
    storyitem_filter_str=args.storyitem_filter)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\instaloader\__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\instaloader\instaloader.py", line 942, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\instaloader\instaloader.py", line 411, in download_post
    downloaded = self.download_pic(filename=filename, url=post.url, mtime=post.date_local)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\instaloader\instaloader.py", line 195, in download_pic
    self.context.get_and_write_raw(url, filename)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\instaloader\instaloadercontext.py", line 497, in get_and_write_raw
    self.write_raw(self.get_raw(url), filename)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\instaloader\instaloadercontext.py", line 455, in write_raw
    shutil.copyfileobj(resp.raw, file)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\shutil.py", line 73, in copyfileobj
    buf = fsrc.read(length)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\urllib3\response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\irvin\appdata\local\programs\python\python36\lib\site-packages\urllib3\response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by hgkmaxymus** [comment] 2019-02-03 02:54
Yeah, I think Instagram is trying to shut us down. I mean, it was working fine until 2 days ago. Now, I can't download anything (logged in or not - ok, I can download 1-10 pictures and then I get the error). I hope it is just some kind of overload on their servers and everything will be fine in a few days...

My error messages (same as the ones above):

```
Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 360, in _error_catcher
    yield
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 448, in read
    n = self.readinto(b)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 583, in _readinto_chunked
    n = self._safe_readinto(temp_mvb)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 623, in _safe_readinto
    n = self.fp.readinto(mvb)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\Scripts\instaloader-script.py", line 10, in <module>
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 412, in main
    storyitem_filter_str=args.storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 911, in download_profiles
    self.download_profilepic(profile)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 317, in download_profilepic
    self.context.write_raw(profile_pic_bytes if profile_pic_bytes else profile_pic_response, filename)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloadercontext.py", line 455, in write_raw
    shutil.copyfileobj(resp.raw, file)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\shutil.py", line 73, in copyfileobj
    buf = fsrc.read(length)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by hgkmaxymus** [comment] 2019-02-06 17:31
Just to update here, it seems they fixed the ConnectionResetError(10054). I was able to download my lists without issues today.

**Comment by aandergr** [comment] 2019-02-10 17:32
Duplicate of #235.

**Closed by aandergr** 2019-02-10 17:32 UTC
