### ISSUE TITLE
Can't save photos with captions as file names.

### ISSUE THREAD

**Issue by SnowDragon997** [instaloader/instaloader#1487] opened 2022-04-12 01:49 UTC
**Describe the bug**
A clear and concise description of what the bug is. Can't save photos with captions as file names.

**To Reproduce**
(e.g. Instaloader command line)
instaloader --sanitize-paths --no-profile-pic --no-captions --no-metadata-json --filename-pattern={caption} apple

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious). should work

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

"error: unrecognized arguments: -encodedCommand -inputFormat xml -outputFormat text"

**Instaloader version**
`instaloader --version` output. newest

**Additional context**

**Comment by hadzb** [comment] 2022-04-20 01:29
i have experienced the same issue, i believe the issue is that the caption has a character that cannot be part of a filename. 
I think a fix would be to remove/replace those characters so the file name would be accepted by windows

A filename cannot contain `\/:*?"<>|` on windows

**Comment by aandergr** [comment] 2022-04-21 18:06
Duplicate of #262

**Closed by aandergr** 2022-04-21 18:06 UTC
Labels: duplicate
