### ISSUE TITLE
Instaloader doesn't work without login anymore JSON Query to profile/feed/: 404 Not Found

### ISSUE THREAD

**Issue by YotonKing** [instaloader/instaloader#1115] opened 2021-04-26 20:16 UTC
**The bug**
It gives me JSON Query to profile/feed/: 404 Not Found and it redirects me after 12 downloads to login page. Changing IP doesn't work like one other thread suggested. I tried many IP addresses and the same happens with every IP.

**To Reproduce**

.\instaloader --no-video-thumbnails --no-captions --no-metadata-json --no-profile-pic --igtv profile cansu.demirhas
JSON Query to profile/feed/: 404 Not Found [retrying; skip with ^C]
JSON Query to profile/feed/: 404 Not Found [retrying; skip with ^C]

HTTP redirect from https://www.instagram.com/web/search/topsearch/ to https://www.instagram.com/accounts/login/
profile: Redirected to login page. Use --login.
Stored ID 5837432653 for profile cansu.demirhas.
Warning: Use --login to download higher-quality versions of pictures.
Retrieving IGTV videos for profile cansu.demirhas.
Retrieving posts from profile cansu.demirhas.
[ 1/48] cansu.demirhas\2018-03-17_20-15-29_UTC.jpg
[ 2/48] cansu.demirhas\2018-03-06_07-46-18_UTC.jpg
[ 3/48] cansu.demirhas\2018-02-27_07-58-12_UTC.jpg
[ 4/48] cansu.demirhas\2018-02-20_17-40-34_UTC.jpg
[ 5/48] cansu.demirhas\2018-02-16_16-37-44_UTC.jpg
[ 6/48] cansu.demirhas\2018-02-14_12-52-55_UTC.jpg
[ 7/48] cansu.demirhas\2018-02-12_17-50-41_UTC.jpg
[ 8/48] cansu.demirhas\2018-02-06_14-59-54_UTC.jpg
[ 9/48] cansu.demirhas\2018-02-05_11-26-49_UTC.jpg
[10/48] cansu.demirhas\2018-02-02_09-27-07_UTC.jpg
[11/48] cansu.demirhas\2018-01-29_16-20-45_UTC.jpg
[12/48] cansu.demirhas\2018-01-26_11-41-09_UTC.jpg

HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
cansu.demirhas: Redirected to login page. Use --login.

Errors or warnings occurred:
profile: Redirected to login page. Use --login.
Warning: Use --login to download higher-quality versions of pictures.
cansu.demirhas: Redirected to login page. Use --login.

**Expected behavior**
Instaloader downloads all posts in the profile and doesn't redirect me to login,

**Error messages and tracebacks**
Error messages are above

**Instaloader version**
instaloader --version says 4.6.2 even though I upgraded it and pip says it is already satisfied aka I have the newest version

**Additional context**
This exact command used to work without problems

**Comment by Showmaster3000** [comment] 2021-04-27 20:04
I think it's duplicate of #1067 - is it?

**Comment by YotonKing** [comment] 2021-04-27 20:19
> 
> 
> I think it's duplicate of #1067 - is it?

No it's not because the suggested solution is to change IP but changing it doesn't work hence I made this. I tried multiple IP addresses and the same happens every time.

**Comment by maxbeauclair** [comment] 2021-04-28 00:50
This is definitely a new problem. I'm in the same boat as YotonKing; changing ip used to fix this issue, but now it does not. Instagram appears to have updated something recently.

**Comment by Thammus** [comment] 2021-04-29 20:30
The message `JSON Query to profile/feed/: 404 Not Found` does not indicate any bug. You are trying to download the target `profile` which does not exist. The redirect that occurs for the second specified profile has already been reported in #1013.

**Closed by Thammus** 2021-04-29 20:30 UTC
Labels: duplicate

**Comment by YotonKing** [comment] 2021-04-29 21:00
It does indicate a bug because this exact same command used to work. That profile does exist and it does download 12 posts from it. This happens with any profile. What second profile? I only specified one. #1013 seems to have a different outcome. It doesn't download the first 12 posts before redirecting. Also why I wanted to open this is because the solution of #1067 doesn't work anymore.

**Comment by darrenandrew** [comment] 2024-06-05 04:53
Hello Users. I am trying to get instaloader to work for me but i am having some issues. Whenever i try to use the hashtag code it comes back with a 404 error any help will be greatly apricated 

C:\Users\Darren Andrew>instaloader "#Sharks"
JSON Query to explore/tags/sharks/: 404 Not Found [retrying; skip with ^C]
JSON Query to explore/tags/sharks/: 404 Not Found [retrying; skip with ^C]
Get hashtag #Sharks: JSON Query to explore/tags/sharks/: 404 Not Found

Errors or warnings occurred:
Get hashtag #Sharks: JSON Query to explore/tags/sharks/: 404 Not Found
