### ISSUE TITLE
Not downloading private account posts

### ISSUE THREAD

**Issue by um-4ir** [instaloader/instaloader#2331] opened 2024-08-04 17:01 UTC
**Describe the bug**
Back few days we can download posts of private accounts by login but now it's always skips posts and start downloading directly stories [ I'm not using --no-posts switch]. So it should download them too as it does before.
I've try with --stories and --highlights with both it skips posts

**To Reproduce**
instaloader --no-metadata-json --no-video-thumbnails --no-compress-json --filename-pattern "{profile}-{date}s" --stories 
 targetusername -l myusername -p mypass
(e.g. Instaloader command line)
It tries Retrieving posts from profile user
But failed I guess.

**Expected behavior**
It should retrieve posts of profile it does if I don't use login then it download public profiles.
I think here problem with login.

**Error messages and tracebacks**
There is no error it just skip them.

**Instaloader version**
4.12.1 from pip

**Additional context**

**Comment by ekalin** [comment] 2024-08-04 18:39
Duplicate of #2319

**Closed** 2024-08-09 22:16 UTC
Labels: duplicate
