### ISSUE TITLE
How can solve this error anyone can help!!!

### ISSUE THREAD

**Issue by rosaleendsouza23** [instaloader/instaloader#1151] opened 2021-05-26 21:40 UTC
![Error](https://user-images.githubusercontent.com/61114190/119734738-03ebf080-be99-11eb-9df6-0863703a1f54.jpg)

**Comment by aandergr** [comment] 2021-05-27 17:12
Duplicate of #1090.

**Closed by aandergr** 2021-05-27 17:12 UTC
Labels: duplicate
