### ISSUE TITLE
Is there a way to stop after n downloads ?

### ISSUE THREAD

**Issue by ishandutta2007** [instaloader/instaloader#314] opened 2019-05-28 07:01 UTC
Say there are thousands of posts, say I only care about latest 100. One way is to pipe the output rows and keep track explicitly by the user but is there an implicit way provided by the library itself ?

**Comment by aandergr** [comment] 2019-06-02 19:27
Duplicate of #141.

**Closed by aandergr** 2019-06-02 19:27 UTC
