### ISSUE TITLE
Android sanitize path

### ISSUE THREAD

**Issue by anuraag488** [instaloader/instaloader#1268] opened 2021-09-02 03:01 UTC
**Describe the bug**
I have been trying instaloader on android using termux but using commands like --tagged gives error as path like : tagged not supported

**To Reproduce**
instaloader --tagged profile

**Instaloader version**
4.8.1

**Comment by Deleora** [comment] 2021-09-04 14:35
Try with [Pydroid3](https://play.google.com/store/apps/details?id=ru.iiec.pydroid3). It has it's own terminal but I haven't tried parameters containing ':'. Maybe you can try and let us know :)

**Comment by anuraag488** [comment] 2021-09-05 02:44
> Try with [Pydroid3](https://play.google.com/store/apps/details?id=ru.iiec.pydroid3). It has it's own terminal but I haven't tried parameters containing ':'. Maybe you can try and let us know :)

I'm interested in using it with Tasker and Termux has it.

**Comment by aandergr** [comment] 2021-09-18 13:33
Duplicate of #1116

**Closed by aandergr** 2021-09-18 13:33 UTC
Labels: bug
