### ISSUE TITLE
TypeError: unorderable types: int() < str()

### ISSUE THREAD

**Issue by sillibird** [instaloader/instaloader#115] opened 2018-05-08 00:58 UTC
On 4.0.0 or the 4.0.0 issue 112 fix version, after it starts downloading a profile it will error out with

`
Traceback (most recent call last):

  File "c:\users\username\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "c:\users\username\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "C:\Users\username\AppData\Local\Programs\Python\Python35\Scripts\instaloader.exe\__main__.py", line 9, in <module>

  File "c:\users\username\appdata\local\programs\python\python35\lib\site-packages\instaloader\__main__.py", line 324, in main
    storyitem_filter_str=args.storyitem_filter)

  File "c:\users\username\appdata\local\programs\python\python35\lib\site-packages\instaloader\__main__.py", line 149, in _main
    stories, stories_only, post_filter, storyitem_filter)

  File "c:\users\username\appdata\local\programs\python\python35\lib\site-packages\instaloader\instaloader.py", line 791, in download_profiles
    downloaded = self.download_post(post, target=profile.username)

  File "c:\users\username\appdata\local\programs\python\python35\lib\site-packages\instaloader\instaloader.py", line 369, in download_post
    self.update_comments(filename=filename, post=post)

  File "c:\users\username\appdata\local\programs\python\python35\lib\site-packages\instaloader\instaloader.py", line 192, in update_comments
    comments_list = sorted(sorted(list(comments), key=lambda t: t['id']),
TypeError: unorderable types: int() < str()
`

**Comment by aandergr** [comment] 2018-05-08 15:08
Duplicate of #114

**Closed by aandergr** 2018-05-08 15:08 UTC
