### ISSUE TITLE
get_hashtag_posts() throws KeyError: 'graphql'

### ISSUE THREAD

**Issue by emremrah** [instaloader/instaloader#1125] opened 2021-05-04 15:17 UTC
**Describe the bug**
When logged in, running `instaloader.get_hashtag_posts('<some hashtag>')` throws an error.

**To Reproduce**
These are the steps to reproduce the issue for me:
```py
import instaloader
from os import getenv
import dotenv

dotenv.load_dotenv('./instagram/.env')

loader = instaloader.Instaloader()

loader.login(getenv('INSTAGRAM_USERNAME'), getenv('INSTAGRAM_PASSWORD'))

posts = loader.get_hashtag_posts('covid19')
```

**Expected behavior**
I expect to run the error-giver line to run without any errors and contionue to get informatin about posts.

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
```
Traceback (most recent call last):
  File "instafoo.py", line 12, in <module>
    posts = loader.get_hashtag_posts('covid19')
  File "/home/.../.venv/lib/python3.8/site-packages/instaloader/instaloader.py", line 996, in get_hashtag_posts
    return Hashtag.from_name(self.context, hashtag).get_posts()
  File "/home/.../.venv/lib/python3.8/site-packages/instaloader/structures.py", line 1302, in from_name
    hashtag._obtain_metadata()
  File "/home/.../.venv/lib/python3.8/site-packages/instaloader/structures.py", line 1316, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "/home/.../.venv/lib/python3.8/site-packages/instaloader/structures.py", line 1311, in _query
    return self._context.get_json("explore/tags/{0}/".format(self.name),
KeyError: 'graphql'
```

**Instaloader version**
Instaloader: 4.6
Python: 3.8 in a virtualenv
Ubuntu 20.04

**Comment by emremrah** [comment] 2021-05-04 15:22
I have checked the release notes above 4.6 but didn't see a note that resolves this issue.

**Comment by aandergr** [comment] 2021-05-08 14:36
Duplicate of #1080.

**Closed by aandergr** 2021-05-08 14:36 UTC
Labels: duplicate
