### ISSUE TITLE
HTTP redirect to Instagram Login Page Issue

### ISSUE THREAD

**Issue by senaykt** [instaloader/instaloader#1667] opened 2022-07-28 08:21 UTC
**Describe the bug**
When I want to get user details without login, it gives me redirection error. Yesterday, this version is OK and I can get all profiles' data. Today, it is not working. 

**To Reproduce**
instaloader profile user_profile

**Expected behavior**
Crawling Instagram profile details 

**Error messages and tracebacks**
"HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=profile to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=profile to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
profile: Redirected to login page. Use --login."

**Instaloader version**
4.9.2

![image](https://user-images.githubusercontent.com/42169819/181457294-f9d3c84e-1c84-46a0-a54e-3d6cf280dc1a.png)
![image](https://user-images.githubusercontent.com/42169819/181457599-c0c0e13d-4945-4c62-87f2-584d1bc4425f.png)

**Comment by jakku13** [comment] 2022-07-28 09:16
have the same issue here as well...

**Comment by sina-rostami** [comment] 2022-07-28 09:56
The same issue here

**Comment by jakku13** [comment] 2022-07-28 12:40
Has anyone found a solution to this? Even with login information, I'm not able to make more than 20 - 40 requests. Is there any work around? Instaloader is almost un-usable right now

**Comment by senaykt** [comment] 2022-07-28 12:43
No, I cannot find any solution for this. It is still not working. 

> Has anyone found a solution to this? Even with login information, I'm not able to make more than 20 - 40 requests. Is there any work around? Instaloader is almost un-usable right now

No, I do not have a solution for this, it is still not working as you said.

**Comment by Showmaster3000** [comment] 2022-07-28 12:47
Your command line is `instaloader profile user_profile` - so instaloader is trying to download the profile `profile` and the profile `user_profile`. Maybe this is your problem.
Anyway the "error" message is clear: you have to login to proceed cause instagram limits the amount of anon access.

Duplicate of #1666 and #1617.

**Comment by jakku13** [comment] 2022-07-28 12:49
That's what I mentioned. Even with Login info, it isn't allowing me to make more than 40 requests.

**Comment by senaykt** [comment] 2022-07-28 12:54
> instaloader profile user_profile

I used same code snipped "instaloader profile user_profile(my_test_profile)" yesterday. It has no error, everthing is fine. Today, suddenly, we cannot get any response from instaloader.

In addition to this, we can proceed get public profiles without login. (I was able to do this yesterday.) Something is changed today.

**Comment by senaykt** [comment] 2022-07-28 12:56
> Your command line is `instaloader profile user_profile` - so instaloader is trying to download the profile `profile` and the profile `user_profile`. Maybe this is your problem. Anyway the "error" message is clear: you have to login to proceed cause instagram limits the amount of anon access.
> 
> Duplicate of #1666 and #1617.

I used same code snipped "instaloader profile user_profile(my_test_profile)" yesterday. It has no error, everthing is fine. Today, suddenly, we cannot get any response from instaloader.

In addition to this, we can proceed get public profiles without login. (I was able to do this yesterday.) Something is changed today.

**Comment by KillaRanks** [comment] 2022-07-28 13:47
These people will tell you there is nothing wrong. I called this 2 week ago and a guy told me he downloaded 2tb in anon and my post was bs.

**Comment by senaykt** [comment] 2022-07-28 13:49
> These people will tell you there is nothing wrong. I called this 2 week ago and a guy told me he downloaded 2tb in anon and my post was bs.

Yes, I saw that. But I need urgent help with this. It does not work now. Maybe Instagram side change something. I send only one request and it does not work.

**Comment by KillaRanks** [comment] 2022-07-28 14:18
> 

All i know is that there is no update, haven't tried the windows port of instaloader and that it kind of fixed itself after 2 days when it happened to me. Till now that i repeated , but i am glad more people can see it happening. And also i don't use my IG profiles cause i already lost 1 by downloading my own stuff , got sent a sms that never arrived and after 24hrs you get nuked.

**Comment by mauronr** [comment] 2022-07-28 14:35
See my comment on the other thread for a potential explanation on what's going on.
I'm suffering from similar issues, but I believe Instagram is at fault, not Instaloader.

https://github.com/instaloader/instaloader/issues/1617#issuecomment-1198201613

**Comment by ttp976633** [comment] 2022-07-29 15:41
Any update on this? Before this issue came up, I was able to download 190+ accounts at one time, without logging in, using basic parameters from the cmd line (fast update, latest stamps, no videos, etc) and never received issues, especially as I would use a VPN connection to switch addresses in between batch requests. It would limit it to the last 12 public posts (which is normal IG behavior) At this point, it does not work for even 5-10 accounts at one time.

**Comment by KillaRanks** [comment] 2022-07-29 15:48
> Any update on this? Before this issue came up, I was able to download 190+ accounts at one time, without logging in, using basic parameters from the cmd line (fast update, latest stamps, no videos, etc) and never received issues, especially as I would use a VPN connection to switch addresses in between batch requests. It would limit it to the last 12 public posts (which is normal IG behavior) At this point, it does not work for even 5-10 accounts at one time.

Nothing so far afaik. But it is interesting your vpn mention as i thought on using one to see if it works. However how do you use it like that? any tip?

**Comment by ttp976633** [comment] 2022-07-29 15:57
I have experimented with ExpressVPN. I would set my location to a particular city (say, New York), run my script with 190 accounts, it would take 10-15 minutes to process, scrape all the accounts, return new images, and then it would complete. After it completed, I would switch locations in the VPN (for example, Toronto), and then run the next batch of scripts. I was able to do this and download 1000+ accounts without getting any errors, too many connections, etc. I switched the VPN location after every batch. This worked for a while until yesterday. Now the VPN does not help at all. Instagram clearly changed something on the back end.

**Comment by faiblesse2** [comment] 2022-08-02 02:13
> I have experimented with ExpressVPN. I would set my location to a particular city (say, New York), run my script with 190 accounts, it would take 10-15 minutes to process, scrape all the accounts, return new images, and then it would complete. After it completed, I would switch locations in the VPN (for example, Toronto), and then run the next batch of scripts. I was able to do this and download 1000+ accounts without getting any errors, too many connections, etc. I switched the VPN location after every batch. This worked for a while until yesterday. Now the VPN does not help at all. Instagram clearly changed something on the back end.

190 accounts grabbing only the first 12 posts per account per IP? I've been using proton mail vpn & its worked fine until now where suddenly all my accs are getting phone number blocked, and some have been disabled + blacklisted phone number

**Comment by faiblesse2** [comment] 2022-08-02 02:14
> I have experimented with ExpressVPN. I would set my location to a particular city (say, New York), run my script with 190 accounts, it would take 10-15 minutes to process, scrape all the accounts, return new images, and then it would complete. After it completed, I would switch locations in the VPN (for example, Toronto), and then run the next batch of scripts. I was able to do this and download 1000+ accounts without getting any errors, too many connections, etc. I switched the VPN location after every batch. This worked for a while until yesterday. Now the VPN does not help at all. Instagram clearly changed something on the back end.

190 accounts grabbing only the first 12 posts per account per IP? I've been using another vpn & its worked fine until now where suddenly all my accs are getting phone number blocked, and some have been disabled + blacklisted phone number

**Comment by ttp976633** [comment] 2022-08-02 02:28
I scrape the accounts without logging in, so I am only downloading photos. Instagram returns a max of 12 posts (with as many pics as are included in those 12 posts) per user when you are not logged in with an account. I only have one instagram account and I don't want it to get banned, so I scrape anonymously.

**Comment by ttp976633** [comment] 2022-08-02 18:31
fwiw, I just tested the following script on a single account:

`Instaloader --fast-update --latest-stamps --no-videos --no-captions --no-metadata --no-profile-pic --request-timeout 15 nike`

and this was the error I received

```
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=nike to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=nike to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
nike: Redirected to login page. Use --login.

Errors or warnings occurred:
nike: Redirected to login page. Use --login.

```

**Comment by thanhtuht** [comment] 2022-08-07 04:23
any news update to fix or bypass login?

**Comment by senaykt** [comment] 2022-08-07 08:28
> any news update to fix or bypass login?

Still same, nightmare for me.

**Comment by mauronr** [comment] 2022-08-08 12:53
I believe this a duplicate of https://github.com/instaloader/instaloader/issues/1617

**Comment by ttp976633** [comment] 2022-08-11 20:39
surely this issue is impacting everyone who uses instaloader, right? as I noted above, I have tried to run the script through a VPN from various regions and I get the persistent errors noted above. this has been open for 2+ weeks, so I am wondering if this is a global problem or if its isolated to the few people in this thread who have explained the issue?

**Comment by JinSolChoi** [comment] 2022-08-16 04:12
still same in version 4.9.3

**Comment by senaykt** [comment] 2022-08-18 02:33
Still same for me.

**Comment by JinSolChoi** [comment] 2022-08-24 02:49
After login, then it work.
Try it!

```
L = instaloader.Instaloader()
id = 'your id'
pw = 'your pw'
L.login(id, pw)
```

**Comment by alex-ash** [comment] 2022-08-24 08:21
I'm not sure about 2FA, login-password only isn't enough.

> After login, then it work. Try it!
> 
> ```
> L = instaloader.Instaloader()
> id = 'your id'
> pw = 'your pw'
> L.login(id, pw)
> ```

**Comment by vishalitg** [comment] 2022-08-30 17:07
curl --location --request GET 'http://i.instagram.com/api/v1/users/web_profile_info/?username=the.badgamer' \
--header 'User-Agent: Instagram 146.0.0.27.125 (iPhone12,1; iOS 13_3; en_US; en-US;scale=2.00; 1656x3584; 190542906'
After Debugging get the above code.
This is working on my local machine, but when I try to run it on my dedicated server it shows redirects to the login page. 
I don't know why.

**Comment by erolrecep** [comment] 2022-09-02 03:31
I did couple things and it works now;
 - I am using a virtual environment for instaloader and I deleted this virtualenv and recreated it.
 - I checked the ~/.cache and ~/.config folders to delete any cache instaloader file-folder in it.
 - I reinstalled my browser (I use firefox) and deleted all cache file-folder of it. (virtual browser may confuse with cache on browser)
 - Finally, I checked my instaloader scripts (downloading saved and liked posts) and changed it with the new updates.
As a result, it's working now. I don't know which one or ones solved the issue but it's working now.

Let me know how things are doing on your end.

**Comment by aandergr** [comment] 2022-09-16 20:16
No need to track this twice; as already mentioned in previous comments, this is a duplicate of #1617.

**Closed by aandergr** 2022-09-16 20:16 UTC
Labels: duplicate

**Comment by masterprog303** [comment] 2023-03-06 21:22
any help??

**Comment by tijas133** [comment] 2023-07-25 19:19
This does not work at all... waste of time :(

**Comment by tijas133** [comment] 2023-07-25 19:22
https://ibb.co/y8Y5B9x

**Comment by jorgeachar** [comment] 2023-12-13 23:06
After 3 days of working hard. I come to this common problem... for god! Why didn't I read this before? I think the problem continues guys

**Comment by geronimo-iia** [comment] 2024-01-14 16:58
Same issus here, it worked few weeks ago without need to provide authentication. 

For me, it's working with and without authentication on my laptop, but need authentication on github ci.
I hope that's not a change from instagram api behavior. If I found something i will reply here.

**Comment by nasleceo** [comment] 2024-06-14 18:34
any one fine some thing , 2024 and no solution yet

**Comment by FoxMcWeezer** [comment] 2024-10-23 06:13
Might be an IP thing. Instagram make it difficult to do things on "fishy" IPs such as VPNs
