### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by zaidunz** [instaloader/instaloader#1918] opened 2023-03-18 07:01 UTC
Session file does not exist yet - Logging in.
Enter Instagram password for _zaidunz: 
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXESmRJZuc2KGAqHErx_lJIT-1E8mLkd9PdsMPLsD6kSam2iX8PEDgYtBLGJhcYKQLl9aQ/AfxD-bh5b_GZBvp6BB8XAjt7XbJtorUuqowj-5pp3pz27ruPMwPZjSSCirYTxps97EzyJ_0OVJCMXg/ffc_MME49VKALdZEC4uqr26tB6WRepxUdemFTNyXPPtDWWCGUNi03KGi7YQvIpE2K21n/ - follow the instructions, then retry. I've done what I was told, but still the error

**Comment by Showmaster3000** [comment] 2023-03-19 20:05
no template. duplicate of #1787.

**Closed by Showmaster3000** 2023-03-19 20:05 UTC
Labels: duplicate, no template
