### ISSUE TITLE
Cannot download from profiles with videos(TypeError: 'NoneType' object is not subscriptable)

### ISSUE THREAD

**Issue by BobMacpherson** [instaloader/instaloader#467] opened 2019-11-25 22:47 UTC
**Describe the bug**
Instaloader crashes when profile has a new video on it to download

**To Reproduce**
**Original command used:**
instaloader profile(s) --fast-update --no-captions --no-metadata-json --no-compress-json --login=user --password=password --sessionfile=/path/to/session-user --dirname-pattern=/path/to/{profile} --filename-pattern={mediaid}
**Additional commands tried after error that also give the same error:**
instaloader profile(s) --fast-update --login=password --password=password
instaloader profile(s) --fast-update

**Expected behavior**
Instaloader updates/downloads the profile with a new video on in.

**Error messages and tracebacks**

> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/instaloader/structures.py", line 157, in _field
>     d = d[key]
> KeyError: 'video_url'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/instaloader", line 11, in <module>
>     load_entry_point('instaloader==4.2.10', 'console_scripts', 'instaloader')()
>   File "/usr/lib/python3.8/site-packages/instaloader/__main__.py", line 401, in main
>     _main(loader,
>   File "/usr/lib/python3.8/site-packages/instaloader/__main__.py", line 187, in _main
>     instaloader.download_profiles(profiles,
>   File "/usr/lib/python3.8/site-packages/instaloader/instaloader.py", line 1039, in download_profiles
>     downloaded = self.download_post(post, target=profile_name)
>   File "/usr/lib/python3.8/site-packages/instaloader/instaloader.py", line 491, in download_post
>     downloaded &= self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local)
>   File "/usr/lib/python3.8/site-packages/instaloader/structures.py", line 290, in video_url
>     return self._field('video_url')
>   File "/usr/lib/python3.8/site-packages/instaloader/structures.py", line 160, in _field
>     d = self._full_metadata
>   File "/usr/lib/python3.8/site-packages/instaloader/structures.py", line 143, in _full_metadata
>     self._obtain_metadata()
>   File "/usr/lib/python3.8/site-packages/instaloader/structures.py", line 137, in _obtain_metadata
>     if self.shortcode != self._full_metadata_dict['shortcode']:
>TypeError: 'NoneType' object is not subscriptable

**Instaloader version**
4.2.10

**Additional context**
Only crashes on profiles that have new videos,can update/download from profiles that have new images only. Was tested using single profile at once as well as multiple and using an +args file. Every time it got to a profile with a video, it crashes

**Comment by werid** [comment] 2019-11-26 09:30
Seeing this post and noticing an error in my log that kept happening, I wonder if it is the same...

I have python 3.6 and instaloader 4.2.9 and experience a similar problem, it doesn't crash instaloader, just errors, but it is related to a strange video.

[  1/1581] download_pic(): HTTPSConnectionPool(host='static.cdninstagram.com', port=443): Max retries exceeded with url: /rsrc.php/null.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x802a52978>: Failed to establish a new connection: [Errno 8] hostname nor servname provided, or not known',)) [retrying; skip with ^C]

download_pic(): HTTPSConnectionPool(host='static.cdninstagram.com', port=443): Max retries exceeded with url: /rsrc.php/null.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x8029dee48>: Failed to establish a new connection: [Errno 8] hostname nor servname provided, or not known',)) [retrying; skip with ^C]  

Download <Post B5Ub46HA6HnyFZFoEl8gw51oXJmu6Jhr7b8G9Y0> of [PROFILE]: download_pic(): HTTPSConnectionPool(host='static.cdninstagram.com', port=443): Max retries exceeded with url: /rsrc.php/null.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x802a32f60>: Failed to establish a new connection: [Errno 8] hostname nor servname provided, or not known',))

When I check this (private) profile in firefox (on linux), and open the first post, i get the following message:

No video with supported format and MIME type found.

When I check this video in the app, it says "Watch IGTV video"

**Comment by sxiii** [comment] 2019-12-07 05:32
I'm having similar problem; not yet sure if it's related to the videos or not:

```
TypeError: 'NoneType' object is not subscriptable
```

Here is more full lout output:
```
[374/???] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instaloader/structures.py", line 157, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.7/dist-packages/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.7/dist-packages/instaloader/instaloader.py", line 1010, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter)
  File "/usr/local/lib/python3.7/dist-packages/instaloader/instaloader.py", line 884, in download_tagged
    downloaded = self.download_post(post, target if target else Path(profile.username) / Path(':tagged'))
  File "/usr/local/lib/python3.7/dist-packages/instaloader/instaloader.py", line 466, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/usr/local/lib/python3.7/dist-packages/instaloader/structures.py", line 227, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/usr/local/lib/python3.7/dist-packages/instaloader/structures.py", line 160, in _field
    d = self._full_metadata
  File "/usr/local/lib/python3.7/dist-packages/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.7/dist-packages/instaloader/structures.py", line 137, in _obtain_metadata
    if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable
```

What I've tried to do is ``` instaloader --tagged --login MY_USER_NAME cmeocollective ```.

Any clues?

**Comment by Kikiss18** [comment] 2019-12-12 09:36
Hello,

I have a same problem.  
structures.py", line 157, in _field d = d[key] 
KeyError: 'edge_sidecar_to_children_' 

Instaloader seems to crash when scraping a post made first of a picture, then a video on the second windows. Sounds like the trouble is based on this new structure of the post.  

Thank you,

**Comment by aandergr** [comment] 2020-01-19 18:34
Duplicate of #449.

**Closed by aandergr** 2020-01-19 18:34 UTC
Labels: bug
