### ISSUE TITLE
"No such file or directory" when downloading highlights

### ISSUE THREAD

**Issue by rabe398** [instaloader/instaloader#286] opened 2019-05-01 16:46 UTC
Hi,
I'm currently scraping a list of 5700 users, the script generated a folder for each user and after that it started downloading. At some point the script crashed, here's the error:
![image](https://user-images.githubusercontent.com/37730040/57031192-b7993c80-6c4f-11e9-8ced-4c744a6ec1a9.png)

Now I tried restarting the script and now its stuck at login, I think instagram is limiting requests from my ip or account.
The script downloaded 20 gigs so far.

**To Reproduce**
instaloader.exe +args.txt

**Instaloader version**
`instaloader --version` output.
4.24

**Comment by rabe398** [comment] 2019-05-01 16:46
Any tips for scraping such large list of users?

**Comment by rabe398** [comment] 2019-05-02 12:07
Update: The script worked but started crashing
![image](https://user-images.githubusercontent.com/37730040/57074234-f977c080-6ceb-11e9-9d6f-9b286e01852d.png)

**Comment by e5150** [comment] 2019-05-02 18:32
@rabe398 you might want to crop the screenshot, since your password is visible in the window title.

**Comment by rabe398** [comment] 2019-05-02 20:18
Whoops!

**Comment by rabe398** [comment] 2019-05-03 20:39
@aandergr Any ideas?

**Comment by aandergr** [comment] 2019-05-09 07:03
Thanks for reporting! I think the problem is that it cannot create a directory named "....", the title of the highlight it attempts to download.

A few remarks about how you reported this bug:
- don't post screenshots of a console. Instead, copy the text into the issue. This makes it more readable, more mobile-internet-friendly and searchable. 
- `instaloader +args.txt` as steps to reproduce is useless, since we don't know what's the content of args.txt. Usually we don't need exact profile names but only those wo fail when it seems profile-specific. But the flags you used, and the kind of targets you attempt to download are almost always of interest. 
- the title doesn't say anything. 
- the third comment seems to refer to a completely different problem than the first one.  Ideally, an issue thread refers to exactly one issue. 
- we get an email for each new issue and comment, we regularly see the open issues page and in our minds we always have an overview of what's happening. We're very unlikely to forget issues (unless they are marked as closed), hence there's no need to ping us.

(Don't take this too personally, it also means that we may have to optimize our issue template. However, we always want to address problems as soon as I can and as precisely as I can, and a good reporting helps a lot, especially at times when there's a lot open)

**Comment by aandergr** [comment] 2019-05-09 07:19
Aaand it's a Duplicate of #263.

**Closed by aandergr** 2019-05-09 07:19 UTC
Labels: Windows, bug
