### ISSUE TITLE
Download posts in specific period - Get posts for other time period

### ISSUE THREAD

**Issue by Annika10** [instaloader/instaloader#681] opened 2020-06-09 15:13 UTC
I want to download posts and comments from the 01.04.2018 to 31.12.2018 but it downloads posts from a different time period. 
I use the format of the instaloader website.
I only changed 

`posts = instaloader.Hashtag.from_name(L.context, myhashtag).get_posts()`

to

`posts = L.get_hashtag_posts(hashtag) `

Here is my code:

```
from datetime import datetime
from itertools import dropwhile, takewhile
import instaloader
import usernameToFile
L = instaloader.Instaloader(download_comments=True)
hashtags = [
    'kuenstlicheintelligenz',
]
SINCE = datetime(2018, 12, 31)
UNTIL = datetime(2018, 4, 1)
for hashtag in hashtags:
    posts = L.get_hashtag_posts(hashtag)
    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        print(post.date)
        print(post.owner_username)
        L.download_post(post, '#' + hashtag)
```

It first downloads posts and comments from 06.08.2018-07.09.2018 and then from 06.04.2018-18.07.2019. Not the posts I requested for. 

Another point is, that some posts aren't scraped. For example when I use: 
```
SINCE = datetime(2019, 9, 1)
UNTIL = datetime(2019, 7, 1)
```
for my hashtag 'kuenstlicheintelligenz' the program doesn't give any feedback or scrapes something. But on instagram there are posts with this hashtag in the specific time period.
I don't know how to fix it, that the time period is correct.

**Comment by aandergr** [comment] 2020-06-09 19:39
Similar to #666. The code example with dropwhile and takewhile makes the assumption that the post iterator returns posts in exact chronological order. This seems no longer true for hashtag posts. It might be helpful to analyze the degree and kind of deviation from chronological order. If e.g. only up to k older posts are inserted into an otherwise chronological order (as #666 suggests with k=3), we could break the loop after encountering the (k+1):th too-old post rather than the first one.

**Comment by Annika10** [comment] 2020-06-10 07:56
The wrongly collected posts from 2019 are about 500 items. The first collected posts in the period  06.08.2018-07.09.2018 are 8 posts.

**Comment by aandergr** [comment] 2020-06-12 18:30
Closing this as duplicate of #666 – no need to keep two issues about the same topic.

**Closed by aandergr** 2020-06-12 18:30 UTC
Labels: duplicate
