### ISSUE TITLE
Traceback (most recent call last) error when trying to download anyting

### ISSUE THREAD

**Issue by BAD-WOLF-AWP** [instaloader/instaloader#1785] opened 2022-10-26 20:52 UTC
**Describe the bug**
when trying to download anything i always get this error:

`Loaded session from C:\Users\user\AppData\Local\Instaloader\username.
Enter Instagram password for username:
Traceback (most recent call last):
  File "C:\Users\user \AppData\Local\Programs\Python\Python39\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9.5', 'console_scripts', 'instaloader')())
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\instaloader\__main__.py", line 471, in main
    _main(loader,
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\instaloader\__main__.py", line 121, in _main
    instaloader.interactive_login(username)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\instaloader\instaloader.py", line 1572, in interactive_login
    self.login(username, password)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\instaloader\instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\instaloader\instaloadercontext.py", line 265, in login
    session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=N
`

**To Reproduce**
instaloader --login username --no-captions --no-metadata-json --no-compress-json --fast-update --no-posts --no-profile-pic --stories --filename-pattern={date_utc}_UTC_{profile} --dirname-pattern="C:\private\private1\Instagram\stories\{profile}" anyprofile

**Expected behavior**
should download the stories

**Instaloader version**
4.9.5

**Additional context**
Sorry, if the problem is on my side, it has always worked like this for me i dont know python and i've never written a github post.

**Comment by Showmaster3000** [comment] 2022-10-26 21:55
Duplicate of #1758.

**Closed** 2022-11-05 16:09 UTC
Labels: duplicate
