### ISSUE TITLE
`Post.likes` property always return -1

### ISSUE THREAD

**Issue by Hyuto** [instaloader/instaloader#1606] opened 2022-06-28 17:08 UTC
`Post.likes` property always return -1

**To Reproduce**

```python
import instaloader

if __name__ == "__main__":
    L = instaloader.Instaloader()
    L.load_session_from_file("<SESSION>")

    profile = instaloader.Profile.from_username(L.context, "instagram")
    posts = profile.get_posts()
    for post in posts:
        print(str(post.date))
        print(post.caption)
        print(post.likes)
        break
```

result

```
2022-06-27 19:01:16
This Pride, kindness and fierceness go hand in hand. 🌈🙌

Check out our story for more things that inspired us to #ShareWithPride this month.

Reel by @virgin_x and @hausofdarkwah
Music by @beyonce
-1
```

expected

```
2022-06-27 19:01:16
This Pride, kindness and fierceness go hand in hand. 🌈🙌

Check out our story for more things that inspired us to #ShareWithPride this month.

Reel by @virgin_x and @hausofdarkwah
Music by @beyonce
261618
```

**Instaloader version**
4.9.1

**Comment by Showmaster3000** [comment] 2022-06-29 00:26
Did you see #968? There is a similar question to yours.

**Comment by aandergr** [comment] 2022-07-14 17:25
Duplicate of #1314

**Closed by aandergr** 2022-07-14 17:25 UTC
Labels: duplicate
