### ISSUE TITLE
Post.get_comments() creates an infinite loop, fetching same comment

### ISSUE THREAD

**Issue by JavierPiedra** [instaloader/instaloader#1017] opened 2021-02-08 09:22 UTC
**Describe the bug**
I'm using Post.get_comments() function in a for loop and it had been working well but I found an exception with one particular comment in a post.
The for loop keeps fetching the same comment indefinitely. I can't see what is particular to this comment that is causing this behaviour, the comment that is been fetched continously is an answer of a comment, it has hashtags and that's all.

**To Reproduce**
```
>>> import instaloader
>>> username = 'xxxxx'
>>> L = instaloader.Instaloader()
>>> try:
...     L.load_session_from_file(username)
... except instaloader.BadCredentialsException:
...     L.login(username, 'mypassword')
...     L.save_session_to_file()
... except instaloader.TwoFactorAuthRequiredException:
...     L.two_factor_login()
...     L.save_session_to_file()
... except Exception as e:
...     print(e)
>>> the_post_with_issues = instaloader.Post.from_shortcode(L.context, 'CKznw1jDJle')
>>> for comment in the_post_with_issues.get_comments():
...     print(comment.text)
```

**Expected behavior**
Fetch all comments, without duplicates

**Error messages and tracebacks**
No error message, just keeo fetching the same comment

**Instaloader version**
4.6.1

**Comment by JavierPiedra** [comment] 2021-02-09 16:32
Update: I found out that the bug might be on instagram side, as some posts are showing that the comments query still have a next page although that's not true. Even on the web interface when you reach the limit, you can keep fetching "new comments" and it brings the same last one.

**Comment by Thammus** [comment] 2021-02-13 19:28
Thanks for providing a reproducible example and for examining the behavior of the comments at Instagram's web interface.
This phenomenon has also been reported in #910.

**Comment by Thammus** [comment] 2021-03-20 15:16
This infinite loop bug seems to be fixed by Instagram.

**Closed by Thammus** 2021-03-20 15:16 UTC
Labels: bug
