### ISSUE TITLE
400,401 Behavior since one month

### ISSUE THREAD

**Issue by raka404suam** [instaloader/instaloader#2446] opened 2024-11-25 17:25 UTC
Describe the bug
When attempting to scrape followees using profile.get_followees(), the script throws a QueryReturnedBadRequestException with a 400 Bad Request response and a message indicating "checkpoint_required".

To Reproduce

Use the following command to attempt scraping followees of a profile:

profile = instaloader.Profile.from_username(L.context, 'username')
followees = list(profile.get_followees())

Run the script.

Observe the error traceback.

Expected behavior
The script should retrieve the followees of the specified profile without encountering a 400 Bad Request error.

Error messages and tracebacks

Instaloader version
instaloader --version output: (Please replace with your version)

Additional context

The issue seems to be related to recent changes in Instagram's API behavior.

The "checkpoint_required" message suggests that additional authentication or verification may now be required to proceed.

The session used in the script was freshly created and valid.

Adding delays between requests did not resolve the issue, Using cookie do the same result for me.

My script has been working for many month/years one time a week randomly (Not spamming API, not using 2FA), so I think about external changes (instagram added a check point? But we don't have checkpoint url.)

Thank you for your help

**Comment by Showmaster3000** [comment] 2024-11-26 00:37
Duplicate of #2445

**Closed by Showmaster3000** 2024-11-26 00:37 UTC
Labels: bug
