### ISSUE TITLE
Instalaoder hashtag image scraper not working 

### ISSUE THREAD

**Issue by AshutoshKhanna** [instaloader/instaloader#2306] opened 2024-07-11 07:59 UTC
**Describe the bug**
while using the command to download pictures of a particular hashtag is not working it is trying to acess the url : https://www.instagram.com/explore/tags/goa/?__a=1&__d=dis  whearas the correct url it should access is  :https://www.instagram.com/explore/tags/goa/ due to which the issue is arising 

**To Reproduce**
instaloader "#goa" --no-videos --no-metadata-json --no-compress-json --no-captions --dirname-pattern "hashtag-goa" 

**Expected behavior**
The command should downlaod the instagram pictures for the hashtags 

**Error messages and tracebacks**
JSON Query to explore/tags/goa/: 404 Not Found when accessing https://www.instagram.com/explore/tags/goa/?__a=1&__d=dis [retrying; skip with ^C]
JSON Query to explore/tags/goa/: 404 Not Found when accessing https://www.instagram.com/explore/tags/goa/?__a=1&__d=dis [retrying; skip with ^C]
Get hashtag #goa: JSON Query to explore/tags/goa/: 404 Not Found when accessing https://www.instagram.com/explore/tags/goa/?__a=1&__d=dis

Errors or warnings occurred:
Get hashtag #goa: JSON Query to explore/tags/goa/: 404 Not Found when accessing https://www.instagram.com/explore/tags/goa/?__a=1&__d=dis

**Instaloader version**
instalaoder version:4.12

**Additional context**

**Comment by geoffrey-vl** [comment] 2024-08-12 20:26
Seeing same issue here.
The specific header query attributes were added 2 years ago (v4.9.5) specifically to fix fetching issues, see https://github.com/instaloader/instaloader/pull/1749
I guess the API got changed in the mean time...

**Comment by goodbyenary** [comment] 2024-09-03 10:29
[](https://apify.com/apify/instagram-hashtag-scraper )
i found this and it seems to be working. Am i overlooking something? Kinda surprised.

**Comment by Mishalabdullah** [comment] 2024-09-04 01:10
Is this bug being actively or passively worked on ?

**Comment by Mishalabdullah** [comment] 2024-09-04 03:15
One Hashtag Post JSON Output.
```
[
  {
    "inputUrl": "https://www.instagram.com/explore/tags/banaras",
    "id": "3449384894479455220",
    "type": "Sidecar",
    "shortCode": "C_erUkxC9P0",
    "caption": "Jai Bala Ji Maharaj 🙏😌\n@varanasi_chatore \n#varanasichatore #zingarimadadhiche #wanderer #pose #explore #varanasi #tridevmandir #templeofvaranasi #kashi #banaras #temple #salasarbalaji #varanasivloger",
    "hashtags": [
      "varanasichatore",
      "zingarimadadhiche",
      "wanderer",
      "pose",
      "explore",
      "varanasi",
      "tridevmandir",
      "templeofvaranasi",
      "kashi",
      "banaras",
      "temple",
      "salasarbalaji",
      "varanasivloger"
    ],
    "mentions": [
      "varanasi_chatore"
    ],
    "url": "https://www.instagram.com/p/C_erUkxC9P0/",
    "commentsCount": 0,
    "firstComment": "",
    "latestComments": [],
    "dimensionsHeight": 1350,
    "dimensionsWidth": 1080,
    "displayUrl": "https://instagram.flas1-1.fna.fbcdn.net/v/t51.29350-15/457821869_1041519797377262_7434449427762011803_n.webp?stp=dst-jpg_e35_p1080x1080&_nc_ht=instagram.flas1-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=hY78P2D7_AsQ7kNvgE_Z8OS&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYDEqKNU-gsyl8vWr2q7_4d3hSIqjsuKBOuwQVjShVpcrA&oe=66DD9710&_nc_sid=10d13b",
    "images": [
      "https://instagram.flas1-1.fna.fbcdn.net/v/t51.29350-15/457821869_1041519797377262_7434449427762011803_n.webp?stp=dst-jpg_e35_p1080x1080&_nc_ht=instagram.flas1-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=hY78P2D7_AsQ7kNvgE_Z8OS&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYDEqKNU-gsyl8vWr2q7_4d3hSIqjsuKBOuwQVjShVpcrA&oe=66DD9710&_nc_sid=10d13b",
      "https://instagram.flas1-2.fna.fbcdn.net/v/t51.29350-15/457829736_1717015999033764_2119435010498788733_n.webp?stp=dst-jpg_e35_p1080x1080&_nc_ht=instagram.flas1-2.fna.fbcdn.net&_nc_cat=100&_nc_ohc=-qiDWZ0psdsQ7kNvgFC5N2N&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYD3OAV9Yqia9-2i0BoZN8BWTAgD41Hf0HmzOshAKyxzUA&oe=66DD8B44&_nc_sid=10d13b"
    ],
    "alt": "Photo shared by Zin Garima Dadhiche on September 03, 2024 tagging @varanasi_chatore. May be an image of 1 person, smiling, shawl, turban, temple and text.",
    "likesCount": 2,
    "timestamp": "2024-09-04T02:59:04.000Z",
    "childPosts": [
      {
        "id": "3449384868130614357",
        "type": "Image",
        "shortCode": "C_erUMOiGxV",
        "caption": "",
        "hashtags": [],
        "mentions": [],
        "url": "https://www.instagram.com/p/C_erUMOiGxV/",
        "commentsCount": 0,
        "firstComment": "",
        "latestComments": [],
        "dimensionsHeight": 1350,
        "dimensionsWidth": 1080,
        "displayUrl": "https://instagram.flas1-1.fna.fbcdn.net/v/t51.29350-15/457821869_1041519797377262_7434449427762011803_n.webp?stp=dst-jpg_e35_p1080x1080&_nc_ht=instagram.flas1-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=hY78P2D7_AsQ7kNvgE_Z8OS&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYDEqKNU-gsyl8vWr2q7_4d3hSIqjsuKBOuwQVjShVpcrA&oe=66DD9710&_nc_sid=10d13b",
        "images": [],
        "alt": "Photo shared by Zin Garima Dadhiche on September 03, 2024 tagging @varanasi_chatore. May be an image of 1 person, smiling, shawl, turban, temple and text.",
        "likesCount": null,
        "timestamp": null,
        "childPosts": [],
        "ownerId": null,
        "taggedUsers": [
          {
            "full_name": "Zin Garima Dadhiche",
            "id": "8065190221",
            "is_verified": false,
            "profile_pic_url": "https://instagram.flas1-2.fna.fbcdn.net/v/t51.2885-19/454693660_1252038122625629_2162077389295432327_n.jpg?stp=dst-jpg_s150x150&_nc_ht=instagram.flas1-2.fna.fbcdn.net&_nc_cat=105&_nc_ohc=fZ6wjimwUCMQ7kNvgH2j_kT&_nc_gid=7185e60e8d0e460790b1d45919dc0b98&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYDnjujrB1TNrF9PhJSWGguLO9u8DJfZ-Mz_au0ABNnmvg&oe=66DD87F9&_nc_sid=10d13b",
            "username": "varanasi_chatore"
          }
        ]
      },
      {
        "id": "3449384868130670134",
        "type": "Image",
        "shortCode": "C_erUMOiUY2",
        "caption": "",
        "hashtags": [],
        "mentions": [],
        "url": "https://www.instagram.com/p/C_erUMOiUY2/",
        "commentsCount": 0,
        "firstComment": "",
        "latestComments": [],
        "dimensionsHeight": 1350,
        "dimensionsWidth": 1080,
        "displayUrl": "https://instagram.flas1-2.fna.fbcdn.net/v/t51.29350-15/457829736_1717015999033764_2119435010498788733_n.webp?stp=dst-jpg_e35_p1080x1080&_nc_ht=instagram.flas1-2.fna.fbcdn.net&_nc_cat=100&_nc_ohc=-qiDWZ0psdsQ7kNvgFC5N2N&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYD3OAV9Yqia9-2i0BoZN8BWTAgD41Hf0HmzOshAKyxzUA&oe=66DD8B44&_nc_sid=10d13b",
        "images": [],
        "alt": "Photo by Zin Garima Dadhiche on September 03, 2024. May be an image of gingerbread cookie, dollhouse, the Taj Mahal and text.",
        "likesCount": null,
        "timestamp": null,
        "childPosts": [],
        "ownerId": null
      }
    ],
    "locationName": "Tridev Temple Varanasi",
    "locationId": "1888758861427747",
    "ownerFullName": "Zin Garima Dadhiche",
    "ownerUsername": "varanasi_chatore",
    "ownerId": "8065190221",
    "isSponsored": false,
    "taggedUsers": [
      {
        "full_name": "Zin Garima Dadhiche",
        "id": "8065190221",
        "is_verified": false,
        "profile_pic_url": "https://instagram.flas1-2.fna.fbcdn.net/v/t51.2885-19/454693660_1252038122625629_2162077389295432327_n.jpg?stp=dst-jpg_s150x150&_nc_ht=instagram.flas1-2.fna.fbcdn.net&_nc_cat=105&_nc_ohc=fZ6wjimwUCMQ7kNvgH2j_kT&_nc_gid=7185e60e8d0e460790b1d45919dc0b98&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYDnjujrB1TNrF9PhJSWGguLO9u8DJfZ-Mz_au0ABNnmvg&oe=66DD87F9&_nc_sid=10d13b",
        "username": "varanasi_chatore"
      }
    ],
    "fullName": "owner didnt open"
  }
]
```

**Comment by aandergr** [comment] 2024-09-04 05:49
Duplicate of #2144

**Closed by aandergr** 2024-09-04 05:49 UTC
Labels: duplicate
