### ISSUE TITLE
KeyError: 'edge_sidecar_to_children' & KeyError: 'graphql'

### ISSUE THREAD

**Issue by anirudh-ramesh** [instaloader/instaloader#498] opened 2020-01-24 08:42 UTC
**Describe the bug**
When Instaloader is used to download saved photos/videos of a user, an attempt to download some posts throws KeyError at `edge_sidecar_to_children` and `graphql`.

**To Reproduce**
Steps to reproduce the behaviour:
When executing `instaloader :saved --login <username>`, certain posts (observed with all posts having multiple photos and not with posts having a single photo) cannot be downloaded, and the above error is thrown.

**Expected behavior**
A clear and concise description of what you expected to happen (if not obvious).

**Error messages and tracebacks**

> 
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/structures.py", line 156, in _field
>     d = d[key]
> KeyError: 'edge_sidecar_to_children'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/bin/instaloader", line 10, in <module>
>     sys.exit(main())
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 410, in main
>     storyitem_filter_str=args.storyitem_filter)
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 153, in _main
>     post_filter=post_filter)
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 49, in call
>     return func(instaloader, *args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 731, in download_saved_posts
>     downloaded = self.download_post(post, target=':saved')
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 462, in download_post
>     for sidecar_node in post.get_sidecar_nodes():
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/structures.py", line 226, in get_sidecar_nodes
>     for edge in self._field('edge_sidecar_to_children', 'edges'):
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/structures.py", line 159, in _field
>     d = self._full_metadata
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/structures.py", line 142, in _full_metadata
>     self._obtain_metadata()
>   File "/home/ubuntu/.local/lib/python3.7/site-packages/instaloader/structures.py", line 134, in _obtain_metadata
>     self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
> KeyError: 'graphql'

**Instaloader version**
4.2.8

**Comment by anirudh-ramesh** [comment] 2020-01-24 08:43
This is different from #451 although similar.

**Comment by aandergr** [comment] 2020-01-25 09:05
> **Instaloader version**
> 4.2.8

Looks like #380, which has been fixed with Instaloader 4.2.10. It should work after upgrading Instaloader. Please reopen this issue if the error still appears.

**Closed by aandergr** 2020-01-25 09:05 UTC
Labels: bug

**Comment by timlinden** [comment] 2020-02-07 13:54
File "instaloader\structures.py", line 157, in _field
KeyError: 'edge_sidecar_to_children'

I got this error using latest code pulled from master yesterday. I wrapped the if post.stypename == 'GraphSidecar' section with a try / except (instaloader.py line 496 to allow it to continue on after the error.

`            if post.typename == 'GraphSidecar':
                edge_number = 1
                try:
                    for sidecar_node in post.get_sidecar_nodes():
                        # Download picture or video thumbnail
                        if not sidecar_node.is_video or self.download_video_thumbnails is True:
                            downloaded &= self.download_pic(filename=filename, url=sidecar_node.display_url,
                                                            mtime=post.date_local, filename_suffix=str(edge_number))
                        # Additionally download video if available and desired
                        if sidecar_node.is_video and self.download_videos is True:
                            downloaded &= self.download_pic(filename=filename, url=sidecar_node.video_url,
                                                            mtime=post.date_local, filename_suffix=str(edge_number))
                        edge_number += 1
                except:
                    downloaded = True
            elif post.typename == 'GraphImage':`

**Comment by polds** [comment] 2020-03-12 06:46
I still see this issue with 4.2.10 and the alpha 4.3a1/4.3a2.

**Comment by billjoe** [comment] 2020-03-20 19:40
I have the same issue with v4.3 on Windows, installed today:

File "instaloader\structures.py", line 157, in _field
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 459, in <module>
  File "__main__.py", line 455, in __main
  File "__main__.py", line 412, in main
  File "__main__.py", line 159, in _main
  File "instaloader\instaloader.py", line 49, in call
  File "instaloader\instaloader.py", line 773, in download_saved_posts
  File "instaloader\instaloader.py", line 492, in download_post
  File "instaloader\structures.py", line 227, in get_sidecar_nodes
  File "instaloader\structures.py", line 160, in _field
  File "instaloader\structures.py", line 143, in _full_metadata
  File "instaloader\structures.py", line 137, in _obtain_metadata
TypeError: 'NoneType' object is not subscriptable
[15356] Failed to execute script __main__

**Comment by aandergr** [comment] 2020-03-20 19:53
@billjoe you get a different error message than the one reported here, hence it's not the same issue, although they may look very similar on the first glance. The error you experience has been reported in #451, but unfortunately there is no fix yet. Feel free to comment your observations there, especially how to reproduce the error.
