### ISSUE TITLE
Endless loop when receiving comments

### ISSUE THREAD

**Issue by djigit0s** [instaloader/instaloader#910] opened 2020-12-07 21:30 UTC
**Endless loop when receiving comments for some links**
For example, the link is https://www.instagram.com/p/CGh4slpJ0IL/

**To Reproduce**
```
count = 0
for item in post_info.get_comments():
    count +=1
    print('count')
    print(item)


```

**Instaloader version**
`instaloader --version` output.
4.5.4

**Additional context**
The cycle goes on forever and the count increases, although the post only has 340 comments
![Снимок](https://user-images.githubusercontent.com/3939174/101407794-7a496600-38ec-11eb-8710-bf9b1f7682c5.JPG)

**Comment by aandergr** [comment] 2020-12-12 17:45
Thanks for reporting this. Indeed, I can reproduce that some comments are looped endlessly for this post.

**Comment by Thammus** [comment] 2021-03-20 15:16
This endless loop bug seems to be fixed by Instagram.

**Closed** 2021-03-20 15:16 UTC
Labels: bug
