### ISSUE TITLE
Instaloader.exceptions.ConnectionException: JSON Query to explore/tags/whatever: HTTP error code 401.

### ISSUE THREAD

**Issue by bellu** [instaloader/instaloader#1988] opened 2023-05-24 04:10 UTC
**Describe the bug**
`instaloader.Hashtag.from_name(self.L.context, 'whatever').get_posts_resumable()`
Returns every time: Instaloader.exceptions.ConnectionException: JSON Query to explore/tags/whatever: HTTP error code 401.

**To Reproduce**
`instaloader.Hashtag.from_name(self.L.context, 'whatever').get_posts_resumable()`
try to use the method above

**Expected behavior**
A list of posts

**Error messages and tracebacks**
 Instaloader.exceptions.ConnectionException: JSON Query to explore/tags/whatever: HTTP error code 401.

**Instaloader version**
4.9.6

**Comment by nebula0225** [comment] 2023-05-24 04:47
your ip is banned from Instagram

**Comment by bellu** [comment] 2023-05-24 05:57
I tried with several VPNs, multihop and a docker image; and even from a remote VPS server.
I've every time this result, how can i solve it?

**Comment by nebula0225** [comment] 2023-05-24 06:03
@bellu Do not use free or low quailty ip or vpn
especially don't use datacenter's ip

**Comment by giovsta** [comment] 2023-05-25 13:50
I just want to clarify that this error even occurs without a banned IP. I tried with two accounts and none is banned, nor is my access to the website locked from the same connection, yet the error occurs constantly after a long session of scraping posts.

**Comment by Sauravlama** [comment] 2023-05-29 10:55
What is your code about. Let me know, i can help!

**Comment by zero0n3** [comment] 2023-05-29 17:05
Hi everyone. Watch out because it seems that Instagram has figured out how to block downloads made by instaloader regardless of IP or account.
Having banned my home IP, I tried to connect via a mobile hotspot, with a different IP and a different operator. Same result: 401 error.

And I don't use session files or logins to download. And I know for sure that the photo is public and does not need to login to be seen.

So watch out

**Comment by nebula0225** [comment] 2023-05-30 00:47
@zero0n3 Use another account that not same sms, Email

**Comment by zero0n3** [comment] 2023-05-30 05:42
> 

I'm not using account now. I got 401 without an account and if i use an account, instagram ban it immediately (already tried)

**Comment by nebula0225** [comment] 2023-05-30 05:56
@zero0n3 Instagram is very strict for public requests
almost public requests have a hard limit & quality per Ip
so instaloader recommend using private requests 
It is not instaloader's fault

if you want to use public requests you have to use a lot of very high quality ip that can change

**Comment by zero0n3** [comment] 2023-05-30 05:58
> @zero0n3 Instagram is very strict for public requests almost public requests have a hard limit & quality per Ip so instaloader recommend using private requests It is not instaloader's fault
> 
> if you want to use public requests you have to use a lot of very high quality ip that can change

ok i understood. But if i use a session cookie with an account, instagram ban it. is there a way to download photos, even in low quality, without getting banned?

**Comment by nebula0225** [comment] 2023-05-30 06:05
@zero0n3
Your wrong with first point -> already your ip is banned from instagram but you login with session
you have to login with another ip

**Comment by nebula0225** [comment] 2023-05-30 06:08
very celar way is using clear another account with another good ip

**Comment by zero0n3** [comment] 2023-05-30 06:47
> very celar way is using clear another account with another good ip

The onyl way to change IP is to use VPN (i'm under FTTC so the IP is the same also if i reboot router)

**Comment by nebula0225** [comment] 2023-05-30 06:54
@zero0n3
Buy good quality ip

**Comment by zero0n3** [comment] 2023-05-30 07:05
> @zero0n3 Buy good quality ip

Can you suggest me one is good for you? thanks

**Comment by nebula0225** [comment] 2023-05-30 07:20
@zero0n3 

rotate ip :
[dashboard.smartproxy.com/register?referral_code=39a10f1c4064acce1d4bc577c74374c843ae66b2](url)

fixed ip :
[https://proxy-seller.com/?partner=Z1YYIDH27IX1OJ](url)
coupon : TQETWM_592186

they have a refer that return to you and me

**Comment by ihabpalamino** [comment] 2023-06-02 09:22
it always happen to me and after 24h it works normally again i think it has a relation with how much time you scraped

**Comment by ihabpalamino** [comment] 2023-06-02 10:11
app = Flask(__name__)

def get_cookiefile():
    default_cookiefile = {
        "Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/*/cookies.sqlite",
        "Darwin": "~/Library/Application Support/Firefox/Profiles/*/cookies.sqlite",
    }.get(system(), "~/.mozilla/firefox/*/cookies.sqlite")
    cookiefiles = glob(expanduser(default_cookiefile))
    if not cookiefiles:
        raise SystemExit("No Firefox cookies.sqlite file found. Use -c COOKIEFILE.")
    return cookiefiles[0]


def import_session(cookiefile, sessionfile):
    print("Using cookies from {}.".format(cookiefile))
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
    try:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE baseDomain='instagram.com'"
        )
    except OperationalError:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE host LIKE '%instagram.com'"
        )
    instaloader = Instaloader(max_connection_attempts=1)
    instaloader.context._session.cookies.update(cookie_data)
    username = instaloader.test_login()
    if not username:
        raise SystemExit("Not logged in. Are you logged in successfully in Firefox?")
    print("Imported session cookie for {}.".format(username))
    instaloader.context.username = username
    instaloader.save_session_to_file(sessionfile)


if __name__ == "__main__":
    p = ArgumentParser()
    p.add_argument("-c", "--cookiefile")
    p.add_argument("-f", "--sessionfile")
    args = p.parse_args()
    try:
        import_session(args.cookiefile or get_cookiefile(), args.sessionfile)
    except (ConnectionException, OperationalError) as e:
        raise SystemExit("Cookie import failed: {}".format(e))



L = instaloader.Instaloader()

L.load_session_from_file("thescraper12")

# Votre code existant pour récupérer les données de profil


# ...


username="al_aoula"


posts = instaloader.Profile.from_username(L.context, f"{username}").get_posts()
Since="2023/05/30"
until="2023/05/20"
SINCE = datetime.strptime(Since,"%Y/%m/%d")
UNTIL = datetime.strptime(until,"%Y/%m/%d")


# PLATFORM_NAME = os.environ.get('PLATFORM_NAME')
a=[]
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    pu=[]

    if post.is_video:
        viewVideo = post.video_view_count
    else:
        viewVideo = None  # or set a default value if needed

    data = {
        "id_post": post.mediaid,
        "Date": post.date.strftime("%Y-%m-%d"),
        "Heure": post.date.strftime("%H:%M:%S"),
        "content": post.caption,
        "username": post.owner_username,
        "likecount": post.likes,
        "viewVideo": viewVideo,
        "replycount": post.comments,
        # "platformname": PLATFORM_NAME

    }
    # pu=[id_post,post_owner,post_date,post_caption,post_likes,post_comments]
    a.append(data)
    # L.download_post(post, "instagram")
df = pd.DataFrame(a, columns=["id_post","Date","Heure", "content", "username", "likecount","viewVideo", "replycount","platformname"])


df.to_csv("C:/Users/HP Probook/OneDrive/Images/Bureau/CsvScraping/instagram.csv", mode="w", sep=";",encoding='utf-8', index=False)
Infos_json = df.to_json(orient='records', indent=4, force_ascii=False)
print(Infos_json.encode('utf-8').decode('utf-8'))

**Comment by ihabpalamino** [comment] 2023-06-02 10:14
here is it i share with you my code it gives me the same error and then i adder the get_cookies and the import session file and delete cookies data from my browser and then 
I reconnected and it works fine again i think the session expired so you have always to delete data's cookies and reconnect from your browser

**Comment by milliorn** [comment] 2023-06-05 07:27
I'm also getting a 401, but after 12 downloads. My IP is clearly not banned, nor is my account. Otherwise, I wouldn't be able to log in. I also never logged in with my account using instaloader. If and when it asked for login, I would quit, and wait 48 hours. Never had an issue for over a year now, until about the same time this issue was published.

**Comment by milliorn** [comment] 2023-06-17 08:27
> I'm also getting a 401, but after 12 downloads. My IP is clearly not banned, nor is my account. Otherwise, I wouldn't be able to log in. I also never logged in with my account using instaloader. If and when it asked for login, I would quit, and wait 48 hours. Never had an issue for over a year now, until about the same time this issue was published. Cookies, ip's, vpn's, etc, nothing works.

For reasons unknown, it's working again. I assume this was just Instagram API.

**Comment by aandergr** [comment] 2023-06-26 05:50
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.

**Closed by aandergr** 2023-06-26 05:50 UTC
Labels: duplicate

**Comment by goodbyenary** [comment] 2024-09-03 10:30
https://apify.com/apify/instagram-hashtag-scraper
i found this and it seems to be working. Am i overlooking something? Kinda surprised.

**Comment by nebula0225** [comment] 2024-09-03 11:00
@goodbyenary "Pay $2.30 for 1,000 results" It's much more expensive than building it yourself.
