### ISSUE TITLE
"Username" disappear from json file

### ISSUE THREAD

**Issue by nincrw** [instaloader/instaloader#181] opened 2018-10-01 12:34 UTC
Hi,
I need to pull username and likes from hashtag
so I use commandline >> instaloader "#hashtag" and it works on July but today I run it again but 'username' part just disappear from json file could u please help suggest what I can do ?

Instaloader version
4.0.4

**Comment by aandergr** [comment] 2018-10-07 13:10
Instaloader 4.0.4 is very old. Could you update it to use the latest version? With pip this can be done using `pip install --upgrade instaloader`.

I think this is a duplicate of #151, where a comment describes how to workaround this.

**Closed by aandergr** 2018-10-07 13:10 UTC
