### ISSUE TITLE
Error, after need to re-login and change my password

### ISSUE THREAD

**Issue by robinhugy** [instaloader/instaloader#2444] opened 2024-11-25 04:19 UTC
Used command:
instaloader
--login=mylogin
--password=mypassword
--highlights
--stories
--tagged
--filename-pattern={filename}
--no-captions
--no-compress-json
_multiple usernames e.g:_ markzuckerberg instagram github

Loaded session from C:\Users\User\AppData\Local\Instaloader\session-user.
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D [retrying; skip with ^C]
Error when checking if logged in: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D
Login: Checkpoint required. Point your browser to /challenge/action/GFG5dhj76jtgj6tzu5_u6HrjHfgH45e4svjtrT3rQQgr5h6jrhcFfddrew-sS34628-_/NHjt645VcxuT883MIooA5mvD46r201AStz48980sbK55KMDz2f0ZXbLLw6i7qSWK1TA7lcSXl4PS9g/ffc_HH7HtGtmgrehtrA7ghgfer43GFDGHDFjne354356783dfsG212tgbhFsdsvjgh34/ - follow the instructions, then retry.

Hey!
Can you help me, please?
After i start the app, i need to re-login and need to change my password everytime.
tried: pip install instaloader --upgrade

**Comment by MonkeyKingViper** [comment] 2024-11-26 01:59
You got your account flagged real quick huh lol. How old is that account? Have you made posts on it? How many people did you add as friends in a day? How obviously are you using the account to scrape data that is against the TOS?

What I'm getting at is that your account is flagged so if you're logging in and doing anything sketchy, it's going to force you to log in and change your password for "safety".

If you use the account like a normal person for a while, maybe a week, and don't be so obvious, then you'll probably be able to use it. Otherwise you're gonna get an email about your account being suspended and have to use a photo ID to get back in, or just that your account was banned.

And if this was an older account, or god forbid your personal real account...really bad luck.

**Comment by robinhugy** [comment] 2024-11-26 02:11
Its 6+ years old.
Creating like 1 post/year xD
Idk how many people follow me/day.
Using everyday to download new pictures.
Sad..
Thanks for your time!

**Comment by MonkeyKingViper** [comment] 2024-11-26 04:30
Dang. Post more. Even if just BS things. Don't look like a spam account used for violating the TOS. Cause they're going in REALLY heavy on that in the new year. Try and just use the account normally for a few days and do normal human stuff that the AI isn't gonna flag. It's watching you right now so don't try again for at least a few days or normalcy.

**Comment by aandergr** [comment] 2024-11-28 08:28
The bug report you provided does not follow the template and lacks some necessary details. Specifically, it does not include a clear description of the issue, steps to reproduce, or error messages formatted as requested in the bug report guide. Additionally, the report seems to have multiple concerns mixed in, such as needing to re-login and changing passwords, which should be addressed separately.

This might also be a duplicate of issue #2307, where a similar problem with the 401 Unauthorized error and re-login requirements is reported.

**Closed by aandergr** 2024-11-28 08:28 UTC
Labels: no template
