### ISSUE TITLE
Instaloader.get_location_posts() loops endlessly and serves the same posts over and over

### ISSUE THREAD

**Issue by hitboxr** [instaloader/instaloader#1470] opened 2022-03-28 22:35 UTC
**Describe the bug**
When using `Instaloader.get_location_posts()`, the generator will return the same set of posts over and over again.

**To Reproduce**
```
from instaloader import Instaloader
L = Instaloader()
L.login(****, ****)
seen = set()

for post in L.get_location_posts('256297394873006'):
    if post.shortcode in seen:
        print(f'Found duplicate post {post.shortcode}')
    seen.add(post.shortcode)
```

**Expected behavior**
Iterator should return all posts from a location page in order, then stop iteration.

**Error messages and tracebacks**
I did some basic debugging of this to see where the `SectionIterator` logic was breaking down and it seems like it's properly advancing the `next_max_id` field, but for some reason instagram still returns the same data over and over. Could be a missing parameter within the new sections format or something.

I modified the SectionIterator to print the `more_available` flag and its current `next_max_id` whenever it reaches the end of a query, and it's obviously advancing with each request. However, the data returned by instagram remains the same and as such, the `more_available` flag always remains true, causing the infinite loop.

Log truncated for clarity.
```
....
....
self._data['more_available'] = True
self._data["next_max_id"] = 'QVFDVHRDT1dJSFZ5NTI2SFdlSHZUblR4S1lCZ3Zja3lTT0dfMDBSazViTGJYRDNhVjBxaERpeF9RdkR1OTk2Qmp0ZHpKN0VrbHB0TWJLT2RGYmJXb3VVMA=='
Found duplicate post CbqLt1qvyja
Found duplicate post CboDVwWJMH8
Found duplicate post CbnOr89rD6K
....
....
self._data['more_available'] = True
self._data["next_max_id"] = 'QVFEbERhOGhtd0QwZUprUE1Sd3lsRVdjQ1U5VDY1SlRHSXF1Vmt6U0dzVzV5RkJMZEozVFEwWUlLRWJ1QVREdkszOURad1FVVzl2N19Xc3luUGxPSzJmTw=='
Found duplicate post CbqLt1qvyja
Found duplicate post CboDVwWJMH8
Found duplicate post CbnOr89rD6K
....
....
```

**Instaloader version**
4.9

**Comment by GGImpact** [comment] 2022-03-31 09:39
I think this issue is similar to #1430, where generator always return first 30 posts infinitely

**Comment by hitboxr** [comment] 2022-03-31 22:25
Yep, definitely looks like the same issue. However in that case, there's a GraphQL query hash that side-steps the problem and works to properly pull paginated hashtag data as seen here: https://github.com/instaloader/instaloader/blob/218d88fc6d7e981676e5ce0c0ea47ffd99ee27fb/instaloader/structures.py#L1622-L1634


But that doesn't do anything for this issue unless there's also a GraphQL query hash that functions similarly for locations. Since the browser site no longer uses GQL fetching for location posts (and I don't know if it ever did), I don't have a way to see if that exists or not. I suppose if one of the instagram apps uses GQL for fetching location posts and someone could sniff the query hash from that, then a similar solution could be implemented for locations, but otherwise we may have to implement a working scheme for requesting paginated data from the new `/sections/` endpoint.

**Comment by aandergr** [comment] 2022-04-18 08:29
Duplicate of #1341

**Closed by aandergr** 2022-04-18 08:29 UTC
Labels: duplicate

**Comment by tari3x** [comment] 2024-01-14 02:39
I might have found the query_hash after some googling:
```
https://www.instagram.com/graphql/query/?query_hash=ac38b90f0f3981c42092016a37c59bf7&variables={"id":"703629436462521","first":12,"after":"XXXXXXXX"}
```

See https://stackoverflow.com/questions/49265339/instagram-a-1-url-not-working-anymore-problems-with-graphql-query-to-get-da
