### ISSUE TITLE
Can't collect likes number

### ISSUE THREAD

**Issue by pvita** [instaloader/instaloader#1355] opened 2021-12-04 09:44 UTC
**Describe the bug**
I tried to collect posts directly (target: shortcode) or from their feed (target: username) and for 99% of the posts likes are -1

**Instaloader version**
`4.9b1.

**EDIT**: without --login likes are correctly collected, but after some posts login is required.

**Comment by 89z** [comment] 2021-12-04 13:51
Please provide example post

**Comment by pvita** [comment] 2021-12-04 14:05
just tried with this one: yza2PAPSx2
(and many thousands more)

**Comment by 89z** [comment] 2021-12-04 14:09
It does work, but you have to use anonymous request:

~~~
GET https://www.instagram.com/p/yza2PAPSx2/?__a=1
{Display_URL:https://scontent-hou1-1.cdninstagram.com/v/t51.2885-15/e15/10954716_778080568935429_305899958_n.jpg?_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_cat=109&_nc_ohc=Lv2aIgeWEBQAX-kTCVV&edm=AABBvjUBAAAA&ccb=7-4&oh=b92b855e844b960e16221f34ef0dd666&oe=61B3316B&_nc_sid=83d603&ig_cache_key=OTE1MTkzMjI1NDU3NTExNTQy.2-ccb7-4
Edge_Media_Preview_Like:{Count:19970}
Edge_Media_To_Parent_Comment:{Edges:[{Node:{Text:@piccipooh}}
{Node:{Text:@__bloodymary__ sentiti male}} {Node:{Text:@howl_____ a che
livelli..}} {Node:{Text:Guarda qui vai com'e caria @duchessabeatrice}}
{Node:{Text:Figa}} {Node:{Text:Ma sei cantante o modella?}}
{Node:{Text:Camionista}} {Node:{Text:@desvallerignani 😍}} {Node:{Text:Top😍
@giadav25}} {Node:{Text:@212vs}} {Node:{Text:@antobernardi59}}
{Node:{Text:@real_brown outfit perfetto..❤️ alla faccia di tutti quelli che
aprono bocca e le danno fiato!!! 😋}} {Node:{Text:Come fai ad essere cosi
bella}} {Node:{Text:Ma anche no!}} {Node:{Text:Minchia stai benissimo!
Bellissima davvero!}} {Node:{Text:Love it!}} {Node:{Text:Troppo
bella"!!!😍😍😍😍}} {Node:{Text:E k style!!!!!}} {Node:{Text:😂😂😂😂}}
{Node:{Text:@ericarecupero}} {Node:{Text:Sei la mia preferita}} {Node:{Text:Sei
la preferita del mio fratellino}} {Node:{Text:Là mia vicina ti canta sempre ma
anche io sei forte eeee e! !!!!!!!!! 😉😂👍👍👍👍👍👍}} {Node:{Text:☁️}}]}
Edge_Sidecar_To_Children:<nil> Video_URL:}
~~~

**Comment by pvita** [comment] 2021-12-04 14:11
> 

Thanks. Is there any command to do it with instaloader through cmd?

**Comment by 89z** [comment] 2021-12-04 14:12
I use my own tool:

https://github.com/89z/mech

**Comment by rocailler** [comment] 2021-12-05 09:02
for some period of time there is a problem with -1 instead of likes count. 
I'm thinking.... In response we get:
`"edge_liked_by":{"count":12344},"edge_media_preview_like":{"count":-1}`
and function for likes is:
```@property
    def likes(self) -> int:
        """Likes count"""
        return self._field('edge_media_preview_like', 'count')```

why we aren't using 'edge_liked_by' ?

**Comment by pvita** [comment] 2021-12-10 18:40
> edge_liked_by

Also "edge_liked_by" is -1 if you are logged in. And it is necessary for large collections

**Comment by Thammus** [comment] 2021-12-11 15:12
Duplicate of #1314.

**Closed by Thammus** 2021-12-11 15:12 UTC
Labels: duplicate
