### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by manishdashsharma** [instaloader/instaloader#639] opened 2020-05-28 05:54 UTC
Your question here...
To work on this module we have to give commands on our command prompt i.e instaloader profile [profil name...] . Is there any UI already developed for instaloader ?
what i mean rather typing a command in command prompt we can use the UI to download the post . There should be a input box which will take user name and next box will have commands . after that when i press enter the post will get downloaded .

**Comment by ungenio** [comment] 2020-05-28 07:17
you can create a bat file, for example `stories.bat`, with the following code:

```
@echo off
title INSTALOADER
:start
echo.
set /p profile="PROFILE: "
instaloader --stories %profile%
goto start
```

you run it and only enter the name of the profile. Customize the command according to what you want to download.

**Comment by Deleora** [comment] 2020-05-30 02:24
Or if you are a developer you can code it yourself, it shouldn't be hard. Even I've been thinking of doing this myself but I'm caught up with other things as well. If I ever start, I'll let the community know. Peace

**Comment by aandergr** [comment] 2020-05-30 09:11
Duplicate of #634.

**Closed by aandergr** 2020-05-30 09:11 UTC
Labels: duplicate
