### ISSUE TITLE
Problem When Downloading

### ISSUE THREAD

**Issue by Carton9** [instaloader/instaloader#1726] opened 2022-09-04 20:10 UTC
Yet the user do exist/

Loaded session from C:\Users\****\AppData\Local\Instaloader\*****
Logged in as *****.
JSON Query to ******./feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Trying to find profile ******. using its unique ID ******.
Profile  ******.. has changed its name to ******.
JSON Query to  ******./feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile ******. does not exist.

**Comment by Showmaster3000** [comment] 2022-09-04 23:28
incomplete bug report.
duplicate of #1553 (and many more).

**Closed by Showmaster3000** 2022-09-04 23:28 UTC
Labels: bug
