### ISSUE TITLE
Error; while running a bat file to download instagram stories 

### ISSUE THREAD

**Issue by Purefreeman** [instaloader/instaloader#108] opened 2018-04-25 00:08 UTC
Traceback (most recent call last):
  File "c:\users\free_000\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\free_000\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\free_000\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader.exe\__main__.py", line 9, in <module>
  File "c:\users\free_000\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1802, in main
    filter_str=args.only_if)
  File "c:\users\free_000\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1620, in main
    filter_func=filter_func)
  File "c:\users\free_000\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1476, in download_profile
    profile_metadata, full_metadata = self.get_profile_metadata(name)
  File "c:\users\free_000\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1431, in get_profile_metadata
    return metadata['entry_data']['ProfilePage'][0]['graphql'], metadata
KeyError: 'ProfilePage

**Comment by aandergr** [comment] 2018-04-26 09:39
Duplicate of #95

**Closed by aandergr** 2018-04-26 09:39 UTC
