### ISSUE TITLE
runpy.py errors with 4.4.4rc1 ValueError: path is on mount 'C:', start on mount 'F:'

### ISSUE THREAD

**Issue by beakwood** [instaloader/instaloader#674] opened 2020-06-08 03:39 UTC
**Describe the bug**
Script bug

**To Reproduce**
instaloader -l xxxx -p xxxx +list.txt --fast-update --no-profile-pic --no-captions --no-metadata-json --no-video-thumbnails --filename-pattern "{profile}_{mediaid}_{date_utc}"
 Traceback (most recent call last):
  File "c:\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python38\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "c:\python\python38\lib\site-packages\instaloader\__main__.py", line 239, in main
    parser = ArgumentParser(description=__doc__, add_help=False, usage=usage_string(),
  File "c:\python\python38\lib\site-packages\instaloader\__main__.py", line 32, in usage_string
    argv0 = get_simple_argv0()
  File "c:\python\python38\lib\site-packages\instaloader\__main__.py", line 23, in get_simple_argv0
    dirname = os.path.relpath(os.path.dirname(sys.argv[0]))
  File "c:\python\python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'F:'

**Expected behavior**
download profiles with the highest resolution

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
instaloader 4.4.4rc1

**Additional context**
instaloader 4.4.3 works perfectly fine. I just wanted to upgrade to download the highest resolution.

**Comment by Thammus** [comment] 2020-06-09 08:38
Duplicate of #671.

**Closed by Thammus** 2020-06-09 08:38 UTC
Labels: duplicate
