### ISSUE TITLE
Post.get_comments() doesn't return all the comments

### ISSUE THREAD

**Issue by vincenzo-viola** [instaloader/instaloader#706] opened 2020-06-28 16:11 UTC
**Describe the bug**
Sometimes it happens that the Post.get_comments() doesn't return all the comments. If I print the returned comments or I count the iterator items, I see that the number of comments is minor of the real number of comments, that is the same returned by post.comments.

**To Reproduce**
Get the post with the shortcode CB02kd9Bb5O, then 

```
  comments = post.get_comments()
  comments_num = 0
        for comment in comments:
            comments_num  =  comments_num  + 1
            answers = comment.answers
            for answer in answers:
                comments_num  =  comments_num  + 1

  comments_num_2 = post.comments
```

Just compare comment_num and comments_num_2 in order to find out the issue.

**Comment by Thammus** [comment] 2020-07-04 14:21
Duplicate of #460.

**Closed by Thammus** 2020-07-04 14:21 UTC
Labels: duplicate
