### ISSUE TITLE
Error with tagged posts 

### ISSUE THREAD

**Issue by maddingamer** [instaloader/instaloader#199] opened 2018-11-16 08:07 UTC
**Describe the bug**
When using the command --tagged, the system somehow has a problem with the folder starting with a colon

**To Reproduce**
instaloader username --tagged --dirname-pattern /PATH/{target}/

**Error messages and tracebacks**
[  1/???] Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 388, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 171, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 835, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 711, in download_tagged
    downloaded = self.download_post(post, target)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 358, in download_post
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/PATH/:tagged'

**Instaloader version**
4.1.1

**Additional context**

**Comment by maddingamer** [comment] 2018-11-16 08:09
Update: Same issue when using only "instaloader username --tagged" 
Does not happen on Windows.

**Comment by maddingamer** [comment] 2018-11-18 15:09
Update: 

I removed the colon in line 702 of instaloader.py  from
` target = profile.username + '/:tagged'`
 to

`target = profile.username + '/tagged'`

and now execute the instaloader.py via python3 instead of installing it (install failed somehow..) so this is a working solution for now.

**Comment by aandergr** [comment] 2018-12-14 16:03
I'm closing this issue as I cannot reproduce it. If there is any more information, please feel free to reopen it.

**Closed by aandergr** 2018-12-14 16:03 UTC

**Comment by maddingamer** [comment] 2018-12-23 19:43
Still happening in v4.2 using Raspbian

**Comment by Showmaster3000** [comment] 2019-02-02 02:32
Just tried --tagged today and run into similar issue.
The problem is the colon (:), which is NOT an allowed character in file and folder names in Windows.

```
Retrieving tagged posts for profile targetprofile.
[  1/???] [13660] Failed to execute script __main__
Traceback (most recent call last):
  File "C:\Instaloader\__main__.py", line 444, in <module>
  File "C:\Instaloader\__main__.py", line 440, in __main
  File "C:\Instaloader\__main__.py", line 415, in main
  File "C:\Instaloader\__main__.py", line 189, in _main
  File "C:\Instaloader\instaloader\instaloader.py", line 923, in download_profiles
  File "C:\Instaloader\instaloader\instaloader.py", line 799, in download_tagged
  File "C:\Instaloader\instaloader\instaloader.py", line 411, in download_post
  File "C:\Instaloader\instaloader\instaloader.py", line 195, in download_pic
  File "C:\Instaloader\instaloader\instaloadercontext.py", line 497, in get_and_write_raw
  File "C:\Instaloader\instaloader\instaloadercontext.py", line 452, in write_raw
  File "C:\Instaloader\instaloader\instaloadercontext.py", line 97, in log
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\ua789' in position 12: character maps to <undefined>
```
The position 12 mentioned in the last line ist the length of the nickname (11 chars in my case) plus directory separator.
