### ISSUE TITLE
Hashtag object not working anymore?

### ISSUE THREAD

**Issue by Tortar** [instaloader/instaloader#1628] opened 2022-07-12 21:20 UTC
**bug description**

Exception when creating hashtag object

**To Reproduce**

import instaloader
L = instaloader.Instaloader()
hashtag = instaloader.Hashtag.from_name(L.context, "disney") #or any other tag

**Expected behavior**

the creation of the Hashtag object 

**Error messages and tracebacks**

simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Instaloader version**
4.9.2.

It worked some hours ago, but now strangely fails. It seems that it returns a page with "Sorry, this page isn't available" but it actually exists. Still after a day, it continues to give me the same error message.

**Comment by Tortar** [comment] 2022-07-12 23:02
It is the same as [#1607](https://github.com/instaloader/instaloader/issues/1607)

**Comment by lchpoikj** [comment] 2022-07-13 21:34
Command line option for hashtag is not working either.

**Comment by Thammus** [comment] 2022-07-14 18:04
Duplicate of #1588

**Closed by Thammus** 2022-07-14 18:04 UTC
Labels: duplicate
