### ISSUE TITLE
400 Bad Request when retrieving hastag media count for multiple tags. 

### ISSUE THREAD

**Issue by Kal-Toh** [instaloader/instaloader#1612] opened 2022-07-04 13:07 UTC
**Describe the bug**

I have a list of IG hashtags on a spreadsheet which the program I wrote accessing and using Instaloader to retrieve the hashtag count for. The list is currently around 1000. After it gets to just over 500, I get:
Traceback (most recent call last):

'File /xx/_Main_.py", line 115, in <module>
    h = Hashtag.from_name(l.context, htag)

  File "/xx/venv/lib/python3.10/site-packages/instaloader/structures.py", line 1482, in from_name
    hashtag._obtain_metadata()

  File "/xx/venv/lib/python3.10/site-packages/instaloader/structures.py", line 1496, in _obtain_metadata
    self._node = self._query({"__a": 1})

  File "/xx/venv/lib/python3.10/site-packages/instaloader/structures.py", line 1491, in _query
    json_response = self._context.get_json("explore/tags/{0}/".format(self.name), params)

  File "/xx/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 345, in get_json
    raise QueryReturnedBadRequestException("400 Bad Request")

instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request`

**To Reproduce**

The code I am using is:
`l = Instaloader()
l.login("user", "pass")
timer = random.randint(6, 12)

for cell in sheet[col5][1:]:
htag = cell.value
print(htag)
h = Hashtag.from_name(l.context, htag)
print(h.mediacount)
sheet.cell(cell.row, col6).value = h.mediacount
book.save('alpha1.xlsx')
time.sleep(timer)`

I used a timer to avoid getting caught by IG and having my acc locked, which has worked. I have not had to reconfirm 2FA or unlock my account. 

**Expected behavior**
It should continue through this list until its completion.

**Instaloader version**
I am using the latest version of Instaloader 4.9.1

**Additional context**

**Comment by Thammus** [comment] 2022-07-14 18:04
Duplicate of #1588

**Closed as not planned by Thammus** 2022-07-14 18:04 UTC
Labels: duplicate
