### ISSUE TITLE
Cooldown/Timeout for downloading profile content (posts, stories, highlights etc...)

### ISSUE THREAD

**Issue by MirayXS** [instaloader/instaloader#1668] opened 2022-07-28 15:08 UTC
**Provide us a use case of the feature**
Hello there. I've been using instaloader to preserve 1K posts of a user.
The problem is that i keep getting logged out and banned from my accounts. ( i also use the --login flag, but this happens without it too. It's instagram when there are to many requests.)
I thought that this is because of instaloader being to fast.
I thought of a quick solution, which is to implement a cooldown/timeout flag and the input it's in seconds.
example: --timeout 600 (600=10 minutes)

**Describe the solution you'd like**
this flag will work like this: When the timeout ends, it downloads the next content, and then timeouts again, download the next content, and so on...

**Describe alternatives you've considered**
The only alternative i've found out is to click in the terminal to make it stop temporarily and then press enter.  This will stop instaloader from processing and then resume. Might be able to automate this with an autoclicker, too.

**If the feature request is accepted, would you be willing to submit a pull request?**
I don't think so, sorry. It's because i'm not the best at coding.

**Comment by EveryDirection** [comment] 2022-07-28 16:32
I just came here about to suggest the same thing. I am finding it impossible to reach older posts of any profile of more than a hundred posts or so because Instagram keeps constantly blocking after just a hundred or so requests. Maybe introducing a delay will help.

**Comment by thariq-nugrohotomo** [comment] 2022-07-29 23:34
+1

I'm suspecting that Instagram is reducing their maximum allowed request-rate, to the point that Instaloader's rate-limiting is not suitable anymore.
I'm using instaloader twice per day (thus every 12 hours to download the stories from 20 public accounts), but my account get frequently blocked recently.

I think it would be wise to expose the rate-limiting control as a command-shell argument, instead of hardcoding it. That way user doesn't need to wait for the next release to mitigate the issue when Instagram doing this again in the future.

**Comment by thariq-nugrohotomo** [comment] 2022-07-29 23:49
Also see https://github.com/instaloader/instaloader/issues/1648 pointing that Instaloader self rate-limiting functionality may be broken.

**Comment by afterdelight** [comment] 2022-07-30 23:47
try this code to disable Instaloader self rate-limiting function and add sleep delay

edit instaloadercontext.py

```
try:
            self.do_sleep()
            if is_graphql_query:
                print('sleep for 6 seconds')
                time.sleep(6)
                #self._rate_controller.wait_before_query(params['query_hash'])
            if is_iphone_query:
                print('sleep for 6 seconds')
                time.sleep(6)
                #self._rate_controller.wait_before_query('iphone')
            if is_other_query:
                print('sleep for 6 seconds')
                time.sleep(6)
                #self._rate_controller.wait_before_query('other')

```

**Comment by aandergr** [comment] 2022-08-11 18:41
Duplicate of #1006.

> Instaloader has a logic to keep track of its requests to Instagram and defers subsequent ones in order to not reach Instagram's rate limits. This rate controlling logic also gets applied when using Instaloader through CLI.

**Closed by aandergr** 2022-08-11 18:41 UTC
Labels: duplicate

**Comment by MirayXS** [comment] 2022-08-11 22:12
ok
