### ISSUE TITLE
400 Bad Request.

### ISSUE THREAD

**Issue by DanyalAhmad832** [instaloader/instaloader#2392] opened 2024-10-10 07:05 UTC
Hello,

I am encountering an issue when using Instaloader to access Instagram posts via the GraphQL query. The specific error I am receiving is:

400 Bad Request - "fail" status, message "feedback_required"
This occurs when making a request to the following endpoint:

https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22C_AZnqxvL7j%22%7D
It seems to happen with certain posts, and I'm not sure whether it's related to Instagram's API limitations or something else. I've been using Instaloader successfully up until now, so any insight into why this error occurs and how to resolve it would be greatly appreciated.

Thank you!

**Comment by Showmaster3000** [comment] 2024-10-10 18:27
duplicate of #2384

**Closed** 2024-10-10 18:29 UTC
Labels: duplicate
