### ISSUE TITLE
Is only downloading "12", no matter how much over 12 is there.

### ISSUE THREAD

**Issue by Gitphex** [instaloader/instaloader#2324] opened 2024-07-31 21:46 UTC
**Describe the bug**
No matter that there are more than 12, it can be 100, 600 or 1000 pictures and videos but for some accounts is only downloading exactly and only 12, and it finish like there is no error or anything wrong.

**To Reproduce**
(e.g. Instaloader command line)

**Expected behavior**
To download all the pictures and photos, like if there are 100, download 100 etc.

**Error messages and tracebacks**
No errors.

**Instaloader version**
instaloader - v4.12.1

**Additional context**
I tried a version before this one and i had the same problem so i assume Instagram changed something?... Probably.

**Comment by MonkeyKingViper** [comment] 2024-07-31 22:11
Probably #2319

**Comment by samuelchristlie** [comment] 2024-08-01 06:57
Might be related to https://github.com/instaloader/instaloader/issues/2307 as well

**Comment by fireattack** [comment] 2024-08-02 04:15
Duplicate of #2307

**Closed by fireattack** 2024-08-02 04:15 UTC
Labels: duplicate
