### ISSUE TITLE
has_public_story failing

### ISSUE THREAD

**Issue by utkarshdalal** [instaloader/instaloader#372] opened 2019-08-09 11:00 UTC
**Describe the bug**
When I try to check if a user has a public story with profile.has_public_story, I get an HTTP error code 403 response.

**To Reproduce**
`from instaloader import Instaloader`
`L = Instaloader()`
`profile = Profile.from_username(L.context, username)`
`has_public_story = profile.has_public_story`

**Expected behavior**
It should return true or false, and not error out.

**Error messages and tracebacks**
```
>>> has_public_story = profile.has_public_story
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.
```

**Instaloader version**
4.2.8

**Additional context**

**Comment by jewl123** [comment] 2019-08-09 13:36
I think this stems from facebook changing graphql.

 I am also getting `JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]` when scraping captions and urls.

**Comment by joalro** [comment] 2019-08-09 14:04
I am also getting this error.  I've attempted to bypass it by only taking exactly what I need.  When calling instaloader, I've now set the following parameters:

`download_geotags=False, post_metadata_txt_pattern='', download_comments=False, save_metadata=False`

So far it is still failing for me, giving me the same error.

**Comment by jewl123** [comment] 2019-08-09 14:13
So far it appears that the error happens when instaloader is trying to scroll down and load a new page.

**Comment by aandergr** [comment] 2019-08-18 09:48
> **To Reproduce**
> Steps to reproduce the behavior:
> `from instaloader import Instaloader`
> `L = Instaloader()`
> `profile = Profile.from_username(L.context, username)`
> `has_public_story = profile.has_public_story`

I tested this with several usernames and it always worked. Can you give concrete examples where it fails?

**Comment by aandergr** [comment] 2019-10-14 05:54
I'm closing this since I cannot reproduce it and no more information given since two month. 

Please reopen if the bug still occurs.

**Closed by aandergr** 2019-10-14 05:54 UTC
Labels: bug
