### ISSUE TITLE
Private but not followed on own account when logging in with email adress

### ISSUE THREAD

**Issue by Knusper** [instaloader/instaloader#632] opened 2020-05-23 01:04 UTC
**Describe the bug**

I tried to make a backup of my account with 'instaloader --login=your_username my_profile'.  When I use my email-adress as username I get logged in, but then I get the "Private but not followed" error.  The download only works correctly if I use my profile name as login.

**To Reproduce**

Instead of using your profile name, try logging in with the email adress.

**Expected behavior**

The download of my own profile should work when logging in with valid user credentials.

**Instaloader version**
 4.4.3

**Comment by Thammus** [comment] 2020-05-23 08:52
Duplicate of #624.

**Closed by Thammus** 2020-05-23 08:52 UTC
Labels: duplicate
