### ISSUE TITLE
Can't log in to instagram.

### ISSUE THREAD

**Issue by tmaxgo404** [instaloader/instaloader#1826] opened 2022-12-09 00:27 UTC
**Describe the bug**
When I try to use the --login command, it gives a fatal
 error and says I need to go to a different link and then retry. When I retry it gives the same error.

C:\Users\Admin\Downloads\57>instaloader +args.txt
Session file does not exist yet - Logging in.
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXF0DaYKzOnFSowvem6EWpx-YvI5dMb2FPI7yvYHWVsh9TaN9ID61RVAICZQf-Q1Eo3XcsQ/Afwd1sxail14Qf1engfP1D4DQkuRhBg028j5YxPDaPU1qpV95KFIXoCIFTgyQ2fuTarcIJyd_QE6Lw/ffc_vSPmf7nfs67MPHwCVA6MHTp70AW7fOYRbynzL1vvgFG9ouP8ZHjBHgBgzRWC2Thp/ - follow the instructions, then retry.

**To Reproduce**
(e.g. Instaloader command line)

I made an args file, but it has the same error as putting --login to the command line. 

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).

I expect the file to log into my account and download a profile, putting the file of images into the folder '57' in downloads. 

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

C:\Users\Admin\Downloads\57>instaloader +args.txt
Session file does not exist yet - Logging in.
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXF0DaYKzOnFSowvem6EWpx-YvI5dMb2FPI7yvYHWVsh9TaN9ID61RVAICZQf-Q1Eo3XcsQ/Afwd1sxail14Qf1engfP1D4DQkuRhBg028j5YxPDaPU1qpV95KFIXoCIFTgyQ2fuTarcIJyd_QE6Lw/ffc_vSPmf7nfs67MPHwCVA6MHTp70AW7fOYRbynzL1vvgFG9ouP8ZHjBHgBgzRWC2Thp/ - follow the instructions, then retry.

**Instaloader version**
`instaloader --version` output.

4.9.5

**Additional context**

**Comment by MSiam** [comment] 2022-12-09 15:11
I have the same issue too. Can someone help on this? Thanks

**Comment by afterdelight** [comment] 2022-12-10 01:38
maybe this will help
https://github.com/instaloader/instaloader/pull/1784

**Comment by TonyPrater10** [comment] 2022-12-14 23:20
Try [this](https://github.com/instaloader/instaloader/issues/240#issuecomment-458653581)

Using the login method did not work for me. What did work was logging out and signing into instagram on FireFox. Then just load the session from your login name

**Comment by tmaxgo404** [comment] 2022-12-28 22:48
> Try [#240](https://github.com/instaloader/instaloader/issues/240#issuecomment-458653581)
> 
> Using the login method did not work for me. What did work was logging out and signing into Instagram on Firefox. Then just load the session from your login name

how do i load the session from my login name?

**Comment by aandergr** [comment] 2022-12-29 10:36
Duplicate of #1787

**Closed by aandergr** 2022-12-29 10:36 UTC
Labels: bug
