### ISSUE TITLE
Having issue with v 4.7.1 during last week 

### ISSUE THREAD

**Issue by sofiavlachou28** [instaloader/instaloader#1097] opened 2021-04-15 14:23 UTC
Having issue with v 4.7.1 too during last week, when I try to download `instance.download_hashtag(hashtag="moodoftheday",max_count=10)` It is not a login problem in my case. I did not make any changes to the code I always worked on. 

Now I get two errors!!! : 
1. (KeyError: 'graphql')
2. TypeError: 'NoneType' object is not subscriptable

My code always worked well.  Did the API or Insta change? Is there a solution?
I did not find any solution from the answers of other users... 

Can anyone tell us what happened??? 

sorry to report again.  there are many users with similar problems

Thank you in advance

**Comment by aandergr** [comment] 2021-04-15 19:30
Duplicate of #1080.

**Closed by aandergr** 2021-04-15 19:30 UTC
Labels: duplicate
