### ISSUE TITLE
On all accounts error 400 after downloading 1 story

### ISSUE THREAD

**Issue by denbartman** [instaloader/instaloader#1640] opened 2022-07-16 11:04 UTC
**Describe the bug**
If have 6 batch files. Each batch uses his own account to download some stories from some users (1 to 30 users per batch). Since 14/7 after downloading the first story i get the following error:

Download aborted: Query to https://i.instagram.com/api/v1/media/2883012367629919545/info/ responded with "400 Bad Request".

I did get the error 560 sometimes before 14/7. But now I only get the 400 error. On All Accounts. All accounts are still working in the app an in the pc browser. So they are not locked.

I had this once before on 1 account about a month ago, but a day after it worked again.

I tried with only 1 account, same problem.

I added the --user agent option, but that doesn't seem to help

I tried the workaround for the 560 error 
I changed the userids_per_query=50`  to 5 and then to 1 but that has no effect either.

Any idea if this is a common problem or what i can do to fix this?

**To Reproduce**
This is my arg file
```
--login=xxx
--no-posts
--stories
--user-agent=Mozilla/5.0 (Linux; Android 10; SM-N960F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36
--dirname-pattern=m:/IG_Instaloader/{target}/Stories/
--filename-pattern={date_local:%Y-%m-%d_%H-%M-%S}-000 {profile} (S) {mediaid}
--title-pattern={profile}_ProfilePic_{date_local:%Y-%m-%d_%H-%M-%S}
--no-video-thumbnails
--no-metadata-json
--no-compress-json
--latest-stamps=c:/Programs/Instaloader/latest-stamps.ini
--comments
--abort-on=400,429
8 user profiles
```

**Expected behavior**
Dowload stories from these profiles

**Error messages and tracebacks**

```
Using latest stamps from c:/Programs/Instaloader/latest-stamps.ini.
Loaded session from C:\Users\xxx\AppData\Local\Instaloader\session-xxx.
Logged in as xxx.
Downloading 8 profiles: prof1 prof2 prof3 prof4 prof5 prof6 prof 7 prof8
[1/8] Downloading profile prof1
[2/8] Downloading profile prof2
[3/8] Downloading profile prof3
[4/8] Downloading profile prof4
[5/8] Downloading profile prof5
[6/8] Downloading profile prof6
[7/8] Downloading profile prof7
[8/8] Downloading profile prof8
Downloading stories
[1/8] Retrieving stories from profile prof4.
[2/8] Retrieving stories from profile prof5.
[  1/  4] 
Download aborted: Query to https://i.instagram.com/api/v1/media/2883012367629919545/info/ responded with "400 Bad Request".
Saved session to C:\Users\xxx\AppData\Local\Instaloader\session-xxx.

```

**Instaloader version**
4.9.2

**Additional context**

**Comment by Showmaster3000** [comment] 2022-07-16 11:15
Duplicate of #1633.

**Closed** 2022-07-17 22:53 UTC
Labels: duplicate
