### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by beatsandmelody** [instaloader/instaloader#663] opened 2020-06-05 18:19 UTC
I just built today and can't get it to work.

pip3 install instaloader
result: Successfully built instaloader

instaloader profile [profile ...] where [profile ...] is a public profile name
result: instaloader: command not found

**Comment by Thammus** [comment] 2020-06-06 09:52
Duplicate of #440.

**Closed by Thammus** 2020-06-06 09:52 UTC
Labels: duplicate
