### ISSUE TITLE
instaloader v4.10 fails to download posts with "ZeroDivisionError: integer division or modulo by zero"

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#2105] opened 2023-11-11 07:55 UTC
**Describe the bug**
instaloader v4.10 fails to download posts with "ZeroDivisionError: integer division or modulo by zero"

**To Reproduce**
 instaloader --login=USER --user-agent "YOURUSERAGENT" --abort-on=302,400,401,429,403  --stories  --tagged --highlights irida_papoutsi/ 
(fail at 110 tagged post)

I use `python3 615_import_firefox_session.py  -c /mnt/tmp/firefox/default/cookies.sqlite ` to login.
Sometimes the problem was not refreshing the login but not now. 

**Expected behavior**
to download all posts. tagged post are a lot of more than 110. 

**Error messages and tracebacks**
```
[108] irida_papoutsi/:tagged/2022-09-10_23-06-13_UTC.jpg exists [Coloring Festival 🔥😍] unchanged irida_papoutsi/:tagged/2022-09-10_23-06-13_UTC.mp4 exists json 
[109] irida_papoutsi/:tagged/2022-09-09_18-53-51_UTC.jpg exists [Reserve your table at @clownd…] unchanged irida_papoutsi/:tagged/2022-09-09_18-53-51_UTC.mp4 exists json 
[110] Traceback (most recent call last):
  File "/home/elias/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 1466, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter,
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 1264, in download_tagged
    self.posts_download_loop(tagged_posts,
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 1064, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 724, in download_post
    for i in range(self.slide_start % post.mediacount, self.slide_end % post.mediacount + 1)),
ZeroDivisionError: integer division or modulo by zero
```

**Instaloader version**
`instaloader --version` output.
4.10

Because i have this problem quite a few times, i request to exists an option to "skip" the nth post (--skip-tagged-post 110), if this can solve the problem.

note similar bug exists but not reproducable --> 1085

**Comment by estatistics** [comment] 2023-11-28 11:16
67th tagged post - unable to download  - division by zero too. https://www.instagram.com/stikoudikaterin/tagged/

**Comment by aandergr** [comment] 2023-12-09 17:09
Duplicate of #1085

**Closed by aandergr** 2023-12-09 17:09 UTC
Labels: duplicate

**Comment by estatistics** [comment] 2023-12-09 18:30
Can you elaborate please why you says "not planned", while this tool is intending to download posts and stories, and this bug clearly show that cannot download all stories and posts?
