### ISSUE TITLE
Crash on KeyError: 'video_url' when accessing Post.video_url

### ISSUE THREAD

**Issue by somera** [instaloader/instaloader#449] opened 2019-11-02 23:21 UTC
**Describe the bug**
Instaloader crash on download some saved content.

**Error messages and tracebacks**

> File "instaloader\structures.py", line 157, in _field
> KeyError: 'video_url'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "__main__.py", line 446, in <module>
>   File "__main__.py", line 442, in __main
>   File "__main__.py", line 417, in main
>   File "__main__.py", line 159, in _main
>   File "instaloader\instaloader.py", line 49, in call
>   File "instaloader\instaloader.py", line 742, in download_saved_posts
>   File "instaloader\instaloader.py", line 491, in download_post
>   File "instaloader\structures.py", line 290, in video_url
>   File "instaloader\structures.py", line 160, in _field
>   File "instaloader\structures.py", line 143, in _full_metadata
>   File "instaloader\structures.py", line 137, in _obtain_metadata
> TypeError: 'NoneType' object is not subscriptable
> [23588] Failed to execute script __main__

**Instaloader version**
4.2.10

**Comment by valdearg** [comment] 2019-11-19 20:06
I get a pretty similar error occasionally:


```
Retrieving posts from profile mk_ays.
[  1/486] mk_ays/2019-11-19_17-43-33_UTC.jpg [Shinobu Kocho cosplay!🦋 Lense…] json
[  2/486] mk_ays/2019-11-15_18-37-38_UTC.jpg [Tried to remake my old Tsunad…] json
[  3/486] mk_ays/2019-11-14_17-54-19_UTC.jpg [Mimosa Vermillion costest❤️🌸 …] json
[  4/486] mk_ays/2019-11-12_18-10-53_UTC_1.jpg mk_ays/2019-11-12_18-10-53_UTC_2.jpg [Just feel the difference😱 my …] json
[  5/486] mk_ays/2019-11-10_15-16-23_UTC.jpg [Happy balloons day to me! YAA…] json
[  6/486] mk_ays/2019-11-08_17-30-54_UTC_1.jpg mk_ays/2019-11-08_17-30-54_UTC_2.jpg [How about Kanae Kocho costest…] json
[  7/486] mk_ays/2019-11-05_18-22-23_UTC.jpg [I’m happy to announce that my…] json
[  8/486] mk_ays/2019-10-31_17-44-19_UTC.jpg exists [Music is freedom! Freedom of …] unchanged Traceback (most recent call last):
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\structures.py", line 157, in _field
    d = d[key]
KeyError: 'video_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.2.10', 'console_scripts', 'instaloader')()
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\__main__.py", line 401, in main
    _main(loader,
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\__main__.py", line 187, in _main
    instaloader.download_profiles(profiles,
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\instaloader.py", line 1039, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\instaloader.py", line 491, in download_post
    downloaded &= self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local)
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\structures.py", line 290, in video_url
    return self._field('video_url')
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\structures.py", line 160, in _field
    d = self._full_metadata
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "c:\users\valdearg.neko\appdata\local\programs\python\python38\lib\site-packages\instaloader\structures.py", line 137, in _obtain_metadata
    if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by aandergr** [comment] 2020-01-19 18:37
Thanks for reporting!. All 3 reports that we received of this error message were in November 2019. This might have been a temporary inconsistency on Instagram's side. Does this problem still occur?

**Comment by somera** [comment] 2020-01-19 19:06
> Thanks for reporting. All 3 reports that we received of this error message were in November 2019. This might have been a temporary inconsistency on Instagram's side. Does this problem still occur?

Yep, problem still exists.

`  File "instaloader\structures.py", line 157, in _field
KeyError: 'video_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 446, in <module>
  File "__main__.py", line 442, in __main
  File "__main__.py", line 417, in main
  File "__main__.py", line 159, in _main
  File "instaloader\instaloader.py", line 49, in call
  File "instaloader\instaloader.py", line 742, in download_saved_posts
  File "instaloader\instaloader.py", line 491, in download_post
  File "instaloader\structures.py", line 290, in video_url
  File "instaloader\structures.py", line 160, in _field
  File "instaloader\structures.py", line 143, in _full_metadata
  File "instaloader\structures.py", line 137, in _obtain_metadata
TypeError: 'NoneType' object is not subscriptable
[3328] Failed to execute script __main__`

I prefer solution where I get an error message and the instaloader is skipping this URL. But the crash is not so good.

**Comment by christopherjanzen** [comment] 2020-03-23 15:17
I'm also receiving the same error:
```
[389] Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 426, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 160, in _main
    post_filter=post_filter)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 49, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 773, in download_saved_posts
    downloaded = self.download_post(post, target=':saved')
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 483, in download_post
    filename = dirname + '/' + self.format_filename(post, target=target)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 471, in format_filename
    return _PostPathFormatter(item).format(self.filename_pattern, target=target)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 186, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 108, in vformat
    ret = super().vformat(format_string, args, kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 190, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 230, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 295, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 116, in get_value
    ret = super().get_value(key, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 90, in get_value
    if hasattr(self._item, key):
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 212, in profile
    return self.owner_username
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 183, in owner_username
    return self.owner_profile.username
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 176, in owner_profile
    owner_struct = self._full_metadata['owner']
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 137, in _obtain_metadata
    if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable
```
I did have a successful run with different directory/filename parameters but after adding Profile to the filename and a date structure to the directory it is throwing this error.

**Comment by aandergr** [comment] 2020-03-24 10:13
@christopherjanzen The error message you posted is a different error than the one described in this issue, in that it refers to a problem getting the owner_username of a saved post (:saved), rather than obtaining the video_url of a video post. The error you are seeing has been reported in #503. Please feel free to share your observations there, especially how to reproduce the error.

**Comment by sseppola** [comment] 2020-03-26 08:48
I often get this error when importing a batch of bookmarked posts, is there a way to enable debug logs to get some more info about what is going on? Couldn't spot anything in the docs

**Comment by aandergr** [comment] 2020-03-26 09:44
Thanks to all of you for sharing your observations. Unfortunately, I still couldn't reproduce this issue. I tried to download the profile quoted in one of the error messages and it just works fine.

I'd like to see the JSON data returned by Instagram on the Posts where accessing `video_url` fails, to see whether the `video url` is in a different field or whether it's just missing. Unfortunately, Instaloader doesn't save the JSON when a Post fails to download. With a debugger and a breakpoint in e.g. `download_post()` we could still access it, and it would be nice if someone could share the `Post._node` and `Post._full_metadata` structures of a failing Post. 

What happens when you retry the download? Does it work, or does it fail at the exact same post again? In the latter case, could you tell us the shortcode (or the profile, the post's URL, ...) of an always-failing post? Otherwise, if retrying works, we could probably fix the issue by invoking our Download-Post-Retry-Logic (introduced for #225, where we already had a `video_url` KeyError) when the JSON lacks the `video_url` field. However, currently, only `download_profiles()` has this retry logic, the also-affected `download_saved_posts()` lacks it at the moment.

> I prefer solution where I get an error message and the instaloader is skipping this URL. But the crash is not so good.

Thanks for this suggestion. From the comments here, we can conclude two observations on how we could better handle Instaloader's behavior when a Post fails to download:
- Always save the JSON file to make debugging easier,
- Print the error and its traceback and skip the affected post, but do not interrupt the download loop.

**Comment by 54656452** [comment] 2020-04-02 18:40
I have also noticed this issue.
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Media\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Media\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\instaloader\__main__.py", line 412, in main
    _main(loader,
  File "C:\Users\Media\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\instaloader\__main__.py", line 192, in _main
    instaloader.download_profiles(profiles,
  File "C:\Users\Media\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\instaloader\instaloader.py", line 1106, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "C:\Users\Media\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\instaloader\instaloader.py", line 492, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "C:\Users\Media\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\instaloader\structures.py", line 231, in get_sidecar_nodes
    video_url=node['video_url'] if is_video else None)
KeyError: 'video_url'
```

**Comment by aandergr** [comment] 2020-04-04 09:10
@54656452 you're having a different issue which had been reported in #558 (now fixed).

**Comment by LouisVA** [comment] 2020-04-09 21:18
> Thanks to all of you for sharing your observations. Unfortunately, I still couldn't reproduce this issue. I tried to download the profile quoted in one of the error messages and it just works fine.
> 
> I'd like to see the JSON data returned by Instagram on the Posts where accessing `video_url` fails, to see whether the `video url` is in a different field or whether it's just missing. Unfortunately, Instaloader doesn't save the JSON when a Post fails to download. With a debugger and a breakpoint in e.g. `download_post()` we could still access it, and it would be nice if someone could share the `Post._node` and `Post._full_metadata` structures of a failing Post.
> 
> What happens when you retry the download? Does it work, or does it fail at the exact same post again? In the latter case, could you tell us the shortcode (or the profile, the post's URL, ...) of an always-failing post? Otherwise, if retrying works, we could probably fix the issue by invoking our Download-Post-Retry-Logic (introduced for #225, where we already had a `video_url` KeyError) when the JSON lacks the `video_url` field. However, currently, only `download_profiles()` has this retry logic, the also-affected `download_saved_posts()` lacks it at the moment.
> 
> > I prefer solution where I get an error message and the instaloader is skipping this URL. But the crash is not so good.
> 
> Thanks for this suggestion. From the comments here, we can conclude two observations on how we could better handle Instaloader's behavior when a Post fails to download:
> 
> * Always save the JSON file to make debugging easier,
> * Print the error and its traceback and skip the affected post, but do not interrupt the download loop.

vv_wanderlust I always get it on 4/379 so basically this post: https://www.instagram.com/p/B-mptvZHjl_/
It downloads, and then fails when it gets to the video (6th item in the post)

**Comment by aandergr** [comment] 2020-04-10 10:24
The new version of Instaloader, [Version 4.3.2](https://github.com/instaloader/instaloader/releases/tag/v4.3.2), doesn't break anymore if that issue occurs. Instead, the affected post is skipped, and a detailed error message is printed containing the bad metadata response, which may help us for debugging.

**Comment by krummrey** [comment] 2020-04-12 09:41
I Still have the same Problem:


instaloader --version
4.3

Retrieving posts from profile palinski.
[   1/1805] Traceback (most recent call last):
  File "C:\Users\jan\AppData\Local\Programs\Python\Python38-32\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.3', 'console_scripts', 'instaloader')()
  File "c:\users\jan\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\__main__.py", line 412, in main
    _main(loader,
  File "c:\users\jan\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\__main__.py", line 192, in _main
    instaloader.download_profiles(profiles,
  File "c:\users\jan\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\instaloader.py", line 1087, in download_profiles
    self.posts_download_loop(profile.get_posts(), profile_name, fast_update, post_filter,
  File "c:\users\jan\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\instaloader.py", line 746, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "c:\users\jan\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\instaloader.py", line 492, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "c:\users\jan\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\structures.py", line 236, in get_sidecar_nodes
    video_url=node['video_url'] if is_video else None)
KeyError: 'video_url'

The error doesn't state the post that is being parsed, but at the time the latest post was:
https://www.instagram.com/p/B-sKQ9zo5OZ/

**Comment by mipesom** [comment] 2020-04-24 10:58
No, it still breaks. (instaloader-4.3.2-1)

**Comment by aandergr** [comment] 2020-07-15 08:49
[Version 4.4.5rc1](https://github.com/instaloader/instaloader/releases/tag/v4.4.5rc1) includes a change of how post medata is accessed (#727). This might affect the here reported problem.

To upgrade:
```
pip3 install --upgrade --pre instaloader
```

**Comment by aandergr** [comment] 2020-07-21 14:24
Closing this, as it is likely fixed in [Version 4.4.5](https://github.com/instaloader/instaloader/releases/tag/v4.4.5). Please comment if the problem still occurs.

**Closed by aandergr** 2020-07-21 14:24 UTC
Labels: bug

**Comment by AhmadTariqAlflahat** [comment] 2020-08-02 14:08
I use this command `instaloader -- -B_K4CykAOtf --comments`
and it give me error about the entry_data

`Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ahmad\Desktop\Workspace\name_spinner\venv\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "c:\users\ahmad\desktop\workspace\name_spinner\venv\lib\site-packages\instaloader\__main__.py", line 429, in main
    _main(loader,
  File "c:\users\ahmad\desktop\workspace\name_spinner\venv\lib\site-packages\instaloader\__main__.py", line 153, in _main
    instaloader.download_post(Post.from_shortcode(instaloader.context, target[1:]), target)
  File "c:\users\ahmad\desktop\workspace\name_spinner\venv\lib\site-packages\instaloader\structures.py", line 83, in from_shortcode    
    post._node = post._full_metadata
  File "c:\users\ahmad\desktop\workspace\name_spinner\venv\lib\site-packages\instaloader\structures.py", line 161, in _full_metadata
    self._obtain_metadata()
  File "c:\users\ahmad\desktop\workspace\name_spinner\venv\lib\site-packages\instaloader\structures.py", line 153, in _obtain_metadata 
    + json.dumps(pic_json['entry_data'], indent=2))
KeyError: 'entry_data'`

**Comment by HamidrezaZMN** [comment] 2021-05-24 22:51
im using instaloader to make a telegram bot. i made it and tried it, it worked, but just randomly, about two hours later i retried and got this error:
...
File "C:\Users\hamid\Desktop\insta-exporter-bot\scripts\PureLink.py", line 54, in PureLink
    p = insta.Post.from_shortcode(loader.context, value)
  File "C:\Users\hamid\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\structures.py", line 83, in from_shortcode
    post._node = post._full_metadata
  File "C:\Users\hamid\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\structures.py", line 165, in _full_metadata
    self._obtain_metadata()
  File "C:\Users\hamid\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\structures.py", line 158, in _obtain_metadata
    raise BadResponseException("Fetching Post metadata failed.")
instaloader.exceptions.BadResponseException: Fetching Post metadata failed.


this doesn't happen for profiles (instaloader.Profile.from_username) and stories/highlights (instaloader.Post.from_mediaid)
packages versions:
instaloader==4.7.1
python-telegram-bot==13.1
