### ISSUE TITLE
Error on download

### ISSUE THREAD

**Issue by TheMNSTR** [instaloader/instaloader#1769] opened 2022-10-13 19:59 UTC
**Describe the bug**
I'm getting a following output on execute:
`Enter Instagram password for XXXXXXXXX:`
`Traceback (most recent call last):`
`  File "__main__.py", line 505, in <module>`
`  File "__main__.py", line 502, in __main`
`  File "__main__.py", line 471, in main`
`  File "__main__.py", line 121, in _main`
`  File "instaloader\instaloader.py", line 1572, in interactive_login`
`  File "instaloader\instaloader.py", line 634, in login`
`  File "instaloader\instaloadercontext.py", line 265, in login`
`  File "requests\cookies.py", line 328, in __getitem__`
`  File "requests\cookies.py", line 399, in _find_no_duplicates`
`KeyError: "name='csrftoken', domain=None, path=None"`
`[21136] Failed to execute script '__main__' due to unhandled exception!`

**To Reproduce**
Using following parameters:
`--fast-update --no-compress-json --no-captions --dirname-pattern posts\{profile}\ --filename-pattern {profile}_{date_utc}_UTC --login XXXXXXXXX :saved --abort-on 429`

**Expected behavior**
Download of all saved posts, with human readable jsons, not including captions. Posts expected to be saved in separate folders, named after source profiles. Photos should be named after source profile, and post timestamp. Immediate abort on HTTP 429 code expected.

**Instaloader version**
`4.9.5`

**Comment by Showmaster3000** [comment] 2022-10-13 20:35
Duplicate of #1758

**Closed** 2022-11-05 15:53 UTC
Labels: duplicate
