### ISSUE TITLE
[BUG] Instaloader no longer works after a few pictures

### ISSUE THREAD

**Issue by Niffecs** [instaloader/instaloader#1889] opened 2023-02-11 02:16 UTC
**Describe the bug**
Instaloader no longer works after a few pictures. You can restore your account via the Challange, but that does not solve the problem. Unfortunately, this pretty much breaks the application.

**To Reproduce**
```python
import instaloader

L = instaloader.Instaloader()
L.login(username,pwd)
profile = instaloader.Profile.from_username(L.context, username)
for post in profile.get_posts():
   L.post(post, target=profile.username)
```

**Expected behavior**
Instaloader downloads all things as planned

**Error messages and tracebacks**
```PowerShell
Traceback (most recent call last):
  File "C:\Nextcloud\code\insta.py", line 79, in <module>
    insta_user_download(L=instag(), username="xxx")
  File "C:\Nextcloud\code\insta.py", line 50, in insta_user_download
    L = instag()
        ^^^^^^^^
  File "C:\Nextcloud\code\insta.py", line 28, in instag
    L.login(get_insta_user()[0], get_insta_user()[1])
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 239, in login
    raise ConnectionException("Login: Checkpoint required. Point your browser to "
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXGm...d2dF/ - follow the instructions, then retry.
```

**Instaloader version**
Version: ``4.9.5``

**Additional context**

**Comment by Niffecs** [comment] 2023-02-11 02:17
The given Python code does what it is supposed to do. The problem is more with the app itself. Username and password are correct and belong to a normal account.

**Comment by Showmaster3000** [comment] 2023-02-11 13:00
Looks like duplicate of #1787.

**Comment by Niffecs** [comment] 2023-02-11 13:46
> Looks like duplicate of #1787.

Actually, it doesn't seem to be a duplicate of the issue you flagged. 
Even if it is a duplicate, it is a pity that there is no attempt to solve an old problem :'(

**Comment by Niffecs** [comment] 2023-02-12 02:37
@Showmaster3000 
Apparently the script works much better if you don't log in. However, I do not know why.

```python
import instaloader

# Create an instance of Instaloader
L = instaloader.Instaloader()

# Define the username of the public profile
username = "example_username"

# Download the public profile
profile = instaloader.Profile.from_username(L.context, username)

# Iterate through all the posts in the profile
for post in profile.get_posts():
    # Download the picture or video
    L.download_post(post, profile)

# Close the Instaloader session
L.context.session.close()
```

**Comment by Niffecs** [comment] 2023-02-12 14:09
```HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=xxx  to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
Redirected to login page. Use --login.```

**Comment by Showmaster3000** [comment] 2023-02-14 02:13
> ```shell
> Redirected to login page. Use --login.
> ```

The message is clear: you have to login to proceed. Anonymous access is very limited, usually the first 12 posts, but often less.

**Comment by Niffecs** [comment] 2023-02-19 19:04
As this and other issues show us, doing the Challanges doesn't help one bit. It is clear what it says, but it would be better if it said something that would solve the problem. 
Since this issue is unlikely to be resolved, I will close it. Maybe the problem will be fixed in a patch at some point. Then you could refer to the issue.

**Closed** 2023-02-19 19:04 UTC
Labels: bug

**Comment by ankit0183** [comment] 2023-03-29 16:54
can you please remove the login mechanism to download posts ? Anonymous access is very limited, can you increase more than 12 posts.. please
