### ISSUE TITLE
Some accounts are not downloadable due to bug telling no such account

### ISSUE THREAD

**Issue by sapphirepro** [instaloader/instaloader#1974] opened 2023-05-12 14:45 UTC
**Describe the bug**
Some accounts are not downloadable. For example https://www.instagram.com/melissariso/ . It wrongly says that there is no such user, while in fact it exists.

**To Reproduce**
Try to download that account https://www.instagram.com/melissariso/ . It will fail with error: "melissariso: Profile melissariso does not exist.

Errors or warnings occurred:
melissariso: Profile melissariso does not exist.
"

**Expected behavior**
Normally download all photos and videos.

**Error messages and tracebacks**
melissariso: Profile melissariso does not exist.

Errors or warnings occurred:
melissariso: Profile melissariso does not exist.

**Instaloader version**
4.9.6

**Additional context**

**Comment by Not4GoodBoyThou** [comment] 2023-05-13 16:01
Tried it on my machine. Works fine

`instaloader --login=<username> melissariso`

![snip](https://github.com/instaloader/instaloader/assets/78427384/9ee35eb9-dddd-4c84-a8ed-7a32fd3b2374)

**Comment by sapphirepro** [comment] 2023-05-14 07:31
I tried without --login and profile is public, so it should be downloading by logic

**Comment by Not4GoodBoyThou** [comment] 2023-05-14 15:23
I tried accessing this profile on my browser and it showed, 'to view profile I must be at least 18 years old'. Only way for me was to login and then it was working.  You can try this in incognito mode if you want. It will show as the _link is broken_, hence the  'profile not found' error.

**Comment by aandergr** [comment] 2023-05-27 07:14
Duplicate of #658

**Closed by aandergr** 2023-05-27 07:14 UTC
Labels: duplicate
