### ISSUE TITLE
HTTP error code 560???

### ISSUE THREAD

**Issue by afterdelight** [instaloader/instaloader#1639] opened 2022-07-15 23:08 UTC
**Describe the bug**
HTTP error code 560,  why is this???

**Error messages and tracebacks**
JSON Query to graphql/query: HTTP error code 560. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 560. [retrying; skip with ^C]
Download stories: JSON Query to graphql/query: HTTP error code 560.
Saved session to **************

**Instaloader version**
latest

**Comment by ryandtw** [comment] 2022-07-16 01:53
What are you trying to fetch? I've been having this issue over the past week! #1622

**Comment by Showmaster3000** [comment] 2022-07-16 09:27
duplicate of #1633.
besides too less information.

**Comment by afterdelight** [comment] 2022-07-17 00:06
its not a duplicate. error 560 is different with error 400

**Comment by MrJmpl3** [comment] 2022-07-17 04:01
To fix in my custom class (to override some functions of Instaloader), made this:

```
    @_requires_login
    def get_stories(self, userids: Optional[List[int]] = None) -> Iterator[Story]:
        if not userids:
            data = self.context.graphql_query("d15efd8c0c5b23f0ef71f18bf363c704",
                                              {"only_stories": True})["data"]["user"]
            if data is None:
                raise BadResponseException('Bad stories reel JSON.')
            userids = list(edge["node"]["id"] for edge in data["feed_reels_tray"]["edge_reels_tray_to_reel"]["edges"])

        def _userid_chunks():
            assert userids is not None
            userids_per_query = 1
            for i in range(0, len(userids), userids_per_query):
                yield userids[i:i + userids_per_query]

        for userid_chunk in _userid_chunks():
            try:
                stories = self.context.graphql_query("303a4ae99711322310f25250d988f3b7",
                                                 {"reel_ids": userid_chunk, "precomposed_overlay": False})["data"]
                yield from (Story(self.context, media) for media in stories['reels_media'])
            except ConnectionException:
                continue
```

Changes:

- userids_per_query from 50 to 1
- Ignore ConnectionException error

I think that increase the request to Instagram, but is the only way u.u

**Comment by afterdelight** [comment] 2022-07-17 19:24
can u explain more about 'Ignore ConnectionException error;

**Closed** 2022-07-23 17:10 UTC
Labels: no template

**Comment by raychenon** [comment] 2022-07-30 08:47
Same error

```
JSON Query to graphql/query: HTTP error code 560. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 560. [retrying; skip with ^C]
:stories: JSON Query to graphql/query: HTTP error code 560.
```

I use the following commands
```
instaloader --fast-update --filename-pattern={date_utc}_UTC_{profile} --dirname-pattern=target_{profile}  :stories --login=$account
```

instaloader version = 4.9.2

**Comment by afterdelight** [comment] 2022-07-31 04:39
have you try reduce userids_per_query from 50 to 5. it worked for me
