### ISSUE TITLE
TypeError on Post of with no video_url

### ISSUE THREAD

**Issue by kb1ibt** [instaloader/instaloader#2161] opened 2024-01-10 19:08 UTC
**Describe the bug**
I follow a couple of accounts that have had videos removed, but the post still exists. One example is post [CKkFMV0jFSF](https://www.instagram.com/p/CKkFMV0jFSF), where the video thumbnail still loads, but the actual video is no more. So when `posts_download_loop` (and thus `download_post`) try to get the post they fail with 
`TypeError: expected string or bytes-like object, got 'NoneType'`

**To Reproduce**
both from the Instaloader command line with not [--no-videos](https://instaloader.github.io/cli-options.html#cmdoption-no-videos) and the Instaloader Python module with `download_videos=True`
happens from the command line with the @ my account, directly the user's profile, and directly the post
happens via python via `download_profiles`, which calls `posts_download_loop`, and thus also `download_post`, also calling any of those later two individually

**Expected behavior**
The error to be caught probably best by an additional if statement in download_post around line [771](https://github.com/instaloader/instaloader/blob/baaa2c2998f019333d079572c97a5d32e0a0827d/instaloader/instaloader.py#L771)

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
```
  File "/opt/homebrew/lib/python3.12/site-packages/instaloader/instaloader.py", line 1064, in posts_download_loop
    downloaded = self.download_post(post, target=target)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/instaloader/instaloader.py", line 773, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/instaloader/instaloader.py", line 340, in download_pic
    urlmatch = re.search('\\.[a-z0-9]*\\?', url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/re/__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

**Instaloader version**
`instaloader --version` output.
4.10.2

**Comment by 0nobody0** [comment] 2024-05-14 18:58
also having this (or a similar) issue using instaloader 4.11 on windows 11 x64. this is when trying to download saved posts.

`instaloader --login=[username] :saved --slide 1 --no-compress-json`

a large number of posts downloaded successfully, but then this came up:

```
[4811/7291] ：saved\YYYY-MM-DD_TT-TT-TT_UTC.jpg exists [Title…] unchanged Unable to fetch high-quality video version of <Post [Shortcode]>: 400 Bad Request
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\instaloader\__main__.py", line 541, in main
    _main(loader,
  File "C:\Python312\Lib\site-packages\instaloader\__main__.py", line 241, in _main
    instaloader.download_saved_posts(fast_update=fast_update, max_count=max_count,
  File "C:\Python312\Lib\site-packages\instaloader\instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\instaloader\instaloader.py", line 1139, in download_saved_posts
    self.posts_download_loop(node_iterator, ":saved",
  File "C:\Python312\Lib\site-packages\instaloader\instaloader.py", line 1070, in posts_download_loop
    downloaded = self.download_post(post, target=target)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\instaloader\instaloader.py", line 773, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\instaloader\instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\instaloader\instaloader.py", line 340, in download_pic
    urlmatch = re.search('\\.[a-z0-9]*\\?', url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\re\__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

**Comment by aandergr** [comment] 2024-11-28 08:01
Duplicate of #2061

**Closed by aandergr** 2024-11-28 08:01 UTC
Labels: duplicate
