### ISSUE TITLE
BUG: get_posts() is not working

### ISSUE THREAD

**Issue by mdjadu** [instaloader/instaloader#2329] opened 2024-08-03 21:33 UTC
**Describe the bug**
Unable to iterate through `NodeIterator` returned by the `get_posts()` function

**Brief Description of the bug**
After loading the Profile, we run `get_posts()` function to obtain the posts:
`posts = profile.get_posts()`
When we try to iterate the posts using `for` loop
`for post in posts`
its not entering the `for` loop

**To Reproduce**
`profile = instaloader.Profile.from_username(L.context, username)` 
`posts = profile.get_posts()`
`for post in posts:`
 `     print(post.shortcode)`

**Expected behavior**
it should enter in the `for` loop and print all the `shortcode` for that profile

**Error messages and tracebacks**
No error message shown

**Instaloader version**
tried with both new and old Instaloader versions

**Comment by ekalin** [comment] 2024-08-03 21:34
Duplicate of #2319

**Closed** 2024-08-09 22:17 UTC
Labels: duplicate
