### ISSUE TITLE
Download only last 10 posts

### ISSUE THREAD

**Issue by rabe398** [instaloader/instaloader#327] opened 2019-06-10 23:37 UTC
**Provide us a use case of the feature**
Is it possible to add a feature to only download last 10 posts instead of all posts? 

**Describe the solution you'd like**
To add an argument to enable downloading x last posts.

The reason I want this, is because i'm scraping large list of users, and I only want to download the newest posts. This would help limit API calls

**Comment by aandergr** [comment] 2019-06-11 08:03
Duplicate of #141.

**Closed by aandergr** 2019-06-11 08:03 UTC

**Comment by rabe398** [comment] 2019-06-11 23:45
@aandergr I'm not sure how to do this correctly, since I have no coding experience in python.
Could please guide me how to do it correctly ?
