### ISSUE TITLE
Getting -1 likes as a like value

### ISSUE THREAD

**Issue by ADavis11** [instaloader/instaloader#2109] opened 2023-11-17 02:38 UTC
**Describe the bug**
On some posts maybe when the likes are too high it just returns -1
**To Reproduce**
make a call to get the likes of these posts:
Czlc_1KqPMq
CzlwTdbt6pB

(e.g. Instaloader command line)

**Expected behavior**
Return the exact amount of likes of the post

**Instaloader version**
`instaloader --version` output.
4.10.1

**Additional context**
my code:
import instaloader

def get_post_likes(post_id):
    L = instaloader.Instaloader()

    # Load the post using the post ID
    post = instaloader.Post.from_shortcode(L.context, post_id)

    # Get the number of likes for the post
    likes = post.likes

    # Print the number of likes
    print(f"Post likes: {likes}")

# Example usage
post_id = input("Enter the post ID: ")
get_post_likes(post_id)

**Comment by ADavis11** [comment] 2023-11-17 03:28
Okay I actually looked more at the posts I was trying to put and I think it is because those users set it so only they can see their likes

**Comment by aandergr** [comment] 2024-05-18 14:41
Duplicate of #1314

**Closed by aandergr** 2024-05-18 14:41 UTC
Labels: duplicate
