### ISSUE TITLE
Need to log in to scrape anything

### ISSUE THREAD

**Issue by dorokkkk** [instaloader/instaloader#883] opened 2020-11-19 19:38 UTC
Since a few days I have been getting a new issue saying I need to login to use any Instaloader functions (I have been mainly scraping comments from pre-chosen posts). I always get the error "429 Too Many Requests: redirected to login". Even if I limit the amount of comments I am scraping I get this issue. Four days ago my code was working fine. But overnight I started getting this error. This also happens with other IP-addresses, so it's not because of a blocked IP-address. 
Did anyone else experience this? I was wondering if Instagram changed something in their API to require everyone to login or if this is a bug?

**Comment by marty90** [comment] 2020-11-21 09:55
+1

**Comment by andreybondarb** [comment] 2020-11-24 13:31
The same issue. Seems like Instagram changed something in their policy. Need an update for the library!

**Comment by aandergr** [comment] 2020-11-28 16:46
> Did anyone else experience this? I was wondering if Instagram changed something in their API to require everyone to login or if this is a bug?

When accessing a hashtag or profile in the Instagram web app, scrolling down to get more than the few latest posts is very soon interrupted by a popup "Log in to continue". This popup also appears when clicking on a post.

It is not a bug that Instaloader cannot access data that is not accessible.

**Comment by aandergr** [comment] 2020-12-04 13:07
Whereas we most probably cannot do anything about login being required to access that data, Instaloader handled that redirect response from Instagram badly. This is fixed in version 4.5.5.

**Closed** 2020-12-04 13:07 UTC
Labels: bug
