### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 401.

### ISSUE THREAD

**Issue by ismatBabirli** [instaloader/instaloader#2002] opened 2023-06-08 16:20 UTC
I am getting the error on the Ubuntu server. But it is working on the local machine.
`JSON Query to graphql/query: HTTP error code 401.`

**Comment by GarethFreeman** [comment] 2023-06-09 02:56
Having the same problem, it seems to be triggered by the login function, works fine on public accounts.

**Comment by ismatBabirli** [comment] 2023-06-09 07:56
@GarethFreeman But I am trying to download a public video. I think it is related to the server or smth

**Comment by aandergr** [comment] 2023-06-26 05:50
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.

**Closed by aandergr** 2023-06-26 05:50 UTC
Labels: duplicate
