### ISSUE TITLE
Download specific save collection instead of all saved posts

### ISSUE THREAD

**Issue by H4xX0r1337** [instaloader/instaloader#1334] opened 2021-11-11 19:23 UTC
**Provide us a use case of the feature**
You could easily add all posts you want to save to a collection and download it later on pc.

**Describe the solution you'd like**
It should do the same thing as :saved but instead download a specific collection. I'd suggest name_of_collection:saved as syntax.

**Describe alternatives you've considered**
How do you achieve the here-described goal without the feature you are requesting?

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes / No
No

**Additional context**

**Comment by aandergr** [comment] 2021-11-13 13:33
Duplicate of #544

**Closed by aandergr** 2021-11-13 13:33 UTC
Labels: duplicate
