### ISSUE TITLE
Login error: 400 Bad Request

### ISSUE THREAD

**Issue by nihelmasell** [instaloader/instaloader#189] opened 2018-10-12 03:17 UTC
**Describe the bug**
Cant pass login to instagram

**To Reproduce**
instaloader --comments --geotags --stories --highlights --tagged --fast-update --login MYLOGIN profile SOMEBODYSPROFILE

**Expected behavior**
Download somebody´s profile highlight or my own saved posts. etc

**Error messages and tracebacks**
Fatal error: Login error: 400 Bad Request

**Instaloader version**
4.1.1

**Additional context**
When I try to login, instagram´s website ask if it was me, I confirm again and again, but it still happens. I also tried login in out from my phone´s app. I tried reinstalling the app by pip3 too. I checked in reddit and saw other people can login. I am on MacOS

**Comment by aandergr** [comment] 2018-10-14 10:08
Duplicate of #92.

This is our oldest bug. Unfortunately, it never happened to me and I can login just fine, making it hard for me to fix it. However, we are open for any suggestions. For fixing it, we would monitor the traffic between a browser and Instagram during logging in, for which Google Chrome has a great tool which opens when pressing F12, and compare it with what Instaloader does in its InstaloaderContext.login() method.

A workaround may be to use a new account for Instaloading, hoping it is not affected by this problem.

**Closed by aandergr** 2018-10-14 10:08 UTC

**Comment by nihelmasell** [comment] 2018-10-15 09:14
If this is useful for another user: I selected a location from ExpressVPN (a place in the US, country where I don't live) and MAGICALLY it works!! The weirdest stuff is that I don't live there nor visited I the country in the last years. Unundertandable stuff, but hopefully It can help someone with the same problem and "starting" conditions. Blackhatforums have infinite threads about this, none of which arrives to a final conclusion. Thanks!
