### ISSUE TITLE
When downloading it dosent get very far. any idea why?

### ISSUE THREAD

**Issue by MMJv3** [instaloader/instaloader#1644] opened 2022-07-18 17:16 UTC
Your question here...
![image](https://user-images.githubusercontent.com/36246145/179566604-7bc0a3d3-2862-402e-8ae5-57ba4625d77e.png)

**Comment by Showmaster3000** [comment] 2022-07-18 19:31
and also duplicate of #1617 or #1514 or others.

**Closed by Showmaster3000** 2022-07-18 19:31 UTC
Labels: duplicate, no template
