### ISSUE TITLE
Find stories that have a specific user tagged in them.

### ISSUE THREAD

**Issue by justemptywords** [instaloader/instaloader#720] opened 2020-07-07 10:52 UTC
It seems like my question isn't covered in the documentation.

How can I find stories that have a specific user tagged in them?

Let's say I want instaloader to go through every user's story that follows the user "x" and tell me which story had "x" tagged in them. How would I do that?

**Comment by Thammus** [comment] 2020-07-11 12:06
Achieving this goal would require to access the tappable objects which is not yet supported. This feature has been suggested in #586.

**Comment by justemptywords** [comment] 2020-07-13 13:52
@Thammus Excuse me? If a user is mentioned in a story then the `.json` file will contain a line with `Tappable objects` which lists the names of all users mentioned in them. Why not write a code that will basically grab all that data and implement it as an argument for `instaloader` ?

**Comment by Thammus** [comment] 2020-07-18 14:10
Supporting tappable objects can be implemented using the information in the json data like you describe. Feel free to implement it and create a pull request.

Closing this as duplicate of #586.

**Closed by Thammus** 2020-07-18 14:10 UTC
Labels: question
