### ISSUE TITLE
Support downloading personal collections

### ISSUE THREAD

**Issue by weiweihuanghuang** [instaloader/instaloader#1733] opened 2022-09-08 00:40 UTC
**Provide us a use case of the feature**
Download collections.

**Describe the solution you'd like**
`instaloader collection [collection ...]`

**Describe alternatives you've considered**

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Additional context**
This would be very useful, there's no tool capable right now of downloading collections.

**Comment by aandergr** [comment] 2022-10-15 14:30
Duplicate of #544

**Closed by aandergr** 2022-10-15 14:30 UTC
Labels: duplicate
