### ISSUE TITLE
HTTP redirect from https://www.instagram.com/username/ to https://www.instagram.com/accounts/login/

### ISSUE THREAD

**Issue by goker67** [instaloader/instaloader#390] opened 2019-08-23 07:13 UTC
When I attempt to scrape who have username such as "username" I see a message like
"HTTP redirect from https://www.instagram.com/username/ to https://www.instagram.com/accounts/login/" and nothing happens.
What is this exactly and how can I fix it?

**Comment by corpone** [comment] 2019-08-23 07:19
@goker67 Duplicate of https://github.com/instaloader/instaloader/issues/388

**Comment by goker67** [comment] 2019-08-23 09:55
When rate limit exceeded, how long does it take? How I long should I wait before another scraping attempt?

**Comment by aandergr** [comment] 2019-09-12 06:29
Duplicate of #388.

**Closed by aandergr** 2019-09-12 06:29 UTC
Labels: question
