### ISSUE TITLE
Custom sleep timer between requests.

### ISSUE THREAD

**Issue by calvinthefreak** [instaloader/instaloader#1220] opened 2021-07-03 22:12 UTC
**Provide us a use case of the feature**
How could the user invoke the new function? Which problem would it solve? If new information is obtained, how would it be further processed?

If you append an argument like --request-limit = seconds (between doing another request)

The Problem is, that I am once upon a time (about each 3 Months) will backup all my followers posts. Instagram hates me and throws a lot of 429 if I do this. The reason for this is just the plain massive count of requests I am going to make.

**Describe the solution you'd like**

Introduce an option, where you can define an custom time to wait between requests to the API and the Image-CDN.

**Describe alternatives you've considered**

Currently I am doing this by limiting the recources (56k download speed) to the LXC container, but not quite working well, still getting a lot of 429.

**If the feature request is accepted, would you be willing to submit a pull request?**
No - I am not good at Python, but can help in the topic of Bash.

**Additional context**
Add any other context about the feature request here.

**Comment by calvinthefreak** [comment] 2021-07-03 22:14
To add to this, I am using the script via Bash, so no fancy Python implementation, I am relying on the cli arguments, that Instaloader has.

**Comment by calvinthefreak** [comment] 2021-07-04 09:30
related to #1218

**Comment by Thammus** [comment] 2021-07-13 17:16
Duplicate of #1006.

**Closed by Thammus** 2021-07-13 17:16 UTC
Labels: duplicate
