### ISSUE TITLE
Issue 401 by Ubuntu Server 

### ISSUE THREAD

**Issue by PandorasBoxTool** [instaloader/instaloader#1983] opened 2023-05-20 09:39 UTC
I have already tried with an Amazon AWS EC2 server and also with an IONOS dedicated root server no matter what I do I get the error code 401 but if I also install VirtualBox Ubuntu Server it works therefore the question what is the reason or which server or provider I can use best?

**Comment by aandergr** [comment] 2023-06-26 05:50
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.

**Closed by aandergr** 2023-06-26 05:50 UTC
Labels: duplicate
