### ISSUE TITLE
Whats the limit of the comment scraping

### ISSUE THREAD

**Issue by jingwuk** [instaloader/instaloader#590] opened 2020-05-01 04:52 UTC
What is exactly the limit of comments scraping? 
is there any way that i can get all of them? Do i need `do_sleep()` to get all of them?
Because the data i get is not the same ammount as the comments from that instagram account

Im trying to scrape comments from 5 post of a specific account (famous account).
Im collecting the data to make a dataset.

**Comment by e5150** [comment] 2020-05-01 09:49
Are you getting error 429? Otherwise you shouldn't need to add more sleeps. And with `Post.get_comments()` you should be getting all available comments. What does your code look like?

**Comment by jingwuk** [comment] 2020-05-02 07:54
i got no error, its just that the data i scrape didnt have the same ammount as the comments on the instagram post.

**Comment by Thammus** [comment] 2020-05-02 07:54
Duplicate of #460.

**Closed** 2020-05-02 07:54 UTC
Labels: duplicate
