### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 400.

### ISSUE THREAD

**Issue by Showmaster3000** [instaloader/instaloader#99] opened 2018-04-18 00:57 UTC
Currently get the following error during updating profiles. It worked about 15 hours ago.
The error seems to be in updating the normal elements. --stories-only works fine. The images in the sample down below are also saved before, so --fast-update doesn't work in current case.
Tried both v3.3.7 and new 3.3.8.

```
instaloader.exe --only-if="date_utc.year>2017" --fast-update --comments --metadata-json --geotags --stories --login=mynickname --filename-pattern={date} username
Only download posts with property "date_utc.year>2017".
Loaded session from c:\users\xxx\appdata\local\temp/.instaloader-xxx/session-mynickname.
Logged in as mynickname.
username/2018-04-14_21-41-06_UTC_profile_pic.jpg already exists
Retrieving stories from profile username.
Retrieving posts from profile username.
[  1/ 56] username/2018-04-12_10-41-25_UTC.jpg exists [desc-cut] unchanged JSON Query to graphql/query: HTTP error code 400. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 400. [retrying; skip with ^C]
Download profile username: JSON Query to graphql/query: HTTP error code 400.
[  2/ 56] username/2018-03-24_12-41-53_UTC.jpg exists [desc-cut] unchanged
Interrupted by user.
Saved session to c:\users\xxx\appdata\local\temp/.instaloader-xxx/session-mynickname.

Errors occured:
Download profile username: JSON Query to graphql/query: HTTP error code 400.
```

**Comment by MatthieuBonenfant** [comment] 2018-04-18 03:43
same here, my hashtags have been going but not user profiles they stop after 12 images or so giving same error as above

`C:\python\Scripts>c:\python\scripts\instaloader universalcollectibles04 --fast-update --filename-pattern={profile}_{date} --no-captions
Stored ID 5807458749 for profile universalcollectibles04.
universalcollectibles04/2017-10-08_18-17-14_UTC_profile_pic.jpg
Retrieving posts from profile universalcollectibles04.
[  1/1404] universalcollectibles04/universalcollectibles04_2018-04-17_20-28-34_UTC.jpg
[  2/1404] universalcollectibles04/universalcollectibles04_2018-04-17_20-20-35_UTC.jpg
[  3/1404] universalcollectibles04/universalcollectibles04_2018-04-17_20-15-18_UTC.jpg
[  4/1404] universalcollectibles04/universalcollectibles04_2018-04-17_19-54-13_UTC.jpg
[  5/1404] universalcollectibles04/universalcollectibles04_2018-04-11_22-57-43_UTC.jpg
[  6/1404] universalcollectibles04/universalcollectibles04_2018-03-25_23-08-09_UTC.jpg
[  7/1404] universalcollectibles04/universalcollectibles04_2018-03-25_22-54-00_UTC.jpg
[  8/1404] universalcollectibles04/universalcollectibles04_2018-03-25_04-11-26_UTC.jpg
[  9/1404] universalcollectibles04/universalcollectibles04_2018-03-25_04-05-52_UTC.jpg
[ 10/1404] universalcollectibles04/universalcollectibles04_2018-03-25_03-58-36_UTC.jpg
[ 11/1404] universalcollectibles04/universalcollectibles04_2018-03-25_03-35-50_UTC.jpg
[ 12/1404] universalcollectibles04/universalcollectibles04_2018-03-25_03-26-30_UTC.jpg
JSON Query to graphql/query: HTTP error code 400. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 400. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 400.
`

**Comment by MatthieuBonenfant** [comment] 2018-04-18 03:53
Hey I tried to save a user account images using jdownloader and it stopped after 12 images as well!

**Comment by aandergr** [comment] 2018-04-18 06:12
Duplicate of #94

**Closed by aandergr** 2018-04-18 06:12 UTC
