### ISSUE TITLE
Trying to download tagged posts fails if you are not pass login information

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#1810] opened 2022-11-17 20:13 UTC
Trying to download tagged posts fails if you are not passing login information.
This is weird because normal posts can be downloaded without to pass login info. 
To some profiles, it fails almost at start and in some other profiles fails after downloading eg. 20 posts.
This behaviour is observed either to  days without any other use of instaloader on insta. 
Try to download any tagged post, after a few one eg. 20-30, it fails everytime.  with the below error

(Linux, bullseye 11, kde) 
```

......
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Warning: Unable to fetch video from graphql of <Post Ch2wM4SDNaU>: JSON Query to graphql/query: HTTP error code 401.
Traceback (most recent call last):
  File "/home/elias/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/__main__.py", line 220, in _main
    instaloader.download_profiles(profiles,
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/instaloader.py", line 1449, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter,
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/instaloader.py", line 1247, in download_tagged
    self.posts_download_loop(tagged_posts,
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/instaloader.py", line 1047, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/instaloader.py", line 756, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg/instaloader/instaloader.py", line 340, in download_pic
    urlmatch = re.search('\\.[a-z0-9]*\\?', url)
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by estatistics** [comment] 2022-11-17 20:16
If u asked, i can provide you with some public profiles, and what happens.

**Comment by aandergr** [comment] 2022-12-23 15:39
Duplicate of #1802

**Closed by aandergr** 2022-12-23 15:39 UTC
Labels: bug
