### ISSUE TITLE
Cant find user

### ISSUE THREAD

**Issue by JosiMou** [instaloader/instaloader#301] opened 2019-05-17 00:43 UTC
**Describe the bug**
Somehow I get the error that the acc doesn't exist although it does (I have scraped it before).

**Error messages and tracebacks**
/Users//.virtualenvs/ThesisObjectDetection/bin/python /Users//Documents/GitHub/RedDotPRJ_1/imageAnalyzer.py
Traceback (most recent call last):
  File "/Users//.virtualenvs/ThesisObjectDetection/lib/python3.6/site-packages/instaloader/structures.py", line 520, in _obtain_metadata
    self._rhx_gis = metadata['rhx_gis']
KeyError: 'rhx_gis'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users//Documents/GitHub/RedDotPRJ_1/imageAnalyzer.py", line 4, in <module>
    from InstagramScraper.instascraper import *
  File "/Users//Documents/GitHub//InstagramScraper/instascraper.py", line 65, in <module>
    profile = Profile.from_username(L.context, USERNAME)
  File "/Users/josefmoucachen/.virtualenvs/ThesisObjectDetection/lib/python3.6/site-packages/instaloader/structures.py", line 475, in from_username
    profile._obtain_metadata()  # to raise ProfileNotExistException now in case username is invalid
  File "/Users//.virtualenvs/ThesisObjectDetection/lib/python3.6/site-packages/instaloader/structures.py", line 522, in _obtain_metadata
    raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username)) from err
instaloader.exceptions.ProfileNotExistsException: Profile josefmoucachen does not exist.

**Instaloader version**
4.2.6
**Additional context**

**Comment by ralfschramm** [comment] 2019-05-17 05:30
similar here:

instaloader --login clickchecker -f insta.session
[Errno 2] No such file or directory: 'insta.session'
Session file does not exist yet - Logging in.
Enter Instagram password for clickchecker: 
Enter 2FA verification code: xxxxxx
Logged in as clickchecker.
Saved session to insta.session.
No targets were specified, thus nothing has been downloaded.


instaloader clickchecker -f insta.session 
clickchecker: Profile clickchecker does not exist.

Errors occured:
clickchecker: Profile clickchecker does not exist.


The profile exists for sure :-)

**Comment by aandergr** [comment] 2019-05-17 05:55
Duplicate of #297.

**Closed by aandergr** 2019-05-17 05:55 UTC
