### ISSUE TITLE
brokey

### ISSUE THREAD

**Issue by ZellsAlpha** [instaloader/instaloader#1553] opened 2022-05-31 17:38 UTC
**Describe the bug**
JSON Query to test/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

**To Reproduce**
Steps to reproduce the behavior: just download anyone

**Expected behavior**
its supposed to work

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
Errors or warnings occurred:
Profile test has changed its name to test.
Warning: test will be downloaded anonymously ("Profile test does not exist.
The most similar profile is: test.")

**Comment by RuzgarErik** [comment] 2022-05-31 19:12
I tried an another account of mine and it downloaded, without a problem. It's probably a measure to preventing bot accounts

**Comment by quietsecret123** [comment] 2022-05-31 19:23
They blocked 2 of my accounts a few weeks ago then I retried them today. They seem to be working again, so it appears to be a temporary measure (for now)

**Comment by AnonC0DER** [comment] 2022-05-31 19:59
Same problem here, I got "Could not find "window._sharedData" in html response." error.
I tried 10 accounts, none of them worked. It seems something has changed in Instagram sessions.
Has anybody found any solution?

**Comment by ekalin** [comment] 2022-05-31 20:07
The workaround is to remove the session file (`session-USERNAME` in the config directory, or whichever file you specify in the command-line) and force a login every time instaloder runs. Not great, but it seems to work.

**Comment by Showmaster3000** [comment] 2022-05-31 20:33
The problem is also discussed in #1530.

**Comment by MrC0D3** [comment] 2022-06-01 01:43
Also discussed in https://github.com/instaloader/instaloader/issues/1523

**Comment by daddancer** [comment] 2022-06-01 08:13
This is what you get back when trying to get stories with a "broken" account:
[storyresponse.zip](https://github.com/instaloader/instaloader/files/8812330/storyresponse.zip)

**Comment by daddancer** [comment] 2022-06-01 11:26
This is what you get as a response for "good" (i.e. log in with fresh session and grab stories immediately) vs "bad" (i.e. use existing session, even for a few seconds before):
[stories.zip](https://github.com/instaloader/instaloader/files/8813592/stories.zip)

**Comment by jbrre** [comment] 2022-06-01 11:26
> The workaround is to remove the session file (`session-USERNAME` in the config directory, or whichever file you specify in the command-line) and force a login every time instaloder runs. Not great, but it seems to work.

Works but got banned within 2 times of using this workaround, be careful guys😢

**Comment by quietsecret123** [comment] 2022-06-02 06:45
I decided to download 4KStogram again, which forced me to login to an account to download stories. I logged in as one of my blocked accounts, and the app was surprisingly able to download the stories, so there is definitely a workaround.

**Comment by ziemek99** [comment] 2022-06-02 08:23
> > The workaround is to remove the session file (`session-USERNAME` in the config directory, or whichever file you specify in the command-line) and force a login every time instaloder runs. Not great, but it seems to work.
> 
> Works but got banned within 2 times of using this workaround, be careful guys😢

What do you mean exactly by "banned"?

**Comment by thariq-nugrohotomo** [comment] 2022-06-02 11:00
Is it possible to edit this issue title, as currently it's not mentioning what the actual issues are?
Other closed issue's title is more representative, e.g. `error Could not find "window._sharedData" in html response`

**Comment by jbrre** [comment] 2022-06-02 11:14
> > > The workaround is to remove the session file (`session-USERNAME` in the config directory, or whichever file you specify in the command-line) and force a login every time instaloder runs. Not great, but it seems to work.
> > 
> > 
> > Works but got banned within 2 times of using this workaround, be careful guys😢
> 
> What do you mean exactly by "banned"? Banned just from scraping (you can still log in), banned temporarily (you can't react to content) or banned completely (removed)?

Just got a softban, I had to reinitialize my password by SMS and got access to my account again

**Comment by fireattack** [comment] 2022-06-02 11:15
Excessive logins have always get your account ban or locked so it's not specific to that workaround. But yeah, be aware.

**Comment by nns33213** [comment] 2022-06-02 13:04
@ekalin @fireattack @jbrre this is not a real workaround, just a coincidence due to the way Instagram releases patches.

I'd advise not to burn your accounts and just wait for a real fix. This "workaround" will stop working completely within the next hours or days.

**Comment by Showmaster3000** [comment] 2022-06-02 13:17
> This is what you get as a response for "good" (i.e. log in with fresh session and grab stories immediately) vs "bad" (i.e. use existing session, even for a few seconds before): [stories.zip](https://github.com/instaloader/instaloader/files/8813592/stories.zip)

Just checked your files. The "bad" version doesn't have the `window._sharedData` in the code. Instead parts of the content is at another position near `XIGSharedData` but without the graphql-part...

**Comment by jbrre** [comment] 2022-06-02 15:15
> @ekalin @fireattack @jbrre this is not a real workaround, just a coincidence due to the way Instagram releases patches.
> 
> I'd advise not to burn your accounts and just wait for a real fix. This "workaround" will stop working completely within the next hours or days.

How "bad" is it? Like is it just an API update or is the good old login method completely broken?

**Comment by nns33213** [comment] 2022-06-02 15:30
> How "bad" is it? Like is it just an API update or is the good old login method completely broken?

@jbrre no, I don't think login is broken. From what I've seen working on patch for other project, yes, `window._sharedData` is gone. Most of the data can be found around `PolarisProfileRoot.react` from the "bad" response (not `XIGSharedData` which holds data for your own account) and also the endpoint for getting media info no longer works (not sure if InstaLoader uses it though).

**Comment by francescogrimaldi** [comment] 2022-06-02 17:43
I have noticed a new API endpoint: `i.instagram.com/api/v1/users/web_profile_info/?username={profile_name}`

**Comment by afterdelight** [comment] 2022-06-03 08:03
please change the title to be more specific, thanks

**Comment by AyluinReymaer** [comment] 2022-06-03 16:53
I also started having the same issue:


instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to test/feed/: Could not find "window._sharedData" in html response.,
instaloader.exceptions.ProfileNotExistsException: Profile test does not exist.

**Comment by tayfunyasar** [comment] 2022-06-03 21:51
entry_data is also empty if you check _sharedData. So are we going to give up? 😆

**Comment by UnixCro** [comment] 2022-06-03 23:23
Serious? You were able to build such a complex program but couldn't find any HTML errors?

**Comment by mitchcapper** [comment] 2022-06-04 02:56
@UnixCro and others  please remember that github issues are for reporting bugs and relevant information only.   Unless you are funding this project you also don't really have grounds to demand something is fixed in a certain timeframe.   The people who work on this software due so often on their own dime and own time, and work to resolve things per their own priorities.  Pull requests are available and open for the project, so a 3rd party can also fix it and submit a request.

The title of this bug is not descriptive, but opening a new issue is not the solution it should just be updated.  Anyone else who is just posting me too doesn't need to comment here, just thumbs up the first comment like others. This is clearly a known issue due to instagram changes, and a problem that virtually all libraries are running into.    

By all means if you have new relevant information to contribute great, but anything else just slows the process down and spams all the users subscribed to this issue.

**Comment by twitter-79** [comment] 2022-06-04 07:53
> I have noticed a new API endpoint `i.instagram.com/api/v1/users/web_profile_info/?username={profile_name}`

this was a good observation! It seems we can get the profile information as well as 50 posts from this link using the `get_iphone_json` method and just have to change the mapping to the new data structure.

I'm not that familiar with the internals of instaloader but will try to fix it at least to a certain extend and put up a pull request. Maybe someone else wants to help out, too?

**Comment by afterdelight** [comment] 2022-06-04 10:36
testing the pull request right now, looks good. will report later

**Comment by afterdelight** [comment] 2022-06-04 10:40
i got
```
Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Python\Python310\lib\site-packages\instaloader\__main__.py", line 471, in main
    _main(loader,
  File "C:\Python\Python310\lib\site-packages\instaloader\__main__.py", line 182, in _main
    profile = instaloader.check_profile_id(target, latest_stamps)
  File "C:\Python\Python310\lib\site-packages\instaloader\instaloader.py", line 1361, in check_profile_id
    latest_stamps.save_profile_id(profile.username, profile.userid)
  File "C:\Python\Python310\lib\site-packages\instaloader\structures.py", line 816, in username
    return self._metadata('username').lower()
  File "C:\Python\Python310\lib\site-packages\instaloader\structures.py", line 788, in _metadata
    d = d[key]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Dibort** [comment] 2022-06-04 10:43
That's because the profile returns `{'data': {'user': None}, 'status': 'ok'}` with the `get_iphone_json` method. Maybe your target profile doesn't exist?

I added this and seems to work fine, testing it now:

```
if metadata['data']['user'] is None:
    raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username))
```

**Comment by afterdelight** [comment] 2022-06-04 10:56
on what line i need to put those lines? thank you.

**Comment by Dibort** [comment] 2022-06-04 10:58
> on what line i need to put those lines? thank you.

Just before `self._node = metadata['data']['user']` in `structures.py` file

**Comment by afterdelight** [comment] 2022-06-04 11:08
ty, its working now. the pull request should have been updated with your fix.

**Comment by twitter-79** [comment] 2022-06-04 11:09
this is weird, for me trying a non-existing profile leads to various tries ending in a 404 and finally a keyerror on fetching similar profiles as the data only contains a username but no id.

Do you have a username that leads to an empty user field for me to try things out?

**Comment by Dibort** [comment] 2022-06-04 11:15
> Do you have a username that leads to an empty user field for me to try things out?

`noxandwillow` was a 404 but `oskar_blackbeard` not. Maybe something about users changing their profile names? I don't know.

**Comment by UnixCro** [comment] 2022-06-04 11:17
If I delete the sessionfile then download the download easily. So it works in itself institute instaloader, only as soon as the sessionfile is retrieved there is a problem there we have to look. What makes instaloader different?

**Comment by fireattack** [comment] 2022-06-04 11:19
> makes instaloader different

It's not different. It happens with webpage too. 

It looks like that Instagram just doesn't seem to send back the same response when you firstly login.

**Comment by twitter-79** [comment] 2022-06-04 11:21
> > Do you have a username that leads to an empty user field for me to try things out?
> 
> `noxandwillow` was a 404 but `oskar_blackbeard` not. Maybe something about users changing their profile names? I don't know.

this really is weird... I added your fix to the pull request. Thx for helping out!
I guess we can use the PR as a quick fix until someone else has time to do it correctly

**Comment by MiguelX413** [comment] 2022-06-05 01:03
It suddenly started working again for me.

**Comment by baris12333** [comment] 2022-06-05 04:47
@quietsecret123 Is the issue the same on Raider? I have been trying to rig Raider to work similarly to how Instaloader has been fixed in this thread but haven't had luck with the older packages it uses. Npm doesn't want to install them. Does Instaloader have a way it can read everything Ive downloaded from Raider so I don't have to re-download all the accounts from scratch to switch over to Instaloader?

**Comment by wolviey** [comment] 2022-06-05 08:57
patch worked for me thx.

**Comment by UnixCro** [comment] 2022-06-05 09:20
How I can install the patch via pip?

**Comment by jbrre** [comment] 2022-06-05 11:14
> How I can install the patch via pip?

Uninstall your old instaloder version.
Clone the patch repository.
Then go into the patch repo and `pip3 install -e .`

**Comment by AnonC0DER** [comment] 2022-06-05 11:19
What does patch repository mean?
How can clone it?

**Comment by jlntrt** [comment] 2022-06-05 11:20
Just use `pip3 install --upgrade --user git+https://github.com/twitter-79/instaloader`

**Comment by afterdelight** [comment] 2022-06-05 12:18
open cmd then write 'pip install https://github.com/twitter-79/instaloader/archive/refs/heads/master.zip --no-cache-dir'

**Comment by UnixCro** [comment] 2022-06-05 12:20
I think, it is the best to run this. 

```
pip install --force-reinstall -U git+https://github.com/instaloader/instaloader@refs/pull/1561/merge
```

**Comment by jiatern** [comment] 2022-06-05 12:53
> Just use `pip3 install --upgrade --user git+https://github.com/twitter-79/instaloader`

Tried this on my Ubuntu machine and it worked perfectly. UnixCro's method gave me an error.

**Comment by UnixCro** [comment] 2022-06-05 13:03
>@jiatern UnixCro's method gave me an error.

The Error is probably this `pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.` ...  It still works without any problems.

**Closed** 2022-06-08 16:12 UTC
Labels: bug

**Comment by brutalsuperman** [comment] 2022-07-07 09:20
> That's because the profile returns `{'data': {'user': None}, 'status': 'ok'}` with the `get_iphone_json` method. Maybe your target profile doesn't exist?
> 
> I added this and seems to work fine, testing it now:
> 
> ```
> if metadata['data']['user'] is None:
>     raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username))
> ```
> 
> It's still doing the "Similar profiles" method, but not with this json response. _Was just a quick fix for me because I needed it working._

What you can say about this profile? 
https://www.instagram.com/molsoncoors/

**Comment by axelmiami** [comment] 2022-09-10 20:05
Exactly the same problem:

```
$ instaloader --login=<username>
Session file does not exist yet - Logging in.
Enter Instagram password for p2i.berest:
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
```
help me please

Moreover, when launched locally from the IDE, everything connects and works, but on the server it gives an error.

All Python packages are the same and updated to the latest versions.

All of the above methods did not help.
Both the call from Python and the call in the console do not work on the server

**Comment by afterdelight** [comment] 2022-09-11 14:53
try uninstall then fresh install of instaloader
