### ISSUE TITLE
Not able to download profile

### ISSUE THREAD

**Issue by cocodedesigns** [instaloader/instaloader#1774] opened 2022-10-19 14:59 UTC
**Describe the bug**
I cannot backup an Instagram profile when logging in

**To Reproduce**
`instaloader --login=[USER] [PROFILE]`

**Expected behavior**
Instaloader should request a password (which it does) then process the profile and download the photos (which it doesn't)

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/3.9/site-packages/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "/Library/Python/3.9/site-packages/instaloader/__main__.py", line 121, in _main
    instaloader.interactive_login(username)
  File "/Library/Python/3.9/site-packages/instaloader/instaloader.py", line 1572, in interactive_login
    self.login(username, password)
  File "/Library/Python/3.9/site-packages/instaloader/instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "/Library/Python/3.9/site-packages/instaloader/instaloadercontext.py", line 265, in login
    session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Python/3.9/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/3.9/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='csrftoken', domain=None, path=None"
```

**Instaloader version**
Instaloader 4.9.5 on Mac OS Monterey 12.6

**Additional context**
Not sure if it is related, but another account has 2FA enabled, and a valid 2FA code from Google Authenticator is not accepted, but the same code is accepted on the website

**Comment by Showmaster3000** [comment] 2022-10-19 22:33
Did you see #1773, #1770, #1767. #1759 or #1758?
Duplicate of #1758

**Closed** 2022-10-19 22:33 UTC
Labels: bug
