### ISSUE TITLE
2FA code no longer valid

### ISSUE THREAD

**Issue by Oktoplus** [instaloader/instaloader#1939] opened 2023-04-03 23:25 UTC
If i try to login it asks for my 2fa code wich i give it but it says code to old while the same code still works to authenticate a browser session.
version 4.9.6 from pip
on Ubuntu based Linux x86_64
`Enter 2FA verification code: 015950
2FA error: This code is no longer valid. Please request a new one.
`
i cant login even if i disable totp based login and only use sms.

**Comment by aandergr** [comment] 2023-05-02 07:54
Duplicate of #1217

**Closed by aandergr** 2023-05-02 07:54 UTC
Labels: duplicate
