### ISSUE TITLE
KeyError: 'video_url'

### ISSUE THREAD

**Issue by beakwood** [instaloader/instaloader#605] opened 2020-05-08 02:38 UTC
**Describe the bug**

**To Reproduce**
instaloader -l xxxxx -p xxxxx +pinsta.txt --fast-update --no-profile-pic --no-captions --no-metadata-json --no-video-thumbnails --filename-pattern "{profile}_{mediaid}_{date_utc}"

**Expected behavior**
A clear and concise description of what you expected to happen (if not obvious).

**Error messages and tracebacks**
[  1/995] Traceback (most recent call last):
  File "c:\python\python38\lib\site-packages\instaloader\structures.py", line 157, in _field
    d = d[key]
KeyError: 'video_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python38\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.3.1', 'console_scripts', 'instaloader')()
  File "c:\python\python38\lib\site-packages\instaloader\__main__.py", line 412, in main
    _main(loader,
  File "c:\python\python38\lib\site-packages\instaloader\__main__.py", line 192, in _main
    instaloader.download_profiles(profiles,
  File "c:\python\python38\lib\site-packages\instaloader\instaloader.py", line 1106, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "c:\python\python38\lib\site-packages\instaloader\instaloader.py", line 517, in download_post
    downloaded &= self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local)
  File "c:\python\python38\lib\site-packages\instaloader\structures.py", line 294, in video_url
    return self._field('video_url')
  File "c:\python\python38\lib\site-packages\instaloader\structures.py", line 160, in _field
    d = self._full_metadata
  File "c:\python\python38\lib\site-packages\instaloader\structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "c:\python\python38\lib\site-packages\instaloader\structures.py", line 137, in _obtain_metadata
    if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable

**Instaloader version**
instaloader 4.3.1

**Additional context**
If I download that same profile without being logged in. It works...

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by aandergr** [comment] 2020-05-08 09:29
Duplicate of #449.

**Closed by aandergr** 2020-05-08 09:29 UTC
Labels: bug
