### ISSUE TITLE
Select location for session_file

### ISSUE THREAD

**Issue by KeronmaN** [instaloader/instaloader#1375] opened 2022-01-04 04:44 UTC
I know that there is option to read session_file from non-default destination but I coudn't manage to find anything about option for changing session file folder. 

Is there any option to save_session_to_file to specyfic/new folder? I would like to use interactive_login, and then save it to a new one.

**Comment by UnixCro** [comment] 2022-01-04 05:22
Duplicate of https://github.com/instaloader/instaloader/issues/928

Thank you

**Closed** 2022-01-07 14:47 UTC
Labels: invalid
