### ISSUE TITLE
Login error: Json decode fail, 403 - Forbidden

### ISSUE THREAD

**Issue by alistvt** [instaloader/instaloader#1153] opened 2021-05-28 10:39 UTC
**Describe the bug**
Hello guys. When I try to login into an Instagram account I got the following error. I have tried all different ways to login and none of them works, except logging in with my own computer and then exporting my firefox cookies file to the server and create the session using that file. Only this works. 
Although I have dozens of accounts working on the same server, I think the problem should not be related to the server's IP, since I have tried logging in to those accounts with the same IP and Instagram didn't give me such an error, neither through the native app, nor through the browser! 
So I cannot find out why am I getting such an error and how should I deal with it. 

**Expected behavior**
Should be able login using username and password, both through the command line and through the python.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "/root/env/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/root/env/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/root/env/lib/python3.8/site-packages/telegram/ext/handler.py", line 167, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)  # type: ignore
  File "teleg.py", line 283, in __init__
    self.run()
  File "teleg.py", line 321, in run
    insta.insta_handler.try_login(username, password)
  File "/root/instasave/insta.py", line 144, in try_login
    L.login(username, password)
  File "/root/env/lib/python3.8/site-packages/instaloader/instaloader.py", line 550, in login
    self.context.login(user, passwd)
  File "/root/env/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 226, in login
    raise ConnectionException(
instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 403 - Forbidden.

```

**Instaloader version**
4.7.1

**Comment by Showmaster3000** [comment] 2021-05-28 23:24
Duplicate of #1150

**Closed by Showmaster3000** 2021-05-28 23:24 UTC
Labels: bug
