### ISSUE TITLE
Highlights make the script retrieve errors

### ISSUE THREAD

**Issue by Muggeren** [instaloader/instaloader#1728] opened 2022-09-06 08:35 UTC
**Describe the bug**
It retrieves an error

**To Reproduce**
"./instaloader --login=USER --highlights --no-video-thumbnails --no-posts TARGET"

**Expected behavior**
To download all highlights from target

**Error messages and tracebacks**

[  5/ 49] Warning: Unable to fetch video from graphql of <StoryItem 2771602286366031741>: list index out of range
Unable to fetch high-quality video version of <StoryItem 2771602286366031741>: 'video_versions'
Traceback (most recent call last):
  File "__main__.py", line 505, in <module>
  File "__main__.py", line 502, in __main
  File "__main__.py", line 471, in main
  File "__main__.py", line 220, in _main
  File "instaloader\instaloader.py", line 1456, in download_profiles
  File "instaloader\instaloader.py", line 81, in call
  File "instaloader\instaloader.py", line 960, in download_highlights
  File "instaloader\instaloader.py", line 887, in download_storyitem
  File "instaloader\instaloader.py", line 97, in call
  File "instaloader\instaloader.py", line 340, in download_pic
  File "re.py", line 201, in search
TypeError: expected string or bytes-like object
[23852] Failed to execute script '__main__' due to unhandled exception!

**Instaloader version**
4.9.3

**Additional context**
Everytime i use the +args feature, the script seems to crash too.

**Comment by Showmaster3000** [comment] 2022-09-06 11:24
Duplicate of #1718.
And same thing like in #1460. But this issue is closed and looks unfixed...

**Comment by fireattack** [comment] 2022-09-07 11:07
So here is how it happens.

In the highlight (https://www.instagram.com/stories/highlights/17962767154067076/), there is one story (fifth last, the one said "sideline work" that is a `StoryItem` with `.is_video == True`, but it doesn't actually have a video_url in neither graphql and iPhone API. You can see that if you open it in browser too, it just has a still image, no video or whatsoever.

We currently don't handle this case well: we assume we will always at least got the video_url from graphql. `StoryItem.video_url` *can* return `None` without erroring out, but `Instaloader.download_pic()` don't properly handle `url=None`).

I'm trying to come up with a fix, but not exactly sure what is the best way to do it.

**Comment by Muggeren** [comment] 2022-09-07 11:23
Ah okay. Thanks for answering the post, and the knowledge  (:

**Comment by aandergr** [comment] 2022-10-15 14:26
Fixed in version 4.9.4.

**Closed by aandergr** 2022-10-15 14:26 UTC
Labels: bug
