### ISSUE TITLE
key Error: 'graphql'

### ISSUE THREAD

**Issue by corori8899** [instaloader/instaloader#1169] opened 2021-06-04 17:34 UTC
**Describe the bug**
I can't scrap Instagram post by hashtag
**To Reproduce**
posts = instaloader.Hashtag.from_name(L.context, "patagonia").get_posts()

SINCE = datetime(2018, 5, 10)  # further from today, inclusive
UNTIL = datetime(2018, 12, 1)  # closer to today, not inclusive

k = 0  # initiate k
#k_list = []  # uncomment this to tune k

for post in posts:
    postdate = post.date

    if postdate > UNTIL:
        continue
    elif postdate <= SINCE:
        k += 1
        if k == 50:
            break
        else:
            continue
    else:
        L.download_post(post, "#patagonia")

**Expected behavior**
Download image using hashtag

**Error messages and tracebacks**
KeyError                                  Traceback (most recent call last)
<ipython-input-3-2e34d79d2586> in <module>
----> 1 posts = instaloader.Hashtag.from_name(L.context, "patagonia").get_posts()
      2 
      3 SINCE = datetime(2018, 5, 10)  # further from today, inclusive
      4 UNTIL = datetime(2018, 12, 1)  # closer to today, not inclusive
      5 

C:\ProgramData\Anaconda3\lib\site-packages\instaloader\structures.py in from_name(cls, context, name)
   1321         # pylint:disable=protected-access
   1322         hashtag = cls(context, {'name': name.lower()})
-> 1323         hashtag._obtain_metadata()
   1324         return hashtag
   1325 

C:\ProgramData\Anaconda3\lib\site-packages\instaloader\structures.py in _obtain_metadata(self)
   1337     def _obtain_metadata(self):
   1338         if not self._has_full_metadata:
-> 1339             self._node = self._query({"__a": 1})
   1340             self._has_full_metadata = True
   1341 

C:\ProgramData\Anaconda3\lib\site-packages\instaloader\structures.py in _query(self, params)
   1333                                       params))
   1334         return self._context.get_json("explore/tags/{0}/".format(self.name),
-> 1335                                       params)['graphql']["hashtag"]
   1336 
   1337     def _obtain_metadata(self):

KeyError: 'graphql'

**Instaloader version**
`instaloader 4.7.1

**Additional context**

**Comment by lastcoala** [comment] 2021-06-05 12:40
Same. From my testing, this happen if you logged in using session file or username and password. It works just fine when you don't login. However, a lot of features would be unavailable if you don't login.

**Comment by Showmaster3000** [comment] 2021-06-06 07:44
Duplicate of #1080.

**Closed by Showmaster3000** 2021-06-06 07:44 UTC
Labels: bug
