### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by pxssy** [instaloader/instaloader#190] opened 2018-10-12 23:19 UTC
**Describe the bug**

Failure to login

**To Reproduce**

instaloader --login=myuser -password=mypassword profiletodownload

**Expected behavior**

Login should occur, and download should proceed.

**Error messages and tracebacks**

Session file does not exist yet - Logging in.
Fatal error: Login error: 400 Bad Request

**Instaloader version**

4.1.1

**Additional context**

Everytime i attempt, Instagram prompts me of a suspicious login, and i've to verify myself though my email, which i do. But when i try again to login, it produces the error and i've to reverify myself. I've been trying on off for the past week or 2. I've changed my password, --updated, others don't seem to have the same issue, i'm not sure why am i the only one affected.

**Comment by aandergr** [comment] 2018-10-14 09:49
Duplicate of #189.

**Closed by aandergr** 2018-10-14 09:49 UTC
