### ISSUE TITLE
Hashtag.from_name search throws 401 error always

### ISSUE THREAD

**Issue by magush27** [instaloader/instaloader#1913] opened 2023-03-13 20:18 UTC
**Describe the bug**
Every time I try to run a search using `Hashtag.from_name(context, hashtag) `I get this error:

`JSON Query to explore/tags/hashtag/: HTTP error code 401.`

**To Reproduce**

I have this Python code as an example:
```
import instaloader

def test_hashtag():
    hashtag = instaloader.Hashtag.from_name(
        instaloader.Instaloader().context, "hola"
    ).get_all_posts()
    print(hashtag)

test_hashtag()
```

I get:
`JSON Query to explore/tags/hola/: HTTP error code 401.`
`JSON Query to explore/tags/hola/: HTTP error code 401.`

**Expected behavior**

It should bring the posts object for that hashtag but I just get the above error every time.

**Instaloader version**
`instaloader==4.9.6`

**Additional context**
I'm logged into my instagram account fine, so that it's not a problem.

I tried searching for the query directly in my browser and it works, so the hashtag 'hola' exists and it should show the posts object. This is the query I tried:
[https://www.instagram.com/explore/tags/Hola/](https://www.instagram.com/explore/tags/Hola/)

What could be the problem?

**Comment by Natmacira** [comment] 2023-03-14 15:45
I have the same problem.

**Comment by WeArePlanta** [comment] 2023-03-14 20:39
same here

**Comment by tungrix** [comment] 2023-03-22 07:46
same here

**Comment by Mujadid-Ali** [comment] 2023-03-28 10:20
Facing same issues. Tried 3 different accounts the accounts are login successfully but when we try to search posts based on any hashtag using python modules it always gives `JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]` any work around or solution to this problem? 
I have also tried a fresh account it's also giving same error and also tried VPN still same issue.

**Comment by ihabpalamino** [comment] 2023-04-10 09:40
i think that after 24 hours it gonna work again you're blocked from instagram

**Comment by Mujadid-Ali** [comment] 2023-04-10 09:45
> i think that after 24 hours it gonna work again you're blocked from instagram

No, it's still not working and throwing same 401 error. I have logged in through browser the accounts are working totally fine but again when I use Instaloader API then got same error.

**Comment by zero0n3** [comment] 2023-05-29 17:09
Hi everyone. Watch out because it seems that Instagram has figured out how to block downloads made by instaloader regardless of IP or account.
Having banned my home IP, I tried to connect via a mobile hotspot, with a different IP and a different operator. Same result: 401 error.

And I don't use session files or logins to download. And I know for sure that the photo is public and does not need to login to be seen.

So watch out

**Comment by ihabpalamino** [comment] 2023-06-02 09:40
> Hi everyone. Watch out because it seems that Instagram has figured out how to block downloads made by instaloader regardless of IP or account. Having banned my home IP, I tried to connect via a mobile hotspot, with a different IP and a different operator. Same result: 401 error.
> 
> And I don't use session files or logins to download. And I know for sure that the photo is public and does not need to login to be seen.
> 
> So watch out

while not using login it was working fine but yesterdsay it says that i have to be logged so when use the get_cookie and import the session file it worked fine but after it shows the same error but sometimes for me it works normally and then it stop working and then the day after it works normally again

**Comment by k12978** [comment] 2023-06-07 22:56
+1

**Comment by aandergr** [comment] 2023-06-26 05:49
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.

**Closed by aandergr** 2023-06-26 05:49 UTC
Labels: duplicate

**Comment by magush27** [comment] 2023-06-26 14:16
> Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.

My issue post is older but ok
