### ISSUE TITLE
Redirect to login page issue (HTTP Redirect from url to anotherUrl)

### ISSUE THREAD

**Issue by 2b32dn** [instaloader/instaloader#1666] opened 2022-07-28 02:01 UTC
**Describe the bug**
The program won't allow me to download the latest pictures from a profile and prompt me to login instead.

**To Reproduce**
instaloader someProfile anotherProfile  -F

**Expected behavior**
Download all images and json from profiles

**Error messages and tracebacks**
`HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=someProfile to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
...
someProfile: Redirected to login page. Use --login.
`

**Instaloader version**
4.9.2

**Additional context**
I use the .exe to open the instaloader terminal to run the command line and I usually dont login

**Comment by Showmaster3000** [comment] 2022-07-28 07:39
Duplicate of #1617.

**Comment by senaykt** [comment] 2022-07-28 07:58
Same bug is occured on my side.

**Closed** 2022-07-28 08:03 UTC
Labels: duplicate
