### ISSUE TITLE
[19600] Failed to execute script '__main__' due to unhandled exception!

### ISSUE THREAD

**Issue by derMiepz** [instaloader/instaloader#1790] opened 2022-10-30 19:45 UTC
**Describe the bug**
Whenever I try to download a profile, I get an error. It used to work a few weeks ago so I'm not sure what's happening.

**To Reproduce**
.\instaloader.exe profile PROFILENAME -l MY_INSTA --no-metadata-json --no-compress-json --no-captions --latest-stamps --highlights

**Expected behavior**
It should download all new videos/images of said account from the last time I used instaloader.

**Error messages and tracebacks**
PS E:\Stuff\Instaloader> .\instaloader.exe profile PROFILENAME -l MY_INSTA --no-metadata-json --no-compress-json --no-captions --latest-stamps --highlights
Using latest stamps from C:\Users\fabia\AppData\Local\Instaloader\latest-stamps.ini.
Session file does not exist yet - Logging in.
Enter Instagram password for MY_INSTA:
Traceback (most recent call last):
  File "__main__.py", line 505, in <module>
  File "__main__.py", line 502, in __main
  File "__main__.py", line 471, in main
  File "__main__.py", line 121, in _main
  File "instaloader\instaloader.py", line 1572, in interactive_login
  File "instaloader\instaloader.py", line 634, in login
  File "instaloader\instaloadercontext.py", line 265, in login
  File "requests\cookies.py", line 328, in __getitem__
  File "requests\cookies.py", line 399, in _find_no_duplicates
KeyError: "name='csrftoken', domain=None, path=None"
[19600] Failed to execute script '__main__' due to unhandled exception!

**Instaloader version**
4.9.5

**Additional context**
I also recently updated instaloader in hopes of that fixing the error.

**Comment by Showmaster3000** [comment] 2022-10-30 22:33
The 10th(?) duplicate of #1758.

**Comment by top31** [comment] 2022-11-04 03:57
> > The 10th(?) duplicate of #1758.
> 
> what's wrong with you idiot Why are you hunting everyone?

**Closed** 2022-12-03 15:57 UTC
Labels: duplicate
