### ISSUE TITLE
Errors occured: 404 Not Found using command line tool

### ISSUE THREAD

**Issue by schwanne** [instaloader/instaloader#273] opened 2019-03-31 20:28 UTC
**Describe the bug**
While downloading from a hashtag with over one million posts, I receive the error 404 Not Found after approximately 35K posts downloaded and the program stopped.  This behavior has repeated 3 times at a similar spot.

**To Reproduce**
`instaloader --no-videos --geotags --comments --no-captions --no-compress-json --max-connection-attempts 0 "#<myhashtag>"`

**Expected behavior**
missing post would be skipped and rest of posts would be retreived

**Error messages and tracebacks**
`#hash-tag-name: 404 Not Found

Errors occured:
#hash-tag-name: 404 Not Found`

**Instaloader version**
4.2.3

**Additional context**
Is there a way to get more verbose error information to see what is making it fail?  Also, if it is a missing post, is there a way to skip it and move on?

This is a great tool!  I would be interested in contributing a fix if I were given pointers on where to look.

**Comment by aandergr** [comment] 2019-04-02 20:38
Duplicate of #146.

**Closed by aandergr** 2019-04-02 20:38 UTC
