### ISSUE TITLE
Error 429 even with proxy

### ISSUE THREAD

**Issue by rocailler** [instaloader/instaloader#654] opened 2020-06-02 10:11 UTC
I know the problems with 429 error, but i can't understand the issue with 429 after proxy change. 

I did too lot of request on my proxies, so i had blocked (i hope for 24h). Then i bought another proxies and... i can't do anything.

How it's possible that i have a 429 on first request after proxy and agent change? 
Please help me understand rate control and requests problems cause i can't set it for a big sets of data

```
from datetime import datetime
from itertools import dropwhile, takewhile
import instaloader
from instaloader.exceptions import ProfileNotExistsException, TooManyRequestsException, ConnectionException, LoginRequiredException 
import os
from time import sleep

os.environ['https_proxy'] = PROXY
agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763'
SINCE = datetime(2020, 5, 31)
UNTIL = datetime(2020, 5, 20)
PROFILES = ... # long list of profiles

L = instaloader.Instaloader(user_agent=agent, 
                 max_connection_attempts=3,
                 dirname_pattern='backup/posts/1',
                 filename_pattern='{date_utc} {mediaid} {target}_post',
                 download_pictures=False, 
                 download_videos=False, 
                 download_video_thumbnails=False,
                 download_geotags = False,
                 download_comments = False,
                 compress_json=False, 
                 post_metadata_txt_pattern=""
                )
for nr, PROFILE in enumerate(PROFILES):
    print('{}: {}'.format(nr, PROFILE))
    
    while True:
        try:
            posts = instaloader.Profile.from_username(L.context, PROFILE).get_posts()
            for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
                print(post.date)
                L.download_post(post, target=PROFILE)
                
            break
        except ProfileNotExistsException:
            print('{} - not exist'.format(PROFILE))
            break
        except (TooManyRequestsException, ConnectionException):
            print('TooManyRequestsException, ConnectionException')
            sleep(900)
            pass
        except LoginRequiredException:
            print('{} -LoginRequiredException'.format(instaloader.Profile.from_username(L.context, PROFILE).is_private))
            break
```
I'm changing proxy, agent, even entire environment and still:

```
HTTP redirect from https://www.instagram.com/PROFILE/ to https://www.instagram.com/accounts/login/
The request will be retried in 666 seconds, at 00:16.
JSON Query to PROFILE: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occured in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 36 requests
    last 30 minutes: 235 requests
    last 60 minutes: 571 requests
  472f257a40c653c64c666ce877d59d2b
    last 10 minutes: 0 requests
    last 11 minutes: 0 requests
    last 15 minutes: 0 requests
    last 20 minutes: 0 requests
    last 30 minutes: 8 requests
    last 60 minutes: 17 requests
```

**Comment by gcstr** [comment] 2020-06-02 13:29
Are you running locally or in a remote server?

**Comment by rocailler** [comment] 2020-06-02 13:41
> Are you running locally or in a remote server?

both, i'm trying on my laptop macos, tablet windows, linux server. on local connection and mobile connection.
Even if i'm trying on mobile connection for the first time this code on new proxy there is an error. maybe something with user agents or with code ? i have no idea, how it's possible that instagram is blocking all proxies after blocking one.

if i del https_proxy from os.environ then it works fine on local connection. (but now i have a block even without proxy)

**Comment by datanizing** [comment] 2020-06-02 15:50
I think Instagram very recently changed something and now blocks all (cloud) servers by IP address. I used to run instaloader on AWS servers, but it's not working anymore. Even a simple wget is not working - neither for profiles nor for posts.

**Comment by heyt0ny** [comment] 2020-06-02 18:41
Having the same issue [#641](https://github.com/instaloader/instaloader/issues/641)
1 ) Seems like not it's impossible to get user info without logging in
2) Seem likes Instaloader class not working. I partially solved the problem switching to requests to `www.instagram.com/<ig>?__a=1` and passing login cookies, but still hitting the limit
```
Error

Please wait a few minutes before you try again.
```

Though the limit is higher than 1 request in hour

**Comment by heyt0ny** [comment] 2020-06-02 21:26
Okay, I can confirm that I was able to scrape using method above around 400 profiles in ~18 hours, before hitting the limit. So seems like a limit is around 1 profile in 3 minutes.

**Comment by rocailler** [comment] 2020-06-05 09:06
It seems that Instagram decreased limits. I still have problems with proxy, instagram blocked almost all IPs, is there any good proxy pool with healthy proxies? 

if i have the code like in first post, how i should setup the sleep time? cause after 200-300 i'm getting 24h 429error. 

In this case what is the 1 request? getting profile with all filtered posts or downloading single post?

**Comment by cloudrac3r** [comment] 2020-06-05 14:41
> I think Instagram very recently changed something and now blocks all (cloud) servers by IP address. 

This _seems_ to be true as well, but I don't want to declare it as confirmed until I know more. All my servers running [Bibliogram](https://bibliogram.art) from Vultr have been blocked from accessing user profile pages (i.e. hxxps://www.­instagram.com/username and hxxps://www.instagram.com/username?__a=1) since somewhere around June 1st. This includes a new server that I just created that presumably does not have any recent outgoing requests from its IP. However, this block is NOT status code 429, it's status code 302 with a redirect to the login page.

/graphql requests from my servers do not seem to be restricted. They're subject to the usual limits.

**Comment by Thammus** [comment] 2020-06-06 10:02
Like discussed in #652 it might be that Instagram has a special restriction policy for Cloud and VPN services in terms that they block anonymous requests. The same restrictions might apply for proxy services which would result in the here observed behavior.

**Comment by rocailler** [comment] 2020-06-06 13:25
hmm it can be true (it is my observation about instaloader behavior past few days), but there are few kinds of proxy. shared and private ok - it's easy for instagram to ban some IP ranges, but residential and 4g proxies are real IPs, it should work. Or I can't setup it correctly ;)

**Comment by datanizing** [comment] 2020-06-30 15:01
For me it appears to be working again also from cloud servers. Instagram has maybe adjusted the rules.

**Comment by cloudrac3r** [comment] 2020-07-07 11:02
@datanizing Which servers specifically are you using? AWS, Hetzner, Linode, ...?

**Comment by jxmesth** [comment] 2020-07-11 16:57
Having the same issue here. The weird thing is, Instaloader seems to work for all profiles, public as well as private, except for this one profile that I've been trying to download for ages. Downloads for all other profiles work perfectly fine but when I try to download this one specific profile I get this: 

'''
HTTP redirect from https://www.instagram.com/PROFILE/ to https://www.instagram.com/accounts/login/?next=/PROFILE/
JSON Query to PROFILE/: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
The request will be retried in 666 seconds, at 19:55.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
[skipped by user]
PROFILE: JSON Query to PROFILE/: 429 Too Many Requests: redirected to login

Errors or warnings occurred:
PROFILE: JSON Query to PROFILE/: 429 Too Many Requests: redirected to login
'''

**Comment by jxmesth** [comment] 2020-07-11 16:58
Having the same issue here. The weird thing is, Instaloader seems to work for all profiles, public as well as private, except for this one profile that I've been trying to download for ages. Downloads for all other profiles work perfectly fine but when I try to download this one specific profile I get this: 

```
HTTP redirect from https://www.instagram.com/PROFILE/ to https://www.instagram.com/accounts/login/?next=/PROFILE/
JSON Query to PROFILE/: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
The request will be retried in 666 seconds, at 19:55.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
[skipped by user]
PROFILE: JSON Query to PROFILE/: 429 Too Many Requests: redirected to login

Errors or warnings occurred:
PROFILE: JSON Query to PROFILE/: 429 Too Many Requests: redirected to login
```

**Comment by midnightbash** [comment] 2020-07-11 20:15
I can confirm the error message _"JSON Query to api/v1/media/<number>/info/: 429 Too Many Requests Unable to fetch high quality image version of <Post <code> >"_. 

The funny thing is: JDownloader 2, a universal downloader application, has absolutely no trouble downloading the same bunch of Instagrams in a snap (up to about 50 tested in a row, without any issues), while Instaloader gets stuck and temp blocked (?) after only a few minutes / files.
It seems, those two tools have a different approach accessing the IG servers...

One after another, I've been running Instaloader 4.4.4 in a VirtualBox with Debian 10 and in another VirtualBox with Xubuntu 20. Host for the VirtualBox is Windows 10 (Version 10.0.18363.900), and it connects through a 100 Mbit/s connection either directly or through a "Private Internet Access" VPN with varying connection points. 
Jdownloader 2 is running on the Host (Windows 10), using the same internet connection. When Instaloader is already stuck again, typically Jdownloader 2 will still work on the same VPN IP.

Also, Instaloader and Jdownloader 2 both use the same Instagram account to authenticate themselves. While Instaloader is already blocked, JDownloader 2 can still use the same account.

I should also mention that the two virtual Linux boxes are working nicely for other downloads. No connection issues there.

I'd love to use Instaloader for periodic automatic downloads in Linux, but at the current state it's unusable to me. Hoping for a fix... Thanks.

**Comment by jxmesth** [comment] 2020-07-11 20:56
@midnightbash Hmm that's interesting, thanks for the info.

**Comment by aandergr** [comment] 2020-07-15 09:06
The problem discussed here might be fixed with [Version 4.4.5rc1](https://github.com/instaloader/instaloader/releases/tag/v4.4.5rc1), which includes a change of how post and profile metadata is accessed (#727).

To upgrade:
```
pip3 install --upgrade --pre instaloader
```

---

Thanks for sharing your observations, @midnightbash.

The error message you mention indicates that Instaloader has trouble accessing the iPhone endpoint, which we use to obtain higher-quality versions of the pictures since Version 4.4.4. It might be worth trying out version 4.4.3 to see if the problem disappears when loading lower-quality pictures.

We recently noticed that Instaloader uses fewer requests per sliding window than what currently seems to be possible. Version 4.5 will most probably use a higher request rate, and make it easier for the user to control rate behavior (#716).

**Comment by midnightbash** [comment] 2020-07-16 00:04
@aandergr :  Thank you for the hints! 
I'll try to 'downgrade' to 4.4.3 for a comparison (will figure out how to do that in linux). I might also check the Instaloader Windows-version.

As for now, here's a direct comparison video of Instaloader 4.4.4, Instaloader 4.4.5rc1 and Jdownloader 2: 
[https://youtu.be/fA9Fps1-Aqc](url)

**Comment by aandergr** [comment] 2020-07-18 14:29
In the video, I don't see any error with the _JSON Query to api/v1/media/.../info/_ so there is no benefit in trying out with version 4.4.3.

The difference in how long it takes can be explained by what I commented earlier, that Instaloader 4.4 uses a lower request rate than what currently seems to be possible. Instaloader 4.5 will provide a faster experience here, you can try out the current pre-alpha state with:

```
pip3 install --upgrade git+https://github.com/instaloader/instaloader@upcoming/v4.5
```

To further tune its performance, you can pass the `--no-sleep` flag, which is intentionally left undocumented, to further reduce the waiting times between requests while still obeying the rate limits.

**Comment by midnightbash** [comment] 2020-07-20 01:08
@aandergr : vielen Dank, thanks for the additional infos. And sorry, I didn't make myself clear about the video.
I still do get the the "JSON Query to api1" error with 4.4.5rc1 in some situations. [https://imgur.com/cz0IUYc.png](url)

I'll have to do further experimenting with 4.5 and maybe 4.4.3 (if i can downgrade).
Thank you for your work.

**Comment by aandergr** [comment] 2020-07-25 09:12
I just experimented with downloading big profiles including the information that requires accessing the iPhone endpoint, and it seems to work fine with the rate limits as they are configured in 4.5. I did not get any 429 error.

**Comment by Lum1nanz** [comment] 2020-08-04 15:38
I have a pretty strange problem with this aswell: On my server (netcup.de) instagram gives me the 429-error, despite being logged in and using proxy-servers (random selection) to request profiles. I also tried requesting without login.
The strange thing is: When i run the very same application (docker-container) on my local machine it works without an error (despite using the very same logic with the proxies and stuff).
Do you guys have any idea what is going on here?

**Comment by Lum1nanz** [comment] 2020-08-04 18:05
I have a really weird phenomenon and maybe one of you guys knows what is going on:
When I deploy my application (that uses Instaloader) on my root-server (netcup.de) and try to download a profile, I always get a 429-error. When I run the very same application on my local MacBook, the error doesn't occur. (I added some proxy-functionality to the application). The weird thing is, it doesn't matter if I am logged in or not - locally it works, on the server it doesn't. Can anybody of you imagine what is going on here? Any help would be much appreciated.

**Comment by aandergr** [comment] 2020-08-06 07:35
@Lum1nanz that's exactly the here-described issue.

There seem to be harder restrictions for anonymous access from within some datacenter IP ranges, in some cases leading to a 429 on the very first request. There was a change (#727) which makes accessing profiles possible on VPNs, Tor, cloud servers, etc.. This change is included in versions >= 4.4.5. Given that it's accessing profiles which causes trouble for you: Do you use at least version 4.4.5?

Also, these restrictions do not seem to apply for logged-in users. As far as already has been reported, logging in should solve the problem. Do you have problems on your server even if logged-in?

**Comment by Lum1nanz** [comment] 2020-08-06 11:20
@aandergr much love my friend <3

I didn't know that this problem got tackled with version 4.4.5 and i was using 4.4.4. I updated and implemented various adaptions to make sure, my application works and now it does :)

Thank you very much man :)

**Closed** 2020-09-19 15:22 UTC
Labels: question

**Comment by restyler** [comment] 2020-12-29 18:09
In case anyone is still suffering on strict rate limits of Instagram and getting 302 (redirect to login) or 429 err, I want to note that it turned out public profiles and posts are still accessible without logging in, the only issue is finding residential proxies with clean ip addresses. https://rapidapi.com/restyler/api/instagram40 solves this problem via proxy network balancer and response health checks.

**Comment by evilgenius786** [comment] 2021-03-27 14:55
How to use proxies in multithreaded instaloader?
