### ISSUE TITLE
[Duplicate] Login failed. Require checkpoint

### ISSUE THREAD

**Issue by Massa4usetts** [instaloader/instaloader#1982] opened 2023-05-19 11:40 UTC
Its same issue as old one closed https://github.com/instaloader/instaloader/issues/328

The bug is reproducing again. Using pyTelegramBotAPI 4.12.0 and instaloader 4.9.6

While trying to download stories i got a message 

`Login: Checkpoint required. Point your browser to www.instagram.com/challenge/AXEHCMEKofRt_9a-0Zfgu7qSKmuBvUr0Wq8tp6JHx8jHdYgvfQN0YxAlCSBeUkgUPjtazg/AfxqzifP9AcjTSbQlmObVE0VfJ9lpawFDSP8f7y4PxE68xfFMcOPEcv4eX1SHChIzpDXnzbZuM_OwQ/?challenge_context=Af5jcotThWKG6K0Z_NyWhIYQ0M1J1q86XhuGzi3Rf1Y8gtjBk8ElsJnlz4s1fjD-hThrm8meW1GIIsdostp5jsyIyn3mauEF8NI-k7CbKGr-nzbs_FNJ8f9vYkdBJnXUEBWWvOWRNyuLd3IRbdEdFCCyMzVL-IJZXIC9ihn4e_zbOe5bm8UzYQmgqJMPBEbvGBkNsutERPZFbyPTzrj0v9AP94XmROpyzIcBLoVq7QVNuFtu0gwoYW7Eqo2wGozfNnRrq3wL_vzw9624you1B3uijvYPX-KoW8rAzmwMmWFLzz3Q5S2IDm3C-GevYqtzMjcqRGzAL2OUtY8qAyOM4tR6NmoABB-NXJk_UbnIzUYH9tulgXsxIQyEtU6PFpu0hqHaG46MiO9iha4BJkZZ9JMFLxIiChX9s12Wmz-Yix0SU1IjY9ofAwRbWyKTN_nEgWRJmbpgYunvDMOhGN0wfwZLpMJOw0RANkLiLkVb6VrwFitrYlUmB0M1pyo4ztgJk4GYb9yzBem2YTe53s24Q9_FfqmCNrtLOVxNSRWhAafCiTlBjrtm4a0cao_E5497msj6DTc2T0zfqZordv8CUavJbeZry64p_qUEHeOGaTLKRIZCOJyq5IrS8ooFzb7gKQSZEH6-WwZpgi2zaZQOzvUy1qpxAu_uiSBbXAMAzUqFcqRw37cW7s1Vi5FD927fgNvscKhF0yTQP0e2su2b4uqrrJkspX2tgBQxGOav3PqPLUEYlgKVMkDy00kk1OgBMYFSPs4N5_etMRn1TSI1dHRIUXh0RnSZxo8iIKmbFucWn-JIxFkTmdwkm6eW2vBSCxMkYLZG3MD70wCaeRlnFxxuHqLvUs0-7eti_oDwQMD1SEZQldwns5f-EkCyC5y4tqD0hNbcOFd_W-veFIFeAAleQyPXoMJD5Lgw32e2-_p71cJBJGzL-KbqihuKY3A_Gx7sLVQsGKgZ-M_qaOuklO35HAn6-s1oIYeR1Gln8Je_5wrsg1LF4gsp5D6MhjdB5UAJbOK6OqTEJmo1zujqe5XOh0WUYw1zvqwGcfKbghx3vxX-ITuO2nqmX3tKaHidQPPKdFaaqXfVum7KP6wRTfnDS5W9_7C8omBhBOgEcxzunmTzmAQpRyrIAg2fvaHKgWpHdM5EhyVQpwJtXUh7rbA5r-fFSEZq0RHpNzVIrw - follow the instructions, then retry.`

But if i open a linke is nothing happen, just regular Instagram feed page is opening

**Comment by Showmaster3000** [comment] 2023-05-19 19:08
This bug was never really fixed cause Instagram is constantly changing things and/or blocking suspicious connection by third party software.
Duplicate of #1787.

**Comment by gck982** [comment] 2023-06-08 20:19
This is happening to me too. I go to the checkpoint link, confirm it is me trying to access my account, then it makes me change my password. I do, then retry everything only to get the exact same Checkpoint required response.

**Closed** 2023-06-26 05:55 UTC
Labels: duplicate

**Comment by FujiwaraChoki** [comment] 2023-07-05 19:31
Same problem here!
