### ISSUE TITLE
Cannot login using the 2FA

### ISSUE THREAD

**Issue by getangar** [instaloader/instaloader#1565] opened 2022-06-05 17:21 UTC
**Describe the bug**

**To Reproduce**
1. type the command: instaloader --login [your_username]
2. give the account's password3. 
3. give the code you receive on your mobile device (or in case, generated on the authenticator app)
4. you get the following error: 2FA error: This code is no longer valid. Please request a new one5. 
5. if you try again with a new code you get: 2FA error: feedback_required

**Expected behavior**
after giving the 2FA code, I expect to be authenticated by Instagram.

**Error messages and tracebacks**
1. This code is no longer valid. Please request a new one5. 2. 
2. 2FA error: feedback_required3. 

**Instaloader version**
4.9

**Comment by Showmaster3000** [comment] 2022-06-06 15:44
Looks like duplicate of still unsolved issue #1217.

**Closed** 2022-06-16 13:13 UTC
Labels: duplicate
