### ISSUE TITLE
V4.11rc2 still bugs about --login=user although --load-cookies edge is used

### ISSUE THREAD

**Issue by SubZero5** [instaloader/instaloader#2183] opened 2024-01-29 19:46 UTC
**Describe the bug**
V4.11rc2 still bugs me to use `--login=USERNAME` although `--load-cookies edge` is used

**To Reproduce**
`instaloader.b.exe --dirname-pattern={profile} --filename-pattern={profile}-{date_utc}-{shortcode} --no-captions --stories --highlights --tagged --igtv --no-metadata-json --fast-update --load-cookies edge martin_niederberger`

**Expected behavior**
Instaloader should not bug me about to login as I am already logged in at the browser. 

**Error messages and tracebacks**
--login=USERNAME required to download stories.
Cookies loaded successfully from edge
Next:  Run instaloader --login=mgIgUser as it is required to download high quality media and to make full use of instaloader's features. 

**Instaloader version**
Version 4.11rc2

**Additional context**
PS: Have not tried the cookies file.

**Comment by aandergr** [comment] 2024-06-29 18:29
Duplicate of #2259, fixed in [version 4.11.1](https://github.com/instaloader/instaloader/releases/tag/v4.11.1).

**Closed by aandergr** 2024-06-29 18:29 UTC
Labels: duplicate
