### ISSUE TITLE
It stops downloading?

### ISSUE THREAD

**Issue by FatalFlawz** [instaloader/instaloader#1672] opened 2022-08-01 22:33 UTC
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/?next=/graphql/query
myusername: Redirected to login page. Use --login.
Errors or warnings occurred:
myusername: Redirected to login page. Use --login.

It goes along perfect then i started to get this error and it would stop the download? Could someone help thanks

**Comment by Showmaster3000** [comment] 2022-08-01 22:39
duplicate of #1617 (and #1666).

**Comment by FatalFlawz** [comment] 2022-08-01 22:40
My bad did not read those

**Closed** 2022-08-09 14:02 UTC
Labels: duplicate, invalid
