### ISSUE TITLE
The program refuses to download a highlight that has a period at the end of its title. 

### ISSUE THREAD

**Issue by andrewkim51** [instaloader/instaloader#1437] opened 2022-03-10 11:43 UTC
**Describe the bug**
The program refuses to download a highlight that has a period at the end of its title. 

**To Reproduce**
Download highlights that has a period at the end of its title.

**Expected behavior**
To start downloading the highlights. 

**Error messages and tracebacks**

username redacted for privacy

Retrieving highlights "ongoing.." from profile [username]
[username]\ongoing..\2022-01-06_09-53-06_UTC_cover.jpg Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\__main__.py", line 467, in main
    _main(loader,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\__main__.py", line 220, in _main
    instaloader.download_profiles(profiles,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 1421, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 80, in call
    return func(instaloader, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 915, in download_highlights
    self.download_highlight_cover(user_highlight, highlight_target)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 547, in download_highlight_cover
    self.download_title_pic(highlight.cover_url, target, 'cover', highlight.owner_profile)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 96, in call
    return func(instaloader, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 515, in download_title_pic
    self.context.write_raw(pic_bytes if pic_bytes else http_response, filename)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloadercontext.py", line 495, in write_raw
    with open(filename + '.temp', 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '[username]\\ongoing..\\2022-01-06_09-53-06_UTC_cover.jpg.temp'

**Instaloader version**
4.8.4

**Additional context**
OS is Windows 10

**Comment by aandergr** [comment] 2022-03-18 14:51
Duplicate of #710.

**Closed by aandergr** 2022-03-18 14:51 UTC
Labels: duplicate
