### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by jlntrt** [instaloader/instaloader#252] opened 2019-02-04 11:03 UTC
**Describe the bug**
When I'm trying to scrape a Instagram profile, the connection after a _random_ time is rejected.
At the moment I'm not sure if I just exceed the limit of IG/API calls or it is the handling of sleep time of instaloader.

**To Reproduce**
I tried different settings to reproduce the behavior. For now there is no difference between any of them. Event without login.The result is every time the same. The connection is rejected at random course of scraping. 
e.g. `instaloader --login=xy --session=../session --highlights --no-profile-pic jp.performance`

**Expected behavior**
I would suggest that Instaloader starts some sleep time and starts tries again. We have to consider the beste sleep time so the next try will be successful. 

**Error messages and tracebacks**
```bash
File "/home/x/lager/il4/lib/python3.6/site-packages/urllib3/response.py", line 331, in _error_catcher
    yield
  File "/home/x/lager/il4/lib/python3.6/site-packages/urllib3/response.py", line 413, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/lager/il4/bin/instaloader", line 11, in <module>
    sys.exit(main())
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/__main__.py", line 412, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/instaloader.py", line 928, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/instaloader.py", line 44, in call
    return func(instaloader, *args, **kwargs)
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/instaloader.py", line 587, in download_highlights
    else '{}/{}'.format(name, user_highlight.title))
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/instaloader.py", line 524, in download_storyitem
    downloaded |= self.download_pic(filename=filename, url=item.video_url, mtime=date_local)
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/instaloader.py", line 195, in download_pic
    self.context.get_and_write_raw(url, filename)
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 497, in get_and_write_raw
    self.write_raw(self.get_raw(url), filename)
  File "/home/x/lager/il4/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 455, in write_raw
    shutil.copyfileobj(resp.raw, file)
  File "/home/x/lager/il4/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/home/x/lager/il4/lib/python3.6/site-packages/urllib3/response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/x/lager/il4/lib/python3.6/site-packages/urllib3/response.py", line 349, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Instaloader version**
4.2.1

**Additional context**

**Comment by AndCycle** [comment] 2019-02-04 13:40
duplicate of #242 , 
which IG introduce new blockade to prevent any batch access.

**Closed** 2019-02-07 14:21 UTC
