### ISSUE TITLE
Login Not working

### ISSUE THREAD

**Issue by tathastu871** [instaloader/instaloader#1862] opened 2023-01-15 19:24 UTC
**Describe the bug**

Every time i use instaloader to login it says
Fatal error: login: checkpoint required. 
when i open given url in browser it forces to change password. 

not loggin in even after that

is it a phishing scam forcing to change password
**To Reproduce**
(e.g. Instaloader command line)
instaloader --login username
**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
`instaloader --version` output.

**Additional context**

**Comment by chrisl106** [comment] 2023-01-17 17:42
I have the same issue on v4.9.5

**Comment by patilaum** [comment] 2023-01-18 05:30
Same here.

**Comment by Showmaster3000** [comment] 2023-01-18 20:07
incomplete bug report.
anyway it looks like duplicate of #1787.

**Comment by arssy** [comment] 2023-01-19 06:17
Same here, after changing password twice, I can still log in to instagram on my phone and web browser, but I got this response whenever I'm trying to login via instaloader. It's the same with my other instagram account (password unchanged).

```
Session file does not exist yet - Logging in.
Enter Instagram password for instagram_username:
Fatal error: Login error: "fail" status, message ""
```

script: **instaloader --login=instagram_username**
instaloader version: **4.9.5**

**Comment by patilaum** [comment] 2023-01-19 06:19
You can do interactive login in python script. That works.

**Comment by tathastu871** [comment] 2023-01-19 06:42
> You can do interactive login in python script. That works.

but then how to scrape images. we have to write script from scratch

**Comment by tathastu871** [comment] 2023-01-19 06:46
> You can do interactive login in python script. That works.

not working tried interactive login. still not working

**Comment by tathastu871** [comment] 2023-01-19 06:48
after using instaloader to login. when i try to open instagran on browser or app it forces me to change password.

have changed password 5 times due to instaloader

**Comment by aandergr** [comment] 2023-02-06 18:12
Duplicate of #1787

**Closed by aandergr** 2023-02-06 18:12 UTC
Labels: duplicate
