### ISSUE TITLE
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.

### ISSUE THREAD

**Issue by ihabpalamino** [instaloader/instaloader#1947] opened 2023-04-12 16:01 UTC
![image](https://user-images.githubusercontent.com/86556941/231515538-e94bfab9-cad5-49e2-9d3c-0f4c4c63787e.png)
this is my source code
and here is te error i am getting;
"C:\Users\HP Probook\PycharmProjects\firstproject\venv\Scripts\python.exe" "C:/Users/HP Probook/PycharmProjects/firstproject/Twint.py"
Using cookies from C:\Users\HP Probook/AppData/Roaming/Mozilla/Firefox/Profiles\043pwafw.default-release-1680275989327\cookies.sqlite.
Imported session cookie for thescraper12.
Saved session to C:\Users\HP Probook\AppData\Local\Instaloader\session-alpachino.

JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 352, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 352, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 352, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\Twint.py", line 71, in <module>
    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\nodeiterator.py", line 141, in __next__
    query_response = self._query(self._data['page_info']['end_cursor'])
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\nodeiterator.py", line 103, in _query
    self._context.graphql_query(
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 429, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 385, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.

Process finished with exit code 1

**Comment by yarodevuci** [comment] 2023-04-14 00:32
@ihabpalamino seems like your IP got banned

**Comment by HirtLocker128** [comment] 2023-04-20 18:53
@yarodevuci Is there a confirmed solution for this? Have not been able to find one

**Comment by akafanfan** [comment] 2023-04-26 14:27
**I found a solution：**
1. https://instaloader.github.io/troubleshooting.html
2. To use this script,
3. Download the script: [Example 615_import_firefox_session.py] you can new a file "615_import_firefox_session.py" ,then copy the web page code and paste it into the py file (https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
4. Login to Instagram in Firefox,!!!!
5. Execute the snippet, e.g. with python 615_import_firefox_session.py,
6. in the "C:\Users\yang1\AppData\Local\Instaloader" ,you got a new session file.
7. use instaloader

**Comment by yarodevuci** [comment] 2023-04-27 05:54
@akafanfan my account got banned after that....

**Comment by zero0n3** [comment] 2023-05-29 17:06
Hi everyone. Watch out because it seems that Instagram has figured out how to block downloads made by instaloader regardless of IP or account.
Having banned my home IP, I tried to connect via a mobile hotspot, with a different IP and a different operator. Same result: 401 error.

And I don't use session files or logins to download. And I know for sure that the photo is public and does not need to login to be seen.

So watch out

**Comment by inesuki1920** [comment] 2023-05-29 20:14
I also got banned. Any idea on how to connect? I have tried with different IPs and no way. 

Thanks

**Comment by Ayushi1722** [comment] 2023-06-05 20:12
Did anyone find a solution to this problem?

**Comment by FabioSpoto** [comment] 2023-06-05 20:28
Same problem...

**Comment by natalya-patrikeeva** [comment] 2023-06-14 19:03
The way around the IP ban is to use a proxy or proxy manager that hides your local machine IP. The function to modify is graphql_query() in instaloadercontext.py. You can pass proxy and crt before calling self.get_json(). 
`tmpsession.proxies = {
                  'http': '<proxyhost>:<port>',
                  'https': '<proxyhost>:<port>'
            }
            tmpsession.verify = '<path-to-certs>/ca.crt'
            resp_json = self.get_json('graphql/query',
                                      params={'query_hash': query_hash,
                                              'variables': variables_json},
                                      session=tmpsession)`

**Comment by aandergr** [comment] 2023-06-26 05:49
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.

**Closed by aandergr** 2023-06-26 05:49 UTC
Labels: duplicate
