### ISSUE TITLE
Unable to login with two-factor authentication

### ISSUE THREAD

**Issue by JustWhit3** [instaloader/instaloader#1516] opened 2022-04-29 15:30 UTC
**Describe the bug**
Unable to login with two factor authentication using Instaloader Python class. I tried with [this](https://instaloader.github.io/troubleshooting.html#:~:text=its%20associated%20information.-,Login%20error,you%20do%20not%20have%20a%20session%20file%20present%2C%20you%20may%20use,-the%20following%20script) troubleshooting and it works. But I need a way to directly login from the script, as it should be ensured from what is written in the documentation, without the needing of passing through Firefox before. 

**To Reproduce**
```
import instaloader as ig

if __name__ == "__main__":
    
    username = "user"
    password = "passwd
    loader = ig.Instaloader()
    
    try:
        loader.login( username, password )
    except TwoFactorAuthRequiredException:
        code = int(input()) # Same if I don't force it to be an int.
        loader.two_factor_login( code )
```

**Expected behavior**
I expect any output, but a correct login.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "./prove.py", line 16, in <module>
    loader.two_factor_login( code )
  File "/home/gianluca/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 645, in two_factor_login
    self.context.two_factor_login(two_factor_code)
  File "/home/gianluca/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 287, in two_factor_login
    raise BadCredentialsException("2FA error: {}".format(resp_json['message']))
instaloader.exceptions.BadCredentialsException: 2FA error: This code is no longer valid. Please request a new one.
```

**Instaloader version**
4.9

**Comment by aandergr** [comment] 2022-05-07 13:24
Duplicate of #1217

**Closed by aandergr** 2022-05-07 13:24 UTC
Labels: duplicate
