### ISSUE TITLE
Instaloader can't download reels which are not listed in the post section.

### ISSUE THREAD

**Issue by albus1234** [instaloader/instaloader#1966] opened 2023-05-06 20:10 UTC
**Describe the bug**
I can't download reels. These reels are those which do not appear in the post section but are available at the reels section in Instagram.

**To Reproduce**
Try downloading an account which have some reels not in the post section using command line interface.

**Expected behavior**
Instaloader should download these reels too. Maybe in the same folder or some seperate one.

**Error messages and tracebacks**
No error message. Just reels don't get downloaded

**Instaloader version**
`instaloader --4.9.6` output.

**Additional context**
This may be because instaloader tries to download data given in the post section only. Hence it ignores reels which are not included in this section.

**Comment by Showmaster3000** [comment] 2023-05-06 23:45
This is not a bug, its a missing feature. Instaloader currently cannot download reels listed on the separate tab.

**Comment by aandergr** [comment] 2023-05-24 05:47
Duplicate of #812

**Closed by aandergr** 2023-05-24 05:47 UTC
Labels: duplicate
