### ISSUE TITLE
Weird bug when running

### ISSUE THREAD

**Issue by Muggeren** [instaloader/instaloader#1718] opened 2022-08-30 16:09 UTC
**Describe the bug**
After running for like 20 min, this occurs:

"[  6/ 10] Warning: Unable to fetch video from graphql of <StoryItem 2675921249948319648>: list index out of range
Unable to fetch high-quality video version of <StoryItem 2675921249948319648>: 'video_versions'
Traceback (most recent call last):
  File "__main__.py", line 505, in <module>
  File "__main__.py", line 502, in __main
  File "__main__.py", line 471, in main
  File "__main__.py", line 220, in _main
  File "instaloader\instaloader.py", line 1456, in download_profiles
  File "instaloader\instaloader.py", line 81, in call
  File "instaloader\instaloader.py", line 960, in download_highlights
  File "instaloader\instaloader.py", line 887, in download_storyitem
  File "instaloader\instaloader.py", line 97, in call
  File "instaloader\instaloader.py", line 340, in download_pic
  File "re.py", line 201, in search
TypeError: expected string or bytes-like object
[17556] Failed to execute script '__main__' due to unhandled exception!"

**To Reproduce**
happens when i use this
--login=username
--password=password
--no-metadata-json
--no-captions
--no-video-thumbnails
--tagged
--highlights
PROFILE
PROFILE

**Expected behavior**
To download all requested from above

**Error messages and tracebacks**
Just did

**Instaloader version**
v4.9.3
-->

**Comment by Showmaster3000** [comment] 2022-08-30 20:11
potentially same thing like in #1460. But this issue is closed and looks unfixed?

**Comment by aandergr** [comment] 2022-09-07 19:12
Duplicate of #1460

**Closed by aandergr** 2022-09-07 19:12 UTC
Labels: bug

**Comment by IljaM13** [comment] 2022-09-14 01:46
As workaround: run with --highlights and --fast-update
This will skip already downloaded highlights an won't run into exception.
Maybe it will crash with one of the following highlights. Just retry until you gott them all. :-)
