### ISSUE TITLE
"name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by WalidHadri-Iron** [instaloader/instaloader#1770] opened 2022-10-13 20:09 UTC
It has been some weeks that I am getting this:

KeyError: "name='csrftoken', domain=None, path=None"

When I try to login
L = instaloader.Instaloader()
L.login(username, password)

**Instaloader version**
`instaloader --version` 4.9.5.

Thanks for the help !

**Comment by Showmaster3000** [comment] 2022-10-13 20:32
Duplicate of #1758

**Closed** 2022-10-13 20:32 UTC
Labels: bug
