### ISSUE TITLE
option to dowload the reels from instagram 

### ISSUE THREAD

**Issue by 6Q9zYC6** [instaloader/instaloader#2310] opened 2024-07-17 20:05 UTC
![Screenshot from 2024-07-18 01-31-26](https://github.com/user-attachments/assets/2ef2a527-4735-4567-93ea-1d85ac9e41c6)

**Suggestion**
Remove the option of IGTV because the don't exist any more 
and add option to dowload reels ::  --reel

**Comment by grub-404** [comment] 2024-07-29 19:04
add get the shares from reels MetaData

**Comment by aandergr** [comment] 2024-10-26 17:47
Duplicate of #812

**Closed by aandergr** 2024-10-26 17:47 UTC
Labels: duplicate
