### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x00'

### ISSUE THREAD

**Issue by Purefreeman** [instaloader/instaloader#233] opened 2019-01-17 19:00 UTC
The bat file i run came up with errors after updating to version 4.2.1, i also tried to download one manually but i got the same error `C:\Users\freeman\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader --highlights -l  -p  --fast-update tajijoseph`

for downloading posts `C:\Users\freeman\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader --highlights -l ******** -p ******  --fast-update tajijoseph`

for downloading stories `C:\Users\freeman\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader --highlights -l ********  -p ******* tajijoseph --stories-only --no-video-thumbnails --no-profile-pic`

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "c:\users\freeman\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\freeman\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\freeman\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader.exe\__main__.py", line 9, in <module>
  File "c:\users\freeman\appdata\local\programs\python\python36-32\lib\site-packages\instaloader\__main__.py", line 412, in main
    storyitem_filter_str=args.storyitem_filter)
  File "c:\users\freeman\appdata\local\programs\python\python36-32\lib\site-packages\instaloader\__main__.py", line 81, in _main
    instaloader.load_session_from_file(username, sessionfile)
  File "c:\users\freeman\appdata\local\programs\python\python36-32\lib\site-packages\instaloader\instaloader.py", line 349, in load_session_from_file
    self.context.load_session_from_file(username, sessionfile)
  File "c:\users\freeman\appdata\local\programs\python\python36-32\lib\site-packages\instaloader\instaloadercontext.py", line 168, in load_session_from_file
    session.cookies = requests.utils.cookiejar_from_dict(pickle.load(sessionfile))
_pickle.UnpicklingError: invalid load key, '\x00'.
```

**Instaloader version**
instaloader 4.2.1

**Comment by aandergr** [comment] 2019-01-17 19:03
That looks like a problem with loading your session file (where we didn't change anything). Try deleting your session file and it should work.

**Comment by maddingamer** [comment] 2019-01-17 20:52
Nearly the same happens to me after update.. deleted session file but still same errors..

**Comment by aandergr** [comment] 2019-01-17 20:56
> Nearly the same happens to me

what exatly happens?

**Comment by maddingamer** [comment] 2019-01-17 21:17
dont know, deleted the session file 2 or 3 times and workes now aigan 👍

**Comment by aandergr** [comment] 2019-01-17 21:21
Duplicate of #66.

**Closed by aandergr** 2019-01-17 21:21 UTC

**Comment by maddingamer** [comment] 2019-01-17 21:39
ok so apperantly my error depends on the profile.. some work some profile doesn't.. here is the output: 


```
python3 /instaloader/instaloader.py targetuser --login=username --stories --tagged --no-captions --no-videos --no-metadata-json --highlights --fast-update --dirname-pattern /downloads/{target}/ --sessionfile /settings/1/.instaloader-session

Loaded session from /settings/1/.instaloader-session.

Logged in as username.

/targetuser//2019-01-12_12-49-48_UTC_profile_pic.jpg Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 483, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.6/http/client.py", line 588, in _readinto_chunked
    n = self._safe_readinto(temp_mvb)
  File "/usr/lib/python3.6/http/client.py", line 628, in _safe_readinto
    n = self.fp.readinto(mvb)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/instaloader/instaloader/__main__.py", line 412, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/instaloader/instaloader/__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/instaloader/instaloader/instaloader.py", line 911, in download_profiles
    self.download_profilepic(profile)
  File "/instaloader/instaloader/instaloader.py", line 317, in download_profilepic
    self.context.write_raw(profile_pic_bytes if profile_pic_bytes else profile_pic_response, filename)
  File "/instaloader/instaloader/instaloadercontext.py", line 455, in write_raw
    shutil.copyfileobj(resp.raw, file)
  File "/usr/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

```

**Comment by brando90** [comment] 2022-02-12 18:59
related https://github.com/learnables/learn2learn/issues/310
