### ISSUE TITLE
Instaloader.download_post(): ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by skrull** [instaloader/instaloader#1085] opened 2021-04-09 08:40 UTC
version: 4.7.1
command line: instaloader --commit-mode --login=(stripped) --sessionfile session --no-posts --abort-on=302,400,429 --tagged user

[ 30] Traceback (most recent call last):
  File "pvenv/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "pvenv/lib/python3.8/site-packages/instaloader/__main__.py", line 445, in main
    _main(loader,
  File "pvenv/lib/python3.8/site-packages/instaloader/__main__.py", line 211, in _main
    instaloader.download_profiles(profiles,
  File "pvenv/lib/python3.8/site-packages/instaloader/instaloader.py", line 1274, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter)
  File "pvenv/lib/python3.8/site-packages/instaloader/instaloader.py", line 1119, in download_tagged
    self.posts_download_loop(profile.get_tagged_posts(),
  File "pvenv/lib/python3.8/site-packages/instaloader/instaloader.py", line 922, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "pvenv/lib/python3.8/site-packages/instaloader/instaloader.py", line 618, in download_post
    for i in range(self.slide_start % post.mediacount, self.slide_end % post.mediacount + 1)),
ZeroDivisionError: integer division or modulo by zero

**Comment by Deleora** [comment] 2021-04-12 12:46
Just curious, what's the point of using both `--login` and `--sessionfile`?

**Comment by skrull** [comment] 2021-04-12 14:26
Nothing really important, but it just asks the password if the session file is missing.

**Comment by aandergr** [comment] 2021-04-15 18:44
How is this reproducible?

**Comment by skrull** [comment] 2021-04-19 06:18
There you go.

https://pastebin.com/tf4Hy24b

**Comment by aandergr** [comment] 2021-04-22 18:27
Thanks. Also reproducible with: `instaloader -- -CNLdFNkBuM1` (downloading the single post that fails)

**Comment by aandergr** [comment] 2021-10-07 18:53
Mentioned post does not exist anymore. Is there any other post for which this error happens?

**Comment by skrull** [comment] 2021-11-18 17:24
@aandergr sorry about the delay. Got it again yesterday. 

https://pastebin.com/nn8brAaG

**Comment by 89z** [comment] 2021-11-22 03:01
https://github.com/instaloader/instaloader/issues/1346

**Comment by QrchackOfficial** [comment] 2022-12-15 11:03
I'm having the same issue. Seems like `post.mediacount` is 0 for some reason and instaloader does `self.slide_start % post.mediacount` without checking, causing the whole program to crash. Perhaps some change on Instagram's end, or a form of rate limiting? Or possibly something to do with removed/edited posts... Either way, I feel like there should be a check if it's 0 and if so, instaloader should handle it gracefully - either by skipping that post by default and printing a warning (preferably), or by allowing the user to choose to do so by a command switch.

**Comment by rouncewell** [comment] 2023-01-31 18:05
I too am having this issue. I have a large backlog of downloads and would like to continue downloading them but I can't since it keeps causing Instaloader to crash. Did anyone find a work around to this?

**Comment by JunedKhan101** [comment] 2023-05-06 10:50
Hi @skrull I cannot access your pastebin it says:

> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by pramoodsurya** [comment] 2024-02-02 12:20
![image](https://github.com/instaloader/instaloader/assets/23474357/886e79f2-173f-4c86-b599-959c011d60c7)

I changed this line it worked for me

**Comment by SeamusMullan** [comment] 2024-03-15 09:39
I've attempted a fix for this issue #2214

**Closed** 2024-07-03 06:19 UTC
Labels: bug, leave open, good first issue
