### ISSUE TITLE
Could not found window._sharedData

### ISSUE THREAD

**Issue by KarelWintersky** [instaloader/instaloader#1560] opened 2022-06-03 22:50 UTC
**Describe the bug**
```
instaloader --fast-update --login=karelwintersky arend_the_elf

...

Logged in as karelwintersky.
JSON Query to arend_the_elf/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to arend_the_elf/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Trying to find profile arend_the_elf using its unique ID 3619983420.
Profile arend_the_elf has changed its name to arend_the_elf.
JSON Query to arend_the_elf/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to arend_the_elf/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile arend_the_elf does not exist.
The most similar profile is: arend_the_elf.
Trying again anonymously, helps in case you are just blocked.
Warning: arend_the_elf will be downloaded anonymously ("Profile arend_the_elf does not exist.
The most similar profile is: arend_the_elf.").
```
and so on for each account

**Comment by Showmaster3000** [comment] 2022-06-04 00:00
Duplicate of #1553.

**Comment by Showmaster3000** [comment] 2022-06-04 13:55
Please do not spam the issue list. Use the linked issue #1553 for this problem (I know the title isn't very speaking, but I can't change it).

**Closed by Showmaster3000** 2022-06-04 13:55 UTC
Labels: duplicate
