### ISSUE TITLE
"JSON Query to graphql/query: HTTP error code 403"

### ISSUE THREAD

**Issue by pvita** [instaloader/instaloader#94] opened 2018-04-11 08:29 UTC
Hi there, 
I'm receiving this error after the collection of few picture about a single hashtag.
Is there any way to fix it?

Best regards

**Comment by aandergr** [comment] 2018-04-11 08:51
Yesterday we noticed that hashtag downloading stopped working and fixed it (5fe2a70). Upgrade to version 3.3.5 and it should work
```
pip3 install --upgrade instaloader
```

**Comment by pvita** [comment] 2018-04-11 09:03
I did it but unfortunately i'm still receiving this error many times during the extraction.

**Comment by aandergr** [comment] 2018-04-11 09:12
I am doing some tests right now and it seems that at the moment `--comments` cannot be used without `--login`.

How are you calling Instaloader? Are you using some additional flags, like `--comments`? Are you using `--login`?  To know the options you give to Instaloader might help us to localize what exactly is broken.

**Comment by pvita** [comment] 2018-04-11 09:15
Thanks andeerg
The query is exactly: instaloader "#hashtag" --comments --geotags --metadata-json --only-if="not is_video"
Without login..

**Comment by aandergr** [comment] 2018-04-11 09:29
My observations at the moment:
- Many GraphQL queries (such as the one needed for `--comments`) seem to be broken if used without `--login`
- My recent commit, 74d5e35e, fixes `--comments` for Posts that have very few comments

**Comment by pvita** [comment] 2018-04-11 09:38
Ok with --login it is collecting json files again. 
Thank you so much

**Comment by aandergr** [comment] 2018-04-11 12:43
Thanks a lot for your report. We now fixed the issue in version 3.3.6, and it should work again even if not logged in.

**Comment by aandergr** [comment] 2018-04-18 09:49
Thanks @creativehelm, @rcola1987, @showmaster3000, @MatthieuBonenfant for reporting the recent breakage. My latest commit, 09f2eb3 might fix the bug, but unfortunately I currently don't have a computer at hand to test it.

To update:
```
pip3 install --upgrade git+https://github.com/instaloader/instaloader
```

We will release a new version as soon it is confirmed that it works.

**Closed** 2018-04-18 14:30 UTC
Labels: bug

**Comment by duttaditya18** [comment] 2018-07-19 09:36
Seeing this error again.

**Comment by duttaditya18** [comment] 2018-07-19 09:41
Okay. So it was because I changed the password.

I fixed it by removing the session file at `/tmp/.instaloader-root/session-<username>`.

Just did : 
```bash
rm /tmp/.instaloader-root/session-<username>
```

**Comment by omidhttp** [comment] 2022-01-19 11:16
```
$ instaloader --login <username> --password ******** --sessionfile .config/instaloader/session-<username>

Loaded session from .config/instaloader/session-<username>
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 403.
```
How can I fix this problem? :/
