### ISSUE TITLE
404 Error when using download_hashtag

### ISSUE THREAD

**Issue by zherbz** [instaloader/instaloader#2402] opened 2024-10-16 21:21 UTC
There seems to be a bug related to any hashtag related functions. I am able to login and even download photos from a profile, but I cannot search/download by a given hashtag name. The error is 404 related, indicating that the endpoint is no longer available. However, the print message shows you the url it is trying to build and use. If you omit the last part after the given hashtag name, then it opens in the browser no problem.

Working: https://www.instagram.com/explore/tags/cat
Broken: https://www.instagram.com/explore/tags/cat/?__a=1&__d=dis

See below for reproducing my error:

**To Reproduce**

# Initialize Instaloader
from instaloader import Instaloader, Profile, Hashtag
L = Instaloader()

# Login using your Instagram credentials
L.login("USERNAME, "PASSWORD)

# Establish a profile instance
profile = Profile.from_username(L.context, "USERNAME)

print(profle)

# Establish a hashtag instance
hashtag = Hashtag.from_name(L.context, "cat")
for post in hashtag.get_posts():
   L.download_post(post, target="#"+hashtag.name)

**Expected behavior**
Downloading of posts associated with the hashtag name "cat"

**Error messages and tracebacks**
JSON Query to explore/tags/cat/: 404 Not Found when accessing https://www.instagram.com/explore/tags/cat/?__a=1&__d=dis [retrying; skip with ^C]
JSON Query to explore/tags/cat/: 404 Not Found when accessing https://www.instagram.com/explore/tags/cat/?__a=1&__d=dis [retrying; skip with ^C]

QueryReturnedNotFoundException: JSON Query to explore/tags/cat/: 404 Not Found when accessing https://www.instagram.com/explore/tags/cat/?__a=1&__d=dis

**Instaloader version**
I have tested this against the following versions and receive the same error each time.
4.11, 4.12, 4.13.1 and 4.14rc1

**Comment by Alkhalf** [comment] 2024-10-22 13:20
same issue too

**Comment by Dbear3347** [comment] 2024-10-24 07:44
same issue too

**Comment by CrypticGuy** [comment] 2024-10-24 17:17
Anyone got any suggestions on patching this, can try to take it up this weekend.

**Comment by aandergr** [comment] 2024-10-26 17:14
Duplicate of #2144

**Closed by aandergr** 2024-10-26 17:14 UTC
Labels: duplicate

**Comment by nehavedam** [comment] 2024-11-07 00:19
I'm also getting the same issue, anyone can tell me how to resolve?
