### ISSUE TITLE
Big bug with hashtag search 

### ISSUE THREAD

**Issue by Kal-Toh** [instaloader/instaloader#1607] opened 2022-06-29 13:57 UTC
When searching for a hashtag the program breaks completely giving a huge amount of errors (too much to copy over). I'm assuming this is after an update from IG as I haven't changed anything on my utilization of the code and tried it fresh.

This can be reproduced by using this minimal code:
from instaloader import Hashtag, Instaloader
htag = "pythonhub"
l = Instaloader()

print(htag)
h = Hashtag.from_name(l.context, htag)
print(h.mediacount)

Instead of printing the post count, it will fail to run resulting in hundreds of lines of errors.
I am using the latest version of instaloader.

The issue seems to be with the entire hashtag module. The same error occurs when using the hashtag function in Instaloader via terminal.

This issue happened to me previously on v4.9.1, but appeared to have resolved itself. It seems to mysteriously have come back so I'm assuming its on Instagrams side?

If someone could try the above code to verify that this issue is not on my end alone that would be appreciated.

**Comment by Oriojas** [comment] 2022-06-29 20:33
Hi, i'm have te same problem

**Comment by leunglong0123** [comment] 2022-06-30 02:16
Same here

**Comment by aarasteh** [comment] 2022-06-30 14:08
Hi, i'm have the same problem

**Comment by David0318** [comment] 2022-06-30 16:57
Hi, I'm have the same problem

**Comment by fireattack** [comment] 2022-07-01 20:09
It works here when I'm not logged in. 

```
import instaloader

L = instaloader.Instaloader()
h = instaloader.Hashtag.from_name(L.context, 'jeanasis')

print(h.mediacount)
```

Prints 263914. The tag you give doesn't seem to return any result even on webpage (https://www.instagram.com/explore/tags/python.hub/).

**Comment by Kal-Toh** [comment] 2022-07-04 10:36
> It works here when I'm not logged in.
> 
> ```python
> import instaloader
> 
> L = instaloader.Instaloader()
> h = instaloader.Hashtag.from_name(L.context, 'jeanasis')
> 
> print(h.mediacount)
> ```
> 
> Prints 263914. The tag you give doesn't seem to return any result even on webpage (https://www.instagram.com/explore/tags/python.hub/).

Apologies, I've corrected that. That included a . in the hashtag which tags never can. 

I can confirm that at the time you posted that it was working as it should and it is currently, however, this problem seems to happen often for a lot of users and since there has not been a diagnosis of the issue, I wouldn't consider it closed.

**Comment by Thammus** [comment] 2022-07-14 18:03
Duplicate of #1588

**Closed by Thammus** 2022-07-14 18:03 UTC
Labels: duplicate
