### ISSUE TITLE
Reels downloading does not work

### ISSUE THREAD

**Issue by AiArtFactory** [instaloader/instaloader#2452] opened 2024-12-05 17:12 UTC
**Describe the bug**
Using the **--reels** flag to attempt to download an account's reels it fails. It will download all normal posts but will either only download a few reels or fail to download any reels at all

**To Reproduce**
(e.g. Instaloader command line)
```
instaloader --login <my-account> --reels --no-metadata --no-captions thecourtneynextdoor
```
**Expected behavior**
Instaloader should download all posts on the account, including reels since the --reels flag was passes. 

**Error messages and tracebacks**
```
instaloader --login <my-account> --reels --no-metadata --no-captions laurenaspyn
Session file does not exist yet - Logging in.
Enter Instagram password for <my-account>:
Logged in as <my-account>.
[1/1] Downloading profile laurenaspyn
Unable to fetch high quality profile pic: 'hd_profile_pic_url_info'
laurenaspyn\2024-07-21_23-06-07_UTC_profile_pic.jpg already exists
Retrieving reels videos for profile laurenaspyn.
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22page_size%22%3A12%2C%22include_feed_video%22%3Atrue%2C%22target_user_id%22%3A%228181048316%22%7D%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7845543455542541&server_timestamps=true [retrying; skip with ^C]
Download reels of laurenaspyn: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22page_size%22%3A12%2C%22include_feed_video%22%3Atrue%2C%22target_user_id%22%3A%228181048316%22%7D%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7845543455542541&server_timestamps=true
Retrieving posts from profile laurenaspyn.
[ 1/17] laurenaspyn\2024-12-04_20-40-21_UTC.jpg exists laurenaspyn\2024-12-04_20-40-21_UTC.mp4 exists
[ 2/17] laurenaspyn\2024-10-30_19-15-29_UTC_1.jpg exists laurenaspyn\2024-10-30_19-15-29_UTC_2.jpg exists laurenaspyn\2024-10-30_19-15-29_UTC_3.jpg exists laurenaspyn\2024-10-30_19-15-29_UTC_4.jpg exists laurenaspyn\2024-10-30_19-15-29_UTC_5.jpg exists laurenaspyn\2024-10-30_19-15-29_UTC_6.jpg exists
[ 3/17] laurenaspyn\2024-08-22_19-34-56_UTC_1.jpg exists laurenaspyn\2024-08-22_19-34-56_UTC_2.jpg exists
[ 4/17] laurenaspyn\2024-06-14_19-18-36_UTC.jpg exists
[ 5/17] laurenaspyn\2024-06-07_18-52-12_UTC.jpg exists
[ 6/17] laurenaspyn\2024-05-19_20-03-48_UTC.jpg exists
[ 7/17] laurenaspyn\2024-04-23_19-52-02_UTC.jpg exists
[ 8/17] laurenaspyn\2024-03-23_19-54-25_UTC_1.jpg exists laurenaspyn\2024-03-23_19-54-25_UTC_2.jpg exists
[ 9/17] laurenaspyn\2023-12-25_20-29-25_UTC_1.jpg exists laurenaspyn\2023-12-25_20-29-25_UTC_2.jpg exists
[10/17] laurenaspyn\2023-12-13_20-13-05_UTC_1.jpg exists laurenaspyn\2023-12-13_20-13-05_UTC_2.jpg exists
[11/17] laurenaspyn\2023-11-24_00-48-32_UTC_1.jpg exists laurenaspyn\2023-11-24_00-48-32_UTC_2.jpg exists laurenaspyn\2023-11-24_00-48-32_UTC_3.jpg exists
[12/17] laurenaspyn\2023-11-01_19-36-16_UTC_1.jpg exists laurenaspyn\2023-11-01_19-36-16_UTC_2.jpg exists
[13/17] laurenaspyn\2023-10-18_16-19-05_UTC_1.jpg exists laurenaspyn\2023-10-18_16-19-05_UTC_2.jpg exists laurenaspyn\2023-10-18_16-19-05_UTC_3.jpg exists laurenaspyn\2023-10-18_16-19-05_UTC_4.jpg exists laurenaspyn\2023-10-18_16-19-05_UTC_5.jpg exists
[14/17] laurenaspyn\2023-07-30_17-59-50_UTC_1.jpg exists laurenaspyn\2023-07-30_17-59-50_UTC_2.jpg exists
[15/17] laurenaspyn\2023-07-07_21-55-52_UTC_1.jpg exists laurenaspyn\2023-07-07_21-55-52_UTC_2.jpg exists laurenaspyn\2023-07-07_21-55-52_UTC_3.jpg exists
[16/17] laurenaspyn\2022-09-22_17-15-15_UTC_1.jpg exists laurenaspyn\2022-09-22_17-15-15_UTC_2.jpg exists laurenaspyn\2022-09-22_17-15-15_UTC_3.jpg exists
[17/17] laurenaspyn\2022-06-07_18-35-00_UTC.jpg exists
Saved session to C: ~.\Instaloader\session-<my-account>.
```

Errors or warnings occurred:
```
Retrieving reels videos for profile laurenaspyn.
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22page_size%22%3A12%2C%22include_feed_video%22%3Atrue%2C%22target_user_id%22%3A%228181048316%22%7D%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7845543455542541&server_timestamps=true [retrying; skip with ^C]
Download reels of laurenaspyn: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22page_size%22%3A12%2C%22include_feed_video%22%3Atrue%2C%22target_user_id%22%3A%228181048316%22%7D%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7845543455542541&server_timestamps=true
```

**Instaloader version**
4.14

**Additional context**
I've tested this on multiple accounts and get the same kind of error. It will download all other posts on the account but specifically fails to download reels videos.

**Comment by aandergr** [comment] 2024-12-27 07:28
This issue appears to be a duplicate of #2307, as the underlying problem is related to Instagram's API returning `401 Unauthorized` errors, which affects specific types of queries, including downloading reels. Please refer to #2307 for updates and discussions regarding this behavior.

We will close this issue to consolidate efforts and keep the discussion focused. If you believe your issue is significantly different, please provide additional details.

**Closed by aandergr** 2024-12-27 07:28 UTC
Labels: duplicate
