### ISSUE TITLE
login loop 

### ISSUE THREAD

**Issue by avinash893** [instaloader/instaloader#1887] opened 2023-02-09 20:02 UTC
**Describe the bug**
A clear and concise description of what the bug is. i try to login it gives me a link to reset password after changing password im within same loop of getting link and change password.

**To Reproduce**
python main.py      , python3 main.py mot working for me.

**Expected behavior**
i thought it will just ask my conformation but it leds to loop of conformation

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
`instaloader --4.5.5.

**Additional context**
im in a login loop,i use the code "python main.py" it gives me a link after authorization to give login location after that it takes me to change instagram password
![Screenshot 2023-02-10 013542](https://user-images.githubusercontent.com/119433529/217926541-cf604398-272e-4bfd-9623-aebe3609d2c8.png)
![Screenshot 2023-02-10 013605](https://user-images.githubusercontent.com/119433529/217926562-5d918713-3ace-4409-8844-04f5f92af2c9.png)
![Screenshot 2023-02-10 013621](https://user-images.githubusercontent.com/119433529/217926600-7a1abb86-9f61-4412-98e1-09a7d1f86880.png)
.

**Comment by Marcinolak** [comment] 2023-02-10 02:54
That happened to me many times. Just use scripts below to get cookie file from your web browser. 

Firefox (recommended): https://instaloader.github.io/troubleshooting.html#login-error
Chrome (harder, but possible): https://github.com/instaloader/instaloader/issues/1821

If you' re using Windows you can also use my pack to make your life easier (download scripts, importers, options included).
Remember to install PIP.
Enjoy!
[instaloader_win_auto.zip](https://github.com/instaloader/instaloader/files/10703246/instaloader_win_auto.zip)

**Comment by avinash893** [comment] 2023-02-10 04:25
thanks for fix.

**Comment by avinash893** [comment] 2023-02-12 11:35
i'm a noob ,i have got the cookie file but dont know what to do,do i have to insert it somewhere ?please specify path

**Comment by aandergr** [comment] 2023-02-18 16:52
Duplicate of #1787

**Closed by aandergr** 2023-02-18 16:52 UTC
Labels: duplicate
