### ISSUE TITLE
Error in V3.3

### ISSUE THREAD

**Issue by ShihabZzz** [instaloader/instaloader#82] opened 2018-03-14 07:01 UTC
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.3', 'console_scripts', 'instaloader')()
  File "c:\program files\python36\lib\site-packages\instaloader.py", line 1742, in main
    filter_str=args.only_if)
  File "c:\program files\python36\lib\site-packages\instaloader.py", line 1568, in main
    filter_func=filter_func)
  File "c:\program files\python36\lib\site-packages\instaloader.py", line 1428, in download_profile
    name_updated, profile_id = self.check_profile_id(name, profile_metadata)
  File "c:\program files\python36\lib\site-packages\instaloader.py", line 1351, in check_profile_id
    profile_id = int(id_file.read())
ValueError: invalid literal for int() with base 10: b''

**Comment by aandergr** [comment] 2018-03-14 07:02
Duplicate of #81

**Closed by aandergr** 2018-03-14 07:02 UTC
