### ISSUE TITLE
Fatal error: Login: Checkpoint required.

### ISSUE THREAD

**Issue by TahaHydra** [instaloader/instaloader#1864] opened 2023-01-19 09:28 UTC
**Describe the bug**

**To Reproduce**
(e.g. Instaloader command line)

**Expected behavior**
using the login it's supposed to login on it's own but i have to go click on the button after it gives me a link to confirm in the command line and asks me to retry
**Error messages and tracebacks**
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action
**Instaloader version**
`instaloader --version` output.
4.9.5
**Additional context**
can we have an auto check for the test please

**Comment by Showmaster3000** [comment] 2023-01-20 00:25
incomplete bug report.
duplicate of #1787.

**Closed by Showmaster3000** 2023-01-20 00:25 UTC
Labels: bug
