### ISSUE TITLE
Unable to download stories by location id

### ISSUE THREAD

**Issue by sbruselario** [instaloader/instaloader#415] opened 2019-09-24 00:37 UTC
When I combine %location id with --stories just download the recent posts from %location id but not stories.

instaloader --login *************** --password ***************  --stories  %locationID

instaloader --version
4.2.9

**Comment by aandergr** [comment] 2019-09-24 06:20
Duplicate of #367.

This is not a bug, it's just not implemented yet.

**Closed** 2019-10-13 18:26 UTC
Labels: duplicate
