### ISSUE TITLE
is Instaloader dead? instaloader Checkpoint Two-Factor-Authentication Login error

### ISSUE THREAD

**Issue by crackbanana** [instaloader/instaloader#382] opened 2019-08-18 06:37 UTC
**Describe the bug**
Instaloader gives me this checkpoint error since 1 month!
 when i try to login with my account with --login --password

`Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/8738755788/JrYzGXkR9C/ - follow the instructions, then retry.
`
i follow the link i insert the code and nothing happens, it still gives me the same error repeatedly

and when i try to import my login cookies from Firefox to Instaloader it gives me

`$ python3 ses.py
Traceback (most recent call last):
  File "ses.py", line 5, in <module>
    from instaloader import ConnectionException
ModuleNotFoundError: No module named 'instaloader`

i'm using their guide from their troubleshoot
https://instaloader.github.io/troubleshooting.html

how to resolve this problem?

**Comment by aandergr** [comment] 2019-08-20 20:11
Duplicate of #328.

> and when i try to import my login cookies from Firefox to Instaloader it gives me
> 
> `$ python3 ses.py Traceback (most recent call last): File "ses.py", line 5, in <module> from instaloader import ConnectionException ModuleNotFoundError: No module named 'instaloader`

This looks like Instaloader is not properly installed.

**Closed by aandergr** 2019-08-20 20:11 UTC
