### ISSUE TITLE
Failed to get profile from username

### ISSUE THREAD

**Issue by chanccm** [instaloader/instaloader#302] opened 2019-05-17 06:35 UTC
**Describe the bug**
fail to get profile when 'from_username' was used
profile = instaloader.Profile.from_username(L.context, USERNAME)

gives error:
Out:
ProfileNotExistsException: Profile _lisa1431_ does not exist.

**To Reproduce**
L = instaloader.Instaloader()
username = my_username
password = my_userid
L.login(my_username, my_password)

profile = instaloader.Profile.from_username(L.context, '_lisa1431_')

**Expected behavior**
<Profile _lisa1431_ (3708154416)>

**Error messages and tracebacks**
KeyError                                  Traceback (most recent call last)
~/instaloader/structures.py in _obtain_metadata(self)
    519                 self._node = metadata['entry_data']['ProfilePage'][0]['graphql']['user']
--> 520                 self._rhx_gis = metadata['rhx_gis']
    521         except (QueryReturnedNotFoundException, KeyError) as err:

KeyError: 'rhx_gis'

The above exception was the direct cause of the following exception:

ProfileNotExistsException                 Traceback (most recent call last)
<ipython-input-7-f4550b82f1fe> in <module>
----> 1 profile = instaloader.Profile.from_username(L.context, '_lisa1431_')

**Instaloader version**
4.2.4

**Additional context**
able to get profile when from_id was used, and I'm sure the profile '_lisa1431_' exists

In:
profile = instaloader.Profile.from_id(L.context, 3708154416)
profile
Out:
<Profile _lisa1431_ (3708154416)>

**Comment by GolvenLD** [comment] 2019-05-17 07:42
This has been discussed in another issue, I suggest you take a look at [this](https://github.com/instaloader/instaloader/issues/297). A user already posted a fix, and although he warns about the fact that it is a quick fix (maybe not a very legit one) it works fine for most of the data.

**Comment by aandergr** [comment] 2019-05-17 16:16
Duplicate of #297.

**Closed by aandergr** 2019-05-17 16:16 UTC
